### ISSUE TITLE
FullHttpResponseToMockServerResponse.setCookies() NullPointerException error!!!

### ISSUE THREAD

**Issue by Desperadolh** [mock-server/mockserver#1000]
use version mock-server-5.9.0 forward type HTTPS requests  appear NullPointerException errors

The version you are using (5.9.0)

**To Reproduce**
Steps to reproduce the issue:

1.I use mockserver forward type HTTPS requests to remote server ,some requests can get response ,but some appear error 
2.I use the command like that
java -jar <path to mockserver-jetty-jar-with-dependencies.jar> -serverPort <port> [-proxyRemotePort <port>] [-proxyRemoteHost <hostname>] [-logLevel <level>] 
then use chrome request remote server 
same error appear too

error below....

**Expected behaviour**
i hope i can mockserver success ,and use chrome can surfing remote server success

**MockServer Log**
2021-03-16 18:19:48.257 ERROR 65120 --- [MockServer-EventLog86] org.mockserver.log.MockServerEventLog    : exception decoding request

        HttpObjectAggregator$AggregatedFullHttpResponse(decodeResult: success, version: HTTP/1.1, content: CompositeByteBuf(freed, components=1))
        HTTP/1.1 200 
        Date: Tue, 16 Mar 2021 10:20:17 GMT
        Server: Apache
        X-Application-Context: perbank:7725
        Set-Cookie: secure;HTTPOnly
        Content-Length: 502
        Set-Cookie: BIGipServerpool_perbank_7725_middle=!XJdHjPezbeyuDvHhrn2uthKM5ieXSuAcXbVH8ilZRP2Sq+G4kVunzc5eMnxQr7Vf/G6dPBitz+bBhEU=; expires=Tue, 16-Mar-2021 10:50:17 GMT; path=/
        Keep-Alive: timeout=5, max=100
        Connection: Keep-Alive
        Content-Type: application/json;charset=utf-8

java.lang.NullPointerException: null
        at org.mockserver.mappers.FullHttpResponseToMockServerResponse.setCookies(FullHttpResponseToMockServerResponse.java:72)
        at org.mockserver.mappers.FullHttpResponseToMockServerResponse.mapFullHttpResponseToMockServerResponse(FullHttpResponseToMockServerResponse.java:34)
        at org.mockserver.codec.NettyToMockServerResponseDecoder.decode(NettyToMockServerResponseDecoder.java:24)
        at org.mockserver.codec.NettyToMockServerResponseDecoder.decode(NettyToMockServerResponseDecoder.java:14)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:316)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1470)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1219)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1266)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:493)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:432)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:271)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.lang.Thread.run(Thread.java:745)

**Comment by jamesdbloom** [comment]
MockServer 5.9.0 is a very old version of MockServer please upgrade. 

I have reviewed the code and fixed the only potential source of NullPointerExceptions in this method, so this issue should now be fixed.
