### ISSUE TITLE
X500Name is internal in Java 16

### ISSUE THREAD

**Issue by reitzig** [mock-server/mockserver#1031]
**Describe the issue**
Previously functional integration tests (Java 11) break when being run with Java 16.

**What you are trying to do**
Migrate project to Java 16

**MockServer version**
5.11.2

**To Reproduce**
Steps to reproduce the issue:

1. We run Spring Boot integration tests annotated like so:
    ```java
    @MockServerTest({"mockserver.dynamicallyCreateCertificateAuthorityCertificate=true"})
    @SpringBootTest(
        webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT,
        properties = {"some.service.url=https://localhost:${mockServerPort}"})
    ````
    
2. We want to test error handling for invalid server certificates, so all we set up is a dummy expectation:
    ```java
    mockServerClient.when(request()
        .withPath("/our/path")
    ).respond(response()
        .withStatusCode(200)
    );
    ```

3. Upon receiving the request, MockServer errors:
    ```
        2021-06-02 13:24:05,536 [MockServer-EventLog0] [invoice-soe,,] ERROR o.m.log.MockServerEventLog - exception creating SSL context for serverclass org.mockserver.socket.tls.jdk.X509Generator (in unnamed module @0x335eadca) cannot access class sun.security.x509.X500Name (in module java.base) because module java.base does not export sun.security.x509 to unnamed module @0x335eadca
    java.lang.IllegalAccessError: class org.mockserver.socket.tls.jdk.X509Generator (in unnamed module @0x335eadca) cannot access class sun.security.x509.X500Name (in module java.base) because module java.base does not export sun.security.x509 to unnamed module @0x335eadca
        at org.mockserver.socket.tls.jdk.X509Generator.generateLeafX509AndPrivateKey(X509Generator.java:52)
        at org.mockserver.socket.tls.jdk.JDKKeyAndCertificateFactory.buildAndSavePrivateKeyAndX509Certificate(JDKKeyAndCertificateFactory.java:195)
        at org.mockserver.socket.tls.NettySslContextFactory.createServerSslContext(NettySslContextFactory.java:132)
        at org.mockserver.socket.tls.SniHandler.lookup(SniHandler.java:31)
        at io.netty.handler.ssl.AbstractSniHandler.lookup(AbstractSniHandler.java:126)
        at io.netty.handler.ssl.SslClientHelloHandler.select(SslClientHelloHandler.java:188)
        at io.netty.handler.ssl.SslClientHelloHandler.decode(SslClientHelloHandler.java:149)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at org.mockserver.netty.unification.PortUnificationHandler.enableTls(PortUnificationHandler.java:201)
        at org.mockserver.netty.unification.PortUnificationHandler.decode(PortUnificationHandler.java:135)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:831)
    2021-06-02 13:24:05,687 [MockServer-EventLog0] [invoice-soe,,] ERROR o.m.log.MockServerEventLog - exception creating SSL context for serverclass org.mockserver.socket.tls.jdk.X509Generator (in unnamed module @0x335eadca) cannot access class sun.security.x509.X500Name (in module java.base) because module java.base does not export sun.security.x509 to unnamed module @0x335eadca
    java.lang.IllegalAccessError: class org.mockserver.socket.tls.jdk.X509Generator (in unnamed module @0x335eadca) cannot access class sun.security.x509.X500Name (in module java.base) because module java.base does not export sun.security.x509 to unnamed module @0x335eadca
        at org.mockserver.socket.tls.jdk.X509Generator.generateLeafX509AndPrivateKey(X509Generator.java:52)
        at org.mockserver.socket.tls.jdk.JDKKeyAndCertificateFactory.buildAndSavePrivateKeyAndX509Certificate(JDKKeyAndCertificateFactory.java:195)
        at org.mockserver.socket.tls.NettySslContextFactory.createServerSslContext(NettySslContextFactory.java:132)
        at org.mockserver.socket.tls.SniHandler.lookup(SniHandler.java:31)
        at io.netty.handler.ssl.AbstractSniHandler.lookup(AbstractSniHandler.java:126)
        at io.netty.handler.ssl.SslClientHelloHandler.select(SslClientHelloHandler.java:188)
        at io.netty.handler.ssl.SslClientHelloHandler.decode(SslClientHelloHandler.java:169)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at org.mockserver.netty.unification.PortUnificationHandler.enableTls(PortUnificationHandler.java:201)
        at org.mockserver.netty.unification.PortUnificationHandler.decode(PortUnificationHandler.java:135)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:831)
    ```
   The client then fails with:
   ````
     java.io.EOFException: SSL peer shut down incorrectly
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:483)
	at java.base/sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
    ````

**Expected behaviour**
MockServer

**MockServer Log**
Log output, as INFO level (or lower)

**Comment by imrel** [comment]
looks to be quite small change needed, limited only to org.mockserver.socket.tls.jdk.X509Generator

until then this workaround works in jdk 16 and 17 
```
test {
    jvmArgs '--add-opens=java.base/sun.security.x509=ALL-UNNAMED'
}
```
(or maybe using bouncycastle instead?)

**Comment by jamesdbloom** [comment]
@imrel when you say a small change could you please provide some more information?  

MockServer is build using JDK 8 as that is still the most commonly used version of Java according to surveys in 2021, so I'm not sure how I can easily provide the information needed.  The JDK libraries are used to avoid using the massively bloated BouncyCastle library.

The only way I know to avoid using sun.security.x509.* is to write custom X509 generation logic.  I do have some of that from another project but I wanted to avoid porting that over.

**Comment by jamesdbloom** [comment]
Does PR #622 fully fix the issue you are referring to?  Is so should this issue now be closed.  Please take against the latest SNAPSHOT release which have been build since that PR was merged.

**Comment by imrel** [comment]
Thank you for taking a look at this. 
using version 5.11.2

Since Java 16+ JDK internals is now strongly encapsulated by default, so we can not use sun.security... etc internals

By "small change" I mean that there are not a lot of uses in this codebase:
 https://github.com/mock-server/mockserver/search?q=%22sun.security%22

if java.security.cert.CertificateFactory etc are not enough then indeed some custom logic has to be implemented. 

I only mentioned BouncyCastle for people who may seek workarounds, but I have no idea if it would work.

**Comment by jamesdbloom** [comment]
MockServer does current support BouncyCastle as an option but it has to be provided on the class path if someone wants to use it which would be complex for helm, docker, homebrew, node, etc

I have implemented custom X509 creation logic before but it's not ideal.  It's pretty shocking this logic was ever internal as it is just as standard as other non-internal classes such as File.

I'll look and see if I can replace the X509 logic with custom logic that generates identical certificates in the next few weeks.

**Comment by jamesdbloom** [comment]
I think it is impractical to implement this logic without either JDK libraries or BouncyCastle so I've added logic to catch the different error and fallback to BouncyCastle, if that fails then an message is printed with two options to resolve the issue (1) add the JVM flags to allow access at runtime or (2) add the BouncyCastle dependencies to the classpath.
