### ISSUE TITLE
Corrupted Response in Velocity Template

### ISSUE THREAD

**Issue by beulahgunasekar-earnin** [mock-server/mockserver#1035]
**Describe the issue**
The response after processing the request header is corrupted in the Velocity template

**What you are trying to do**
We are using Velocity Template and trying to get the request ID from header and apply it on the response header before sending the response back

Here is the sample 
```
"httpResponseTemplate": {
      "templateType": "VELOCITY",
      "template": "{"statusCode":200, 
      "RequestId":["$!request.headers["RequestId"][0]"]
    }
```

and the response is generated like this 
```
`2021-06-15 17:04:21  org.mockserver.log.MockServerEventLog  INFO  generated output:

  **{"statusCode":200,"reasonPhrase":"OK","headers":{"Date":["Mon, 14 Jun 2021 19:58:14 GMT"],"Content-Type":["application/json; charset\u003dutf-8"],"Content-Length":["35"],"Connection":["keep-alive"],"Server":["Microsoft-IIS/10.0"],"RequestId":["6EB64C0D-3991-4D5E-B94B-696F25E24AAF"],"X-Powered-By":["ASP.NET"]},"body":"{\r\n  \"riskLevel\": \"NotAvailable\"\r\n}"}**{"statusCode":200,"reasonPhrase":"OK","headers":{"Date":["Mon, 14 Jun 2021 19:58:14 GMT"],"Content-Type":["application/json; charset\u003dutf-8"],"Content-Length":["71"],"Connection":["keep-alive"],"Server":["Microsoft-IIS/10.0"],"RequestId":["6EB64C0D-3991-4D5E-B94B-696F25E24AAF"],"X-Powered-By":["ASP.NET"]},"body":"{\r\n  \"enabled\": false,\r\n  \"workLocations\": [],\r\n  \"PIPLocations\": []\r\n}"}

 from template:

  {"statusCode":200,"reasonPhrase":"OK","headers":{"Date":["Mon, 14 Jun 2021 19:58:14 GMT"],"Content-Type":["application/json; charset\u003dutf-8"],"Content-Length":["71"],"Connection":["keep-alive"],"Server":["Microsoft-IIS/10.0"],"RequestId":["$!request.headers["RequestId"][0]"],"X-Powered-By":["ASP.NET"]},"body":"{\r\n  \"enabled\": false,\r\n  \"workLocations\": [],\r\n  \"PIPLocations\": []\r\n}"}`
```

Also got the error mentioned below

**MockServer version**
5.10.0

**To Reproduce**
Steps to reproduce the issue:

using java
java -jar mockserver.jar -serverPort 1080

**Expected behaviour**
What you expected to happen

**MockServer Log**
```
2021-06-15 17:04:21  org.mockserver.log.MockServerEventLog  SEVERE  exception transforming json:


 
com.fasterxml.jackson.databind.exc.MismatchedInputException: No content to map due to end-of-input
 at [Source: (String)""; line: 1, column: 0]
	at com.fasterxml.jackson.databind.exc.MismatchedInputException.from(MismatchedInputException.java:59)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4344)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4189)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3173)
	at org.mockserver.templates.engine.serializer.HttpTemplateOutputDeserializer.deserializer(HttpTemplateOutputDeserializer.java:46)
	at org.mockserver.templates.engine.velocity.VelocityTemplateEngine.executeTemplate(VelocityTemplateEngine.java:59)
	at org.mockserver.mock.action.HttpResponseTemplateActionHandler.handle(HttpResponseTemplateActionHandler.java:42)
	at org.mockserver.mock.action.ActionHandler.lambda$null$3(ActionHandler.java:103)
	at org.mockserver.mock.action.ActionHandler.handleAnyException(ActionHandler.java:285)
	at org.mockserver.mock.action.ActionHandler.lambda$processAction$4(ActionHandler.java:102)
	at org.mockserver.scheduler.Scheduler.run(Scheduler.java:67)
	at org.mockserver.scheduler.Scheduler.schedule(Scheduler.java:104)
	at org.mockserver.mock.action.ActionHandler.processAction(ActionHandler.java:102)
	at org.mockserver.netty.MockServerHandler.channelRead0(MockServerHandler.java:147)
	at org.mockserver.netty.MockServerHandler.channelRead0(MockServerHandler.java:46)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.mockserver.dashboard.DashboardWebSocketServerHandler.channelRead(DashboardWebSocketServerHandler.java:130)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.mockserver.closurecallback.websocketregistry.CallbackWebSocketServerHandler.channelRead(CallbackWebSocketServerHandler.java:56)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by jamesdbloom** [comment]
The template is not a valid format please see the recently improved template documentation for velocity response templates: https://mock-server.com/mock_server/response_templates.html#velocity_templates.

You might also prefer the simpler mustache templates added in the last release: https://mock-server.com/mock_server/response_templates.html#mustache_templates

Here is a comparison of the different response template formates: https://mock-server.com/mock_server/response_templates.html

**Comment by beulahgunasekar-earnin** [comment]
Thanks for the response, will try the new format.
