### ISSUE TITLE
Build is broken in master due to expired certificates

### ISSUE THREAD

**Issue by brunopalos** [mock-server/mockserver#1064]
**Describe the issue**

Master is currently failing to build due to expired certificates.

I would have opened a PR to fix this but I'm unable to generate valid certificates for the integration tests.

**What you are trying to do**
I'm trying to submit a Pull Request but the build is failing.

**MockServer version**
5.11.3-SNAPSHOT

**To Reproduce**
Steps to reproduce the issue:

1. Run the build with `mvn clean install -Djavax.net.debug=all` 
2. Some tests fail due to expired certificates.

**Expected behaviour**
The build to pass.

**MockServer Log**
```
javax.net.ssl|ERROR|1A|MockServer-MockServer-workerEventLoop10|2021-08-23 17:35:51.689 WEST|TransportContext.java:312|Fatal (CERTIFICATE_UNKNOWN): PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed (
"throwable" : {
  sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
        at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:350)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:248)
        at java.base/sun.security.validator.Validator.validate(Validator.java:264)
        at java.base/sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:313)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:276)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkClientTrusted(X509TrustManagerImpl.java:135)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkClientCerts(CertificateMessage.java:669)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:398)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:366)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:392)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:443)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1061)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask$DelegatedAction.run(SSLEngineImpl.java:1048)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.security.ssl.SSLEngineImpl$DelegatedTask.run(SSLEngineImpl.java:995)
        at io.netty.handler.ssl.SslHandler.runAllDelegatedTasks(SslHandler.java:1557)
        at io.netty.handler.ssl.SslHandler.runDelegatedTasks(SslHandler.java:1571)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1455)
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1282)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1329)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:834)
  Caused by: java.security.cert.CertPathValidatorException: validity check failed
        at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:233)
        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:141)
        at java.base/sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:80)
        at java.base/java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
        at java.base/sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:345)
        ... 37 more
  Caused by: java.security.cert.CertificateExpiredException: NotAfter: Sun Jan 24 07:51:00 WET 2021
        at java.base/sun.security.x509.CertificateValidity.valid(CertificateValidity.java:274)
        at java.base/sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:687)
        at java.base/sun.security.provider.certpath.BasicChecker.verifyValidity(BasicChecker.java:190)
        at java.base/sun.security.provider.certpath.BasicChecker.check(BasicChecker.java:144)
        at java.base/sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
        ... 42 more}

```

```
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.522 s - in org.mockserver.cors.OverridePreFlightRequestIntegrationTest
--
  | [INFO]
  | [INFO] Results:
  | [INFO]
  | [ERROR] Errors:
  | [ERROR]   ClientAuthenticationAdditionalCertificateChainMockingIntegrationTest.shouldReturnResponseInHttpsApacheClient:125 ? SSL
  | [ERROR]   ClientAuthenticationCustomPrivateKeyAndCertificateMockingIntegrationTest>AbstractClientAuthenticationMockingIntegrationTest.shouldFailToAuthenticateInHttpApacheClient:169 ? Runtime
  | [ERROR]   ClientAuthenticationCustomPrivateKeyAndCertificateMockingIntegrationTest>AbstractClientAuthenticationMockingIntegrationTest.shouldFailToAuthenticateInHttpsApacheClient:130 ? Runtime
  | [ERROR]   ClientAuthenticationCustomPrivateKeyAndCertificateMockingIntegrationTest.shouldReturnExpectedX509Certificate:93 ? Runtime
  | [ERROR]   ClientAuthenticationCustomPrivateKeyAndCertificateMockingIntegrationTest>AbstractClientAuthenticationMockingIntegrationTest.shouldReturnResponseInHttpsApacheClient:100 ? Runtime
  | [ERROR]   ClientAuthenticationCustomPrivateKeyAndCertificateMockingIntegrationTest>AbstractClientAuthenticationMockingIntegrationTest.shouldReturnResponseInHttpsNettyClient:70 ? Runtime
  | [ERROR]   ClientAuthenticationCustomPrivateKeyAndCertificateMockingIntegrationTest>AbstractClientAuthenticationMockingIntegrationTest.shouldReturnUpgradeForHttp:41 ? Runtime


```

**Comment by brunopalos** [comment]
@jamesdbloom FYI ☝️

**Comment by jamesdbloom** [comment]
This is now fixed and the master build is fixed.  I have also attempted to work around a bug in buildkite separately causing PR builds to fail.  The master build is now passing.
