### ISSUE TITLE
Calling verify on a ClientAndServer Instance Causes a SocketConnectionException

### ISSUE THREAD

**Issue by pbtura** [mock-server/mockserver#1072]
**Describe the issue**
Calling verify(request, times) on a running ClientAndServer instance will fail with the exception: "org.mockserver.client.SocketConnectionException: Channel handler removed before valid response has been received"

**What you are trying to do**
I am currently trying to use MockServer to mock out a call to an external web service in my unit tests. Before getting into testing my actual application I set up a simple test to make sure I had a handle on the basics of using MockServer. I created a unit test and added code to initialize and run the mock server, create and execute a simple GET request, and validate the response. I got the test working and then I decided I wanted to verify the request. As soon as I added the verify call, the test started throwing an exception.

**MockServer version**
5.11.2

**To Reproduce**
Steps to reproduce the issue:

The code is being run as a JUnit4 test in eclipse.
Environment:
OSX 10.14.6
Eclipse 4.6
JDK 1.8

```
@Test
	public void getShouldWork() throws URISyntaxException, IOException {

	    final String responseBody = "some_response_body";
	    final String respHdrName = "some_header";
	    final String respHdrVal = "some value";
	    ClientAndServer mockServer = ClientAndServer.startClientAndServer(1080);
	    HttpRequest request = HttpRequest.request()
                .withMethod("GET")
                .withPath("/some/url")
                .withQueryStringParameter("id", "9"); 
	    mockServer.when(
	    		request,
	            Times.exactly(1)
	        )
	        .respond(
	        		HttpResponse.response()
	                .withBody(responseBody)
	                .withHeader(respHdrName, respHdrVal)
	        );
	    
	    CloseableHttpClient httpClient = HttpClientBuilder.create()
	            .build();
	    
	    HttpGet getRequest = new HttpGet("http://localhost:" + mockServer.getPort()
	            + "/some/url?id=9");
	    CloseableHttpResponse resp = httpClient.execute(getRequest);
	   
            //an exception will be thrown here. removing this line will cause the test to pass.
 	    mockServer.verify(request, VerificationTimes.exactly(1));

	    try (InputStreamReader isr = new InputStreamReader(resp.getEntity().getContent());
	            BufferedReader br = new BufferedReader(isr);) {
	        assertThat(br.readLine(), is(responseBody));
	        while (br.readLine() != null) {
	            // consume content...
	        }
	    }
	    assertThat(
	            resp.getFirstHeader(respHdrName), 
	            is(notNullValue()));
	    assertThat(
	            resp.getFirstHeader(respHdrName).getValue(), 
	            is(respHdrVal));
	}
```

**Expected behaviour**
The test should pass since the request was made exactly once

**MockServer Log**
Not sure how to get the actual MockServer logs but the stack trace for the error is:
```
org.mockserver.client.SocketConnectionException: Channel handler removed before valid response has been received
	at org.mockserver.client.HttpClientConnectionErrorHandler.handlerRemoved(HttpClientConnectionErrorHandler.java:20)
	at io.netty.channel.AbstractChannelHandlerContext.callHandlerRemoved(AbstractChannelHandlerContext.java:946)
	at io.netty.channel.DefaultChannelPipeline.callHandlerRemoved0(DefaultChannelPipeline.java:637)
	at io.netty.channel.DefaultChannelPipeline.destroyDown(DefaultChannelPipeline.java:876)
	at io.netty.channel.DefaultChannelPipeline.destroyUp(DefaultChannelPipeline.java:844)
	at io.netty.channel.DefaultChannelPipeline.destroy(DefaultChannelPipeline.java:836)
	at io.netty.channel.DefaultChannelPipeline.access$700(DefaultChannelPipeline.java:46)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelUnregistered(DefaultChannelPipeline.java:1392)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:198)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelUnregistered(AbstractChannelHandlerContext.java:184)
	at io.netty.channel.DefaultChannelPipeline.fireChannelUnregistered(DefaultChannelPipeline.java:821)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:827)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:745)


```

**Comment by jamesdbloom** [comment]
I can't reproduce this error.  I image something else on your computer may be using that port or sending a close request to that port.  For example if a docker container is exposing that port then multiple things can be bound to the same port because docker doesn't always lock a port always.

Can you try re-running the test without specifying the port as folows:
```java
@Test
public void getShouldWork() throws URISyntaxException, IOException {

    final String responseBody = "some_response_body";
    final String respHdrName = "some_header";
    final String respHdrVal = "some value";
    ClientAndServer mockServer = ClientAndServer.startClientAndServer();
    HttpRequest request = HttpRequest.request()
        .withMethod("GET")
        .withPath("/some/url")
        .withQueryStringParameter("id", "9");
    mockServer.when(
            request,
            Times.exactly(1)
        )
        .respond(
            HttpResponse.response()
                .withBody(responseBody)
                .withHeader(respHdrName, respHdrVal)
        );

    CloseableHttpClient httpClient = HttpClientBuilder.create()
        .build();

    HttpGet getRequest = new HttpGet("http://localhost:" + mockServer.getPort()
        + "/some/url?id=9");
    CloseableHttpResponse resp = httpClient.execute(getRequest);

    // an exception will be thrown here. removing this line will cause the test to pass.
    mockServer.verify(request, VerificationTimes.exactly(1));

    try (InputStreamReader isr = new InputStreamReader(resp.getEntity().getContent());
         BufferedReader br = new BufferedReader(isr);) {
        assertThat(br.readLine(), is(responseBody));
        while (br.readLine() != null) {
            // consume content...
        }
    }
    assertThat(
        resp.getFirstHeader(respHdrName),
        is(notNullValue()));
    assertThat(
        resp.getFirstHeader(respHdrName).getValue(),
        is(respHdrVal));
}
```

**Comment by damoncoo** [comment]
I think the issue still exists in latest version 5.15.0, when I switch old last version, it works

**Comment by wyy0117** [comment]
I get this exception too with version 5.15.0
org.mockserver.httpclient.SocketConnectionException: Channel handler removed before valid response has been received
