### ISSUE TITLE
org.mockserver.client.SocketConnectionException: Unable to connect to socket localhost/127.0.0.1:1080

### ISSUE THREAD

**Issue by bhavithadornala** [mock-server/mockserver#1073]
Hi, 
I am trying to start mockserver in my gradle project with the following code

`ClientAndServer.startClientAndServer("localhost", 1080);`

it is giving me the connection refused error

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'startMockServer': Invocation of init method failed; nested exception is org.mockserver.client.SocketConnectionException: Unable to connect to socket localhost/127.0.0.1:1080
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1788)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:882)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.centime.mockservice.MockServiceApplication.main(MockServiceApplication.java:20)
Caused by: org.mockserver.client.SocketConnectionException: Unable to connect to socket localhost/127.0.0.1:1080`

**Comment by jamesdbloom** [comment]
It looks like MockServer isn't running when Spring is attempting to create the bean for the MockServerClient

**Comment by jamesdbloom** [comment]
Closing due to inactivity
