### ISSUE TITLE
Expectations are not created during docker container startup.

### ISSUE THREAD

**Issue by Drezir** [mock-server/mockserver#1099]
When mockserver containers starts, it fails on the giver error below. I cant initiate it manually: 
```
curl -v -X PUT "http://localhost:1080/mockserver/openapi" -d '{
    "specUrlOrPayload": "file:/config/B2B-SampleService.yaml"
}
```
But container cannot initiate itself at startup.
Environment in container looks like this:
```
MOCKSERVER_PROPERTY_FILE=/config/mockserver.properties
MOCKSERVER_INITIALIZATION_JSON_PATH=/config/initializerJson.json
```
mockserver.properties are empty but initializerJson.json contains this:
```json
{
  "specUrlOrPayload": "file:/config/B2B-SampleService.yaml"
}
```

```shell
2021-11-10 12:26:35 5.11.1 INFO loading JSON initialization file:
mockServer_1  | 
mockServer_1  |   /config/initializerJson.json
mockServer_1  |  
mockServer_1  | 2021-11-10 12:26:36 5.11.1 WARNING exception while loading JSON initialization file, ignoring file 
mockServer_1  | java.lang.IllegalArgumentException: incorrect expectation json format for:
mockServer_1  | 
mockServer_1  |   {
mockServer_1  |     "specUrlOrPayload" : "file:/config/B2B-openapi.json"
mockServer_1  |   }
mockServer_1  | 
mockServer_1  |  schema validation errors:
mockServer_1  | 
mockServer_1  |   12 errors:
mockServer_1  |    - object instance has properties which are not allowed by the schema: ["specUrlOrPayload"]
mockServer_1  |    - oneOf of the following must be specified ["httpResponse", "httpResponseTemplate", "httpResponseObjectCallback", "httpResponseClassCallback", "httpForward", "httpForwardTemplate", "httpForwardObjectCallback", "httpForwardClassCallback", "httpOverrideForwardedRequest", "httpError"] but found 0 without errors
mockServer_1  |    - schema: "/oneOf/0" has error: "object has missing required properties (["httpResponse"])"
mockServer_1  |    - schema: "/oneOf/1" has error: "object has missing required properties (["httpResponseTemplate"])"
mockServer_1  |    - schema: "/oneOf/2" has error: "object has missing required properties (["httpResponseObjectCallback"])"
mockServer_1  |    - schema: "/oneOf/3" has error: "object has missing required properties (["httpResponseClassCallback"])"
mockServer_1  |    - schema: "/oneOf/4" has error: "object has missing required properties (["httpForward"])"
mockServer_1  |    - schema: "/oneOf/5" has error: "object has missing required properties (["httpForwardTemplate"])"
mockServer_1  |    - schema: "/oneOf/6" has error: "object has missing required properties (["httpForwardObjectCallback"])"
mockServer_1  |    - schema: "/oneOf/7" has error: "object has missing required properties (["httpForwardClassCallback"])"
mockServer_1  |    - schema: "/oneOf/8" has error: "object has missing required properties (["httpOverrideForwardedRequest"])"
mockServer_1  |    - schema: "/oneOf/9" has error: "object has missing required properties (["httpError"])"
mockServer_1  |   
mockServer_1  |   See: https://app.swaggerhub.com/apis/jamesdbloom/mock-server-openapi/5.11.x for OpenAPI Specification
mockServer_1  |         at org.mockserver.serialization.ExpectationSerializer.deserializeArray(ExpectationSerializer.java:180)
mockServer_1  |         at org.mockserver.server.initialize.ExpectationInitializerLoader.retrieveExpectationsFromJson(ExpectationInitializerLoader.java:94)
mockServer_1  |         at org.mockserver.server.initialize.ExpectationInitializerLoader.loadExpectations(ExpectationInitializerLoader.java:115)
mockServer_1  |         at org.mockserver.server.initialize.ExpectationInitializerLoader.addExpectationsFromInitializer(ExpectationInitializerLoader.java:37)
mockServer_1  |         at org.mockserver.server.initialize.ExpectationInitializerLoader.<init>(ExpectationInitializerLoader.java:33)
mockServer_1  |         at org.mockserver.mock.HttpState.<init>(HttpState.java:119)
mockServer_1  |         at org.mockserver.lifecycle.LifeCycle.<init>(LifeCycle.java:48)
mockServer_1  |         at org.mockserver.netty.MockServer.<init>(MockServer.java:50)
mockServer_1  |         at org.mockserver.netty.MockServer.<init>(MockServer.java:41)
mockServer_1  |         at org.mockserver.cli.Main.main(Main.java:100)
mockServer_1  | 
mockServer_1  | 2021-11-10 12:26:36 5.11.1 INFO logger level is INFO, change using:
mockServer_1  |  - 'ConfigurationProperties.logLevel(String level)' in Java code,
mockServer_1  |  - '-logLevel' command line argument,
mockServer_1  |  - 'mockserver.logLevel' JVM system property or,
mockServer_1  |  - 'mockserver.logLevel' property value in 'mockserver.properties' 
mockServer_1  | 2021-11-10 12:26:36 5.11.1 INFO 1080 started on port: 1080 
```

**Comment by jamesdbloom** [comment]
OpenAPI expectations were previously not supported for initialisers but that has now been fixed, which is working in the current SNAPSHOT version.  This will be released in the next few weeks so closing this issue.
