### ISSUE TITLE
NoClassDefFoundError: io/netty/handler/codec/compression/Brotli when MockServerClient

### ISSUE THREAD

**Issue by gregohree** [mock-server/mockserver#1173]
### Describe the issue
While using **MockServer 5.11.2**, I setup a test with **MockServerClient** using a **.when()** and **.respond()** method. After the WaitStrategy succeeds, I get an error: `java.lang.RuntimeException: Exception while sending request - java.lang.NoClassDefFoundError: io/netty/handler/codec/compression/Brotli`.

### What you are trying to do
Test using the **MockServerClient** (docker).

### MockServer version
5.11.2

### To reproduce
1. Setup a test using docker, in my case like this:
    ```java
    new MockServerClient(getContainerIpAddress(), getServerPort())
        .when(request()
            .withPath("/foo"))
        .respond(response()
            .withBody("bar"));
    ```
2. Run the test.
3. The test outputs: `java.lang.RuntimeException: Exception while sending request - java.lang.NoClassDefFoundError: io/netty/handler/codec/compression/Brotli`

### Resolution
When I check the  `mvn dependency:tree` of my project, I see this:
```
[INFO] |  +- org.mock-server:mockserver-core:jar:5.11.2:compile
[INFO] |  |  +- com.lmax:disruptor:jar:3.4.2:compile
[INFO] |  |  +- javax.servlet:javax.servlet-api:jar:4.0.1:compile
[INFO] |  |  +- io.netty:netty-buffer:jar:4.1.73.Final:compile
[INFO] |  |  |  \- io.netty:netty-common:jar:4.1.73.Final:compile
[INFO] |  |  +- io.netty:netty-codec:jar:4.1.46.Final:compile
[INFO] |  |  +- io.netty:netty-codec-http:jar:4.1.73.Final:compile
[INFO] |  |  +- io.netty:netty-codec-socks:jar:4.1.73.Final:compile
```
Note this version of netty-codec: `[INFO] |  |  +- io.netty:netty-codec:jar:4.1.46.Final:compile`.
Version **4.1.46.Final** does not have the **Brotli** class. Manually overriding the netty-codec dependency resolved the issue:
```xml
        <dependency>
            <groupId>io.netty</groupId>
            <artifactId>netty-codec</artifactId>
            <version>4.1.73.Final</version>
        </dependency>
```
To resolve, please update the **netty-codec** dependency within **mockserver-core** to **4.1.73.Final**.

### Expected behaviour
No exception thrown.

### MockServer Log
```
11:17:27.528 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
11:17:27.530 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 8
11:17:27.567 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
11:17:27.568 [main] DEBUG io.netty.util.internal.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
11:17:27.612 [main] DEBUG io.netty.util.internal.PlatformDependent0 - -Dio.netty.noUnsafe: false
11:17:27.613 [main] DEBUG io.netty.util.internal.PlatformDependent0 - Java version: 8
11:17:27.616 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
11:17:27.617 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
11:17:27.618 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
11:17:27.619 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
11:17:27.620 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
11:17:27.621 [main] DEBUG io.netty.util.internal.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
11:17:27.621 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
11:17:27.621 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
11:17:27.622 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: C:\Users\grlee\GIT\tech\pimco-java\pimco-java-lib\java-core\core-test\.\target (java.io.tmpdir)
11:17:27.622 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
11:17:27.623 [main] DEBUG io.netty.util.internal.PlatformDependent - Platform: Windows
11:17:27.625 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: 477626368 bytes
11:17:27.626 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
11:17:27.628 [main] DEBUG io.netty.util.internal.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
11:17:27.629 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
11:17:27.631 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
11:17:27.632 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
11:17:27.651 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
11:17:28.313 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.level: simple
11:17:28.314 [main] DEBUG io.netty.util.ResourceLeakDetector - -Dio.netty.leakDetection.targetRecords: 4
11:17:28.316 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numHeapArenas: 4
11:17:28.316 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.numDirectArenas: 4
11:17:28.316 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.pageSize: 8192
11:17:28.316 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxOrder: 11
11:17:28.316 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.chunkSize: 16777216
11:17:28.316 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.smallCacheSize: 256
11:17:28.316 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.normalCacheSize: 64
11:17:28.316 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedBufferCapacity: 32768
11:17:28.316 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimInterval: 8192
11:17:28.316 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.cacheTrimIntervalMillis: 0
11:17:28.316 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.useCacheForAllThreads: true
11:17:28.316 [main] DEBUG io.netty.buffer.PooledByteBufAllocator - -Dio.netty.allocator.maxCachedByteBuffersPerChunk: 1023
11:17:28.379 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.processId: 13908 (auto-detected)
11:17:28.384 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv4Stack: false
11:17:28.384 [main] DEBUG io.netty.util.NetUtil - -Djava.net.preferIPv6Addresses: false
11:17:28.444 [main] DEBUG io.netty.util.NetUtilInitializations - Loopback interface: lo (Software Loopback Interface 1, 127.0.0.1)
11:17:28.446 [main] DEBUG io.netty.util.NetUtil - Failed to get SOMAXCONN from sysctl and file \proc\sys\net\core\somaxconn. Default: 200
11:17:28.494 [main] DEBUG io.netty.channel.DefaultChannelId - -Dio.netty.machineId: 50:6b:8d:ff:fe:13:92:3d (auto-detected)
11:17:28.553 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.allocator.type: pooled
11:17:28.553 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.threadLocalDirectBufferSize: 0
11:17:28.553 [main] DEBUG io.netty.buffer.ByteBufUtil - -Dio.netty.maxThreadLocalCharBufferSize: 16384
11:17:28.664 [MockServer-MockServerClient-eventLoop0] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkAccessible: true
11:17:28.664 [MockServer-MockServerClient-eventLoop0] DEBUG io.netty.buffer.AbstractByteBuf - -Dio.netty.buffer.checkBounds: true
11:17:28.667 [MockServer-MockServerClient-eventLoop0] DEBUG io.netty.util.ResourceLeakDetectorFactory - Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@176fae11
11:17:28.770 [MockServer-MockServerClient-eventLoop0] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.maxCapacityPerThread: 4096
11:17:28.770 [MockServer-MockServerClient-eventLoop0] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.ratio: 8
11:17:28.770 [MockServer-MockServerClient-eventLoop0] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.chunkSize: 32
11:17:28.770 [MockServer-MockServerClient-eventLoop0] DEBUG io.netty.util.Recycler - -Dio.netty.recycler.blocking: false
java.lang.NoClassDefFoundError: io/netty/handler/codec/compression/Brotli
	at io.netty.handler.codec.http.HttpContentDecompressor.newContentDecoder(HttpContentDecompressor.java:70)
	at io.netty.handler.codec.http.HttpContentDecoder.decode(HttpContentDecoder.java:100)
	at io.netty.handler.codec.http.HttpContentDecoder.decode(HttpContentDecoder.java:47)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:308)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:422)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.netty.handler.codec.compression.Brotli
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 28 more
11:17:30.300 [MockServer-MockServerClient-eventLoop0] DEBUG io.netty.channel.DefaultChannelPipeline - Discarded inbound message DefaultLastHttpContent(data: PooledSlicedByteBuf(ridx: 0, widx: 257, cap: 257/257, unwrapped: PooledUnsafeDirectByteBuf(ridx: 390, widx: 390, cap: 2048)), decoderResult: success) that reached at the tail of the pipeline. Please check your pipeline configuration.

java.lang.RuntimeException: Exception while sending request - java.lang.NoClassDefFoundError: io/netty/handler/codec/compression/Brotli

	at org.mockserver.client.NettyHttpClient.sendRequest(NettyHttpClient.java:186)
	at org.mockserver.client.MockServerClient.sendRequest(MockServerClient.java:211)
	at org.mockserver.client.MockServerClient.sendRequest(MockServerClient.java:244)
	at org.mockserver.client.MockServerClient.upsert(MockServerClient.java:1109)
	at org.mockserver.client.ForwardChainExpectation.respond(ForwardChainExpectation.java:50)
	at com.pimco.java.core.testcontainer.MockServerContainerTest.testRepeatableBody(MockServerContainerTest.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.testcontainers.containers.FailureDetectingExternalResource$1.evaluate(FailureDetectingExternalResource.java:30)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: io/netty/handler/codec/compression/Brotli
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1915)
	at org.mockserver.client.NettyHttpClient.sendRequest(NettyHttpClient.java:169)
	... 34 more
Caused by: java.lang.NoClassDefFoundError: io/netty/handler/codec/compression/Brotli
	at io.netty.handler.codec.http.HttpContentDecompressor.newContentDecoder(HttpContentDecompressor.java:70)
	at io.netty.handler.codec.http.HttpContentDecoder.decode(HttpContentDecoder.java:100)
	at io.netty.handler.codec.http.HttpContentDecoder.decode(HttpContentDecoder.java:47)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:308)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:422)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: io.netty.handler.codec.compression.Brotli
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 28 more
```

**Comment by jamesdbloom** [comment]
I suspect this is caused by another dependency in your project downgrading the version of `io.netty:netty-codec` through a transitive dependency.

Running 

```bash
mvn dependency:tree
```

for a pom.xml only containing `mockserver-client-java`, as follows:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.mock-server</groupId>
    <artifactId>test</artifactId>
    <version>5.11.3-SNAPSHOT</version>

    <dependencies>
        <!-- mockserver -->
        <dependency>
            <groupId>${project.groupId}</groupId>
            <artifactId>mockserver-client-java</artifactId>
            <version>5.11.2</version>
        </dependency>
    </dependencies>

</project>
```

outputs the following 

```bash
[INFO] \- org.mock-server:mockserver-client-java:jar:5.11.2:compile
[INFO]    +- org.mock-server:mockserver-core:jar:5.11.2:compile
[INFO]    |  +- com.lmax:disruptor:jar:3.4.2:compile
[INFO]    |  +- javax.servlet:javax.servlet-api:jar:4.0.1:compile
[INFO]    |  +- io.netty:netty-buffer:jar:4.1.53.Final:compile
[INFO]    |  |  \- io.netty:netty-common:jar:4.1.53.Final:compile
[INFO]    |  +- io.netty:netty-codec:jar:4.1.53.Final:compile
[INFO]    |  +- io.netty:netty-codec-http:jar:4.1.53.Final:compile
[INFO]    |  +- io.netty:netty-codec-socks:jar:4.1.53.Final:compile
[INFO]    |  +- io.netty:netty-handler:jar:4.1.53.Final:compile
[INFO]    |  |  \- io.netty:netty-resolver:jar:4.1.53.Final:compile
[INFO]    |  +- io.netty:netty-handler-proxy:jar:4.1.53.Final:compile
[INFO]    |  +- io.netty:netty-transport:jar:4.1.53.Final:compile
[INFO]    |  +- com.jcraft:jzlib:jar:1.1.3:compile
[INFO]    |  +- com.fasterxml.uuid:java-uuid-generator:jar:4.0.1:compile
[INFO]    |  +- org.apache.velocity:velocity-engine-scripting:jar:2.2:compile
[INFO]    |  +- org.apache.velocity:velocity-engine-core:jar:2.2:compile
[INFO]    |  +- com.fasterxml.jackson.core:jackson-core:jar:2.11.3:compile
[INFO]    |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.11.3:compile
[INFO]    |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.11.3:compile
[INFO]    |  +- net.javacrumbs.json-unit:json-unit-core:jar:2.19.0:compile
[INFO]    |  |  \- org.hamcrest:hamcrest-core:jar:2.2:compile
[INFO]    |  |     \- org.hamcrest:hamcrest:jar:2.2:compile
[INFO]    |  +- com.github.java-json-tools:json-schema-validator:jar:2.2.14:compile
[INFO]    |  |  +- com.github.java-json-tools:jackson-coreutils-equivalence:jar:1.0:compile
[INFO]    |  |  |  \- com.github.java-json-tools:jackson-coreutils:jar:2.0:compile
[INFO]    |  |  |     \- com.github.java-json-tools:msg-simple:jar:1.2:compile
[INFO]    |  |  |        \- com.github.java-json-tools:btf:jar:1.3:compile
[INFO]    |  |  +- com.github.java-json-tools:json-schema-core:jar:1.2.14:compile
[INFO]    |  |  |  +- com.github.java-json-tools:uri-template:jar:0.10:compile
[INFO]    |  |  |  \- org.mozilla:rhino:jar:1.7.7.2:compile
[INFO]    |  |  +- com.sun.mail:mailapi:jar:1.6.2:compile
[INFO]    |  |  +- joda-time:joda-time:jar:2.10.5:compile
[INFO]    |  |  +- com.googlecode.libphonenumber:libphonenumber:jar:8.11.1:compile
[INFO]    |  |  \- net.sf.jopt-simple:jopt-simple:jar:5.0.4:compile
[INFO]    |  +- com.jayway.jsonpath:json-path:jar:2.4.0:compile
[INFO]    |  |  \- net.minidev:json-smart:jar:2.3:compile
[INFO]    |  |     \- net.minidev:accessors-smart:jar:1.2:compile
[INFO]    |  |        \- org.ow2.asm:asm:jar:5.0.4:compile
[INFO]    |  +- io.swagger.parser.v3:swagger-parser:jar:2.0.23:compile
[INFO]    |  |  +- io.swagger.parser.v3:swagger-parser-v2-converter:jar:2.0.23:compile
[INFO]    |  |  |  +- io.swagger:swagger-core:jar:1.6.2:compile
[INFO]    |  |  |  |  +- io.swagger:swagger-models:jar:1.6.2:compile
[INFO]    |  |  |  |  |  \- io.swagger:swagger-annotations:jar:1.6.2:compile
[INFO]    |  |  |  |  \- javax.validation:validation-api:jar:1.1.0.Final:compile
[INFO]    |  |  |  +- io.swagger:swagger-parser:jar:1.0.52:compile
[INFO]    |  |  |  |  \- org.slf4j:slf4j-ext:jar:1.7.28:compile
[INFO]    |  |  |  +- io.swagger:swagger-compat-spec-parser:jar:1.0.52:compile
[INFO]    |  |  |  |  \- org.apache.httpcomponents:httpclient:jar:4.5.2:compile
[INFO]    |  |  |  |     +- org.apache.httpcomponents:httpcore:jar:4.4.4:compile
[INFO]    |  |  |  |     \- commons-logging:commons-logging:jar:1.2:compile
[INFO]    |  |  |  +- io.swagger.core.v3:swagger-models:jar:2.1.5:compile
[INFO]    |  |  |  \- io.swagger.parser.v3:swagger-parser-core:jar:2.0.23:compile
[INFO]    |  |  \- io.swagger.parser.v3:swagger-parser-v3:jar:2.0.23:compile
[INFO]    |  |     +- io.swagger.core.v3:swagger-core:jar:2.1.5:compile
[INFO]    |  |     |  +- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.11.1:compile
[INFO]    |  |     |  +- io.swagger.core.v3:swagger-annotations:jar:2.1.5:compile
[INFO]    |  |     |  \- jakarta.validation:jakarta.validation-api:jar:2.0.2:compile
[INFO]    |  |     \- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.11.1:compile
[INFO]    |  |        \- org.yaml:snakeyaml:jar:1.26:compile
[INFO]    |  +- javax.xml.bind:jaxb-api:jar:2.4.0-b180830.0359:compile
[INFO]    |  |  \- javax.activation:javax.activation-api:jar:1.2.0:compile
[INFO]    |  +- org.xmlunit:xmlunit-core:jar:2.8.0:compile
[INFO]    |  |  \- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
[INFO]    |  |     \- jakarta.activation:jakarta.activation-api:jar:1.2.2:compile
[INFO]    |  +- org.xmlunit:xmlunit-placeholders:jar:2.8.0:compile
[INFO]    |  +- commons-io:commons-io:jar:2.8.0:compile
[INFO]    |  +- org.apache.commons:commons-text:jar:1.9:compile
[INFO]    |  \- commons-codec:commons-codec:jar:1.15:compile
[INFO]    +- org.apache.commons:commons-lang3:jar:3.11:compile
[INFO]    +- com.google.guava:guava:jar:30.0-android:compile
[INFO]    |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO]    |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO]    |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO]    |  +- org.checkerframework:checker-compat-qual:jar:2.5.5:compile
[INFO]    |  +- com.google.errorprone:error_prone_annotations:jar:2.3.4:compile
[INFO]    |  \- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO]    \- org.slf4j:slf4j-api:jar:1.7.30:compile
```

There is now a shaded version of both `mockserver-client-java` and `mockserver-netty` which should avoid these sorts of issues, but this is not yet release and is only in the SNAPSHOT version, see here: https://oss.sonatype.org/index.html#nexus-search;gav~org.mock-server~~5.11.3-SNAPSHOT~~
