### ISSUE TITLE
java.security.KeyStoreException after upgrading to Java 11

### ISSUE THREAD

**Issue by yugunchevska** [mock-server/mockserver#1178]
**Describe the issue**
Hello,

I use MockServer as a mock server in my tests. There wasn't any problem, when I used Java 8, but now I have to upgrade to Java 11 and a problem appeared, when I try to create HTTPS mock server with passed self-signed certificate and private key. The following error is seen in the logs:
```java
2022-02-08 09:22:51,745 ERROR [org.m.l.MockServerEventLog                                  ] - exception creating SSL context for serverfailed to initialize the server-side SSL context
javax.net.ssl.SSLException: failed to initialize the server-side SSL context
	at io.netty.handler.ssl.JdkSslServerContext.newSSLContext(JdkSslServerContext.java:288) ~[netty-handler-4.1.50.jar:4.1.50.Final]
	at io.netty.handler.ssl.JdkSslServerContext.<init>(JdkSslServerContext.java:247) ~[netty-handler-4.1.50.jar:4.1.50.Final]
	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:465) ~[netty-handler-4.1.50.jar:4.1.50.Final]
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:571) ~[netty-handler-4.1.50.jar:4.1.50.Final]
	at org.mockserver.socket.tls.NettySslContextFactory.createServerSslContext(NettySslContextFactory.java:141) ~[mockserver-core-5.11.2.jar:5.11.2]
	at org.mockserver.socket.tls.SniHandler.lookup(SniHandler.java:31) ~[mockserver-core-5.11.2.jar:5.11.2]
	at io.netty.handler.ssl.AbstractSniHandler.lookup(AbstractSniHandler.java:126) ~[netty-handler-4.1.50.jar:4.1.50.Final]
	at io.netty.handler.ssl.SslClientHelloHandler.select(SslClientHelloHandler.java:188) ~[netty-handler-4.1.50.jar:4.1.50.Final]
	at io.netty.handler.ssl.SslClientHelloHandler.decode(SslClientHelloHandler.java:149) ~[netty-handler-4.1.50.jar:4.1.50.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501) ~[netty-codec-4.1.50.jar:4.1.50.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440) ~[netty-codec-4.1.50.jar:4.1.50.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:404) ~[netty-codec-4.1.50.jar:4.1.50.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:371) ~[netty-codec-4.1.50.jar:4.1.50.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354) ~[netty-codec-4.1.50.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[netty-transport-4.1.50.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[netty-transport-4.1.50.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241) ~[netty-transport-4.1.50.jar:4.1.50.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405) ~[netty-transport-4.1.50.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262) ~[netty-transport-4.1.50.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248) ~[netty-transport-4.1.50.jar:4.1.50.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901) ~[netty-transport-4.1.50.jar:4.1.50.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818) ~[netty-transport-4.1.50.jar:4.1.50.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164) ~[netty-common-4.1.50.jar:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472) ~[netty-common-4.1.50.jar:4.1.50.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497) ~[netty-transport-4.1.50.jar:4.1.50.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[netty-common-4.1.50.jar:4.1.50.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.50.jar:4.1.50.Final]
	at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.security.KeyStoreException: Key protection algorithm not found: java.security.KeyStoreException: Certificate chain is not valid
	at sun.security.pkcs12.PKCS12KeyStore.setKeyEntry(PKCS12KeyStore.java:688) ~[?:?]
	at sun.security.pkcs12.PKCS12KeyStore.engineSetKeyEntry(PKCS12KeyStore.java:585) ~[?:?]
	at sun.security.util.KeyStoreDelegator.engineSetKeyEntry(KeyStoreDelegator.java:111) ~[?:?]
	at java.security.KeyStore.setKeyEntry(KeyStore.java:1174) ~[?:?]
	at io.netty.handler.ssl.SslContext.buildKeyStore(SslContext.java:1102) ~[netty-handler-4.1.50.jar:4.1.50.Final]
	at io.netty.handler.ssl.SslContext.buildKeyManagerFactory(SslContext.java:1274) ~[netty-handler-4.1.50.jar:4.1.50.Final]
	at io.netty.handler.ssl.SslContext.buildKeyManagerFactory(SslContext.java:1263) ~[netty-handler-4.1.50.jar:4.1.50.Final]
	at io.netty.handler.ssl.JdkSslServerContext.newSSLContext(JdkSslServerContext.java:266) ~[netty-handler-4.1.50.jar:4.1.50.Final]
	... 27 more
Caused by: java.security.KeyStoreException: Certificate chain is not valid
	at sun.security.pkcs12.PKCS12KeyStore.setKeyEntry(PKCS12KeyStore.java:635) ~[?:?]
	at sun.security.pkcs12.PKCS12KeyStore.engineSetKeyEntry(PKCS12KeyStore.java:585) ~[?:?]
	at sun.security.util.KeyStoreDelegator.engineSetKeyEntry(KeyStoreDelegator.java:111) ~[?:?]
	at java.security.KeyStore.setKeyEntry(KeyStore.java:1174) ~[?:?]
	at io.netty.handler.ssl.SslContext.buildKeyStore(SslContext.java:1102) ~[netty-handler-4.1.50.jar:4.1.50.Final]
	at io.netty.handler.ssl.SslContext.buildKeyManagerFactory(SslContext.java:1274) ~[netty-handler-4.1.50.jar:4.1.50.Final]
	at io.netty.handler.ssl.SslContext.buildKeyManagerFactory(SslContext.java:1263) ~[netty-handler-4.1.50.jar:4.1.50.Final]
	at io.netty.handler.ssl.JdkSslServerContext.newSSLContext(JdkSslServerContext.java:266) ~[netty-handler-4.1.50.jar:4.1.50.Final]
	... 27 more
```

I created my own server using just Java 11 with the same self-signed certificate and I was able to send a request to it without a problem.

**What you are trying to do**
I want to verify that a request is received successfully, when it's sent to the HTTPS server with a self-signed certificate.

**MockServer version**
MockServer version is 5.10.0, even though I upgraded it to 5.11.0 and the same exception was thrown.
jUnit version is 4
Java version is 11 (with Java 8 I don't have any problems)
Gradle version is 7

**To Reproduce**
Steps to reproduce the issue:

1. How you are running MockServer (i.e maven plugin, docker, etc) - I'm using MockServer programmatically via the Java API in an @Before and @After methods 
2. Code you used to create expectations 
The self-signed certificate and private key are created using openssl and the code is:

```java
   ClientAndServer mockServer;
 
    @BeforeClass
    public static void prepareEnvironment() {
        // remember the original certificate and private key to be able to revert them
        originalCertificatePath = MockServerUtils.getMockServerCertificatePath();
        originalPrivateKeyPath = MockServerUtils.getMockServerPrivateKeyPath();

        ConfigurationProperties.x509CertificatePath(certificatePath);
        ConfigurationProperties.privateKeyPath(privateKeyPath);

        mockServer = ClientAndServer.startClientAndServer();
    }

    @AfterClass
    public static void cleanEnvironment() {
        Stop.stopQuietly(mockServer);

        // reset certificate and private key
        ConfigurationProperties.x509CertificatePath(originalCertificatePath);
        ConfigurationProperties.privateKeyPath(originalPrivateKeyPath);
    }

    @Test
    public void test() {
        mockServer.reset();
        
        mockServer
                .when(getExpectedRequest(path, method, client, licenseKey))
                .respond(getResponseWithStatusCode(responseCode));

        ...

        mockServer.verify(getExpectedRequest(path, method, client, licenseKey),
                VerificationTimes.exactly(1));
    }
```

3. What error you saw - when a request is sent to the mock server, the exception above is thrown. After that the test fails, when it tries to verify, because a request wasn't send at all. 

**Expected behaviour**
I expected I won't have problems when I upgraded to Java 11, but the exception is thrown and my tests are failing. 

**MockServer Log**
Log output, as INFO level (or lower)
```bash
2022-02-08 09:22:44,350 INFO  [org.m.l.MockServerEventLog                                  ] - 54049 started on port: 54049
2022-02-08 09:22:44,528 INFO  [org.m.l.MockServerEventLog                                  ] - 54049 resetting all expectations and request logs
2022-02-08 09:22:45,079 INFO  [org.m.l.MockServerEventLog                                  ] - 54049 creating expectation:

  {
    "id" : "3c4ed28f-f70b-49e1-a788-462f90d14500",
    "priority" : 0,
    "httpRequest" : {
      "method" : "POST",
      "path" : "/api/measurements",
      "headers" : {
        "Content-Type" : [ "application/x-ndjson" ],
        "X-SAG-Client" : [ "1" ],
        "X-SAG-License-Key" : [ "12345678" ]
      }
    },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpResponse" : {
      "statusCode" : 200
    }
  }

 with id:

  3c4ed28f-f70b-49e1-a788-462f90d14500
2022-02-08 09:22:51,698 ERROR [org.m.l.MockServerEventLog                                  ] - exception creating SSL context for serverfailed to initialize the server-side SSL context (the whole exception is above)
2022-02-08 09:22:54,548 INFO  [org.m.l.MockServerEventLog                                  ] - 54049 verifying requests that match:

  {
    "httpRequest" : {
      "method" : "POST",
      "path" : "/api/measurements",
      "headers" : {
        "Content-Type" : [ "application/x-ndjson" ],
        "X-SAG-Client" : [ "1" ],
        "X-SAG-License-Key" : [ "12345678" ]
      }
    },
    "times" : {
      "atLeast" : 1,
      "atMost" : 1
    }
  }

2022-02-08 09:22:54,571 INFO  [org.m.l.MockServerEventLog                                  ] - request not found exactly once, expected:

  {
    "method" : "POST",
    "path" : "/api/measurements",
    "headers" : {
      "Content-Type" : [ "application/x-ndjson" ],
      "X-SAG-Client" : [ "1" ],
      "X-SAG-License-Key" : [ "12345678" ]
    }
  }

 but was:

  []
```

**Comment by jamesdbloom** [comment]
This can be fixed by using Bouncy Castle as described here: https://mock-server.com/mock_server/HTTPS_TLS.html#button_configuration_use_bouncy_castle 

I may need to make this the default behaviour due to the issue you raised which I was aware of or provide a version of MockServer that uses modules.  The problem is that the most common version of Java in use is still 8 which doesn't support modules.

**Comment by yugunchevska** [comment]
I added the dependencies to Bouncy Castle and used `ConfigurationProperties.useBouncyCastleForKeyAndCertificateGeneration(true);` just above `ConfigurationProperties.x509CertificatePath(certificatePath);
 ConfigurationProperties.privateKeyPath(privateKeyPath);` but the same exception is thrown. From the logs I can see:
`2022-02-08 17:55:53,825 INFO  [org.m.c.MockServerClient                                    ] - using Bouncy Castle for X.509 Certificate and Private Key generation
2022-02-08 17:55:53,987 INFO  [org.m.l.MockServerEventLog                                  ] - using Bouncy Castle for X.509 Certificate and Private Key generation`
 Am I missing something?

**Comment by jamesdbloom** [comment]
Can you please provide me a reproducible example then I can help debug the issue or fix the bug if there is one.

**Comment by jamesdbloom** [comment]
Actually now I look at this in more detail it looks like the certificate chain you are using is not a valid supported format for Java 11 or BouncyCastle.  I'm surprised it worked for Java 8.  

I have some notes for generating a private key and certificate chain that work with Java 8 to 17 and Bouncy Castle here: https://github.com/mock-server/mockserver/blob/master/mockserver-netty/src/test/resources/org/mockserver/netty/integration/tls/generate_custom_certifcates.md

If you follow these notes you should be able to create a what you need in a valid format and you don't need to use Bouncy Castle until you use Java 16+

**Comment by yugunchevska** [comment]
I have a requirement to use a self-signed certificate. I checked and it's algorithm is also RSA 2048, so I'm not sure if the problem is in the certificate. I managed to generate new key pair in the way, described below, and the issue appeared again:

The self-signed certificate can be generated this way: 
`openssl req -x509 -sha256 -nodes -days 365 -newkey rsa:2048 -keyout privateKey.key -out certificate.crt`
then to convert the certificate to pem:
`openssl x509 -in certificate.crt -out certificate.crt.pem -outform PEM`
and to convert the private key to pem:
`openssl rsa -in privateKey.key -out privateKey.pem -outform PEM`

and then to convert it in PKCS#8:
openssl pkcs8 -topk8 -inform PEM -in privateKey.pem -out privateKey-pkcs8.pem -nocrypt

The way I reproduced the problem is with this code:

```
package com.company.name;

import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.URL;

import org.apache.http.HttpHeaders;
import org.apache.http.client.ClientProtocolException;
import org.apache.http.client.HttpClient;
import org.apache.http.client.methods.HttpPost;
import org.apache.http.entity.StringEntity;
import org.apache.http.impl.client.HttpClients;
import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import org.mockserver.configuration.ConfigurationProperties;
import org.mockserver.integration.ClientAndServer;
import org.mockserver.model.HttpRequest;
import org.mockserver.model.HttpResponse;
import org.mockserver.stop.Stop;
import org.mockserver.verify.VerificationTimes;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class MockServerTest {
	private static final Logger LOG = LoggerFactory.getLogger(MockServerTest.class);
	
	private static ClientAndServer mockServer;
    private static String originalCertificatePath;
    private static String originalPrivateKeyPath;
	
	@BeforeClass
	public static void setup() {
        //remember the original certificate and private key to be able to revert them
        originalCertificatePath = ConfigurationProperties.x509CertificatePath();
        originalPrivateKeyPath = ConfigurationProperties.privateKeyPath();
        
        ConfigurationProperties.useBouncyCastleForKeyAndCertificateGeneration(true);
        
        ConfigurationProperties.x509CertificatePath("certificate.pem");
        LOG.info("Certificate path changed to " + "certificate.pem");

        ConfigurationProperties.privateKeyPath("privateKey-pkcs8.pem");
        LOG.info("Private key path changed to " + "privateKey-pkcs8.pem");
        
        mockServer = ClientAndServer.startClientAndServer();
	}
	
    @AfterClass
    public static void cleanEnvironment() {
    	Stop.stopQuietly(mockServer);
    	
        //reset certificate and private key
    	ConfigurationProperties.x509CertificatePath(originalCertificatePath);
        LOG.info("Certificate path changed to " + originalCertificatePath);

        ConfigurationProperties.privateKeyPath(originalPrivateKeyPath);
        LOG.info("Private key path changed to " + originalPrivateKeyPath);
    }

    @Test
    public void test() throws ClientProtocolException, IOException {
    	String endpoint = new URL("https", "localhost", mockServer.getLocalPort(),
                MockServerUtils.PATH_REPORT_MEASUREMENTS).toString();
    	
    	configureMockServerRequestExpectancy(HttpURLConnection.HTTP_OK);
    	
    	// send a request 
    	HttpPost httppost = new HttpPost(endpoint + "/api/measurements");
        httppost.setHeader(HttpHeaders.CONTENT_TYPE, "application/x-ndjson");
        httppost.setEntity(new StringEntity("hi"));
        org.apache.http.HttpResponse response = execute(httppost);
        LOG.info("The post request is executed - " + response.getStatusLine().getStatusCode());
    	
    	verifyRequestReceived(1);
    }
    
    private void configureMockServerRequestExpectancy(int responseCode) {
        mockServer
                .when(HttpRequest.request()
                        .withMethod("POST")
                        .withPath("/api/measurements"))
                .respond(getResponseWithStatusCode(responseCode));
    }
    
    private void verifyRequestReceived(int verificationTimes) {
        mockServer.verify(HttpRequest.request()
                			.withMethod("POST")
                			.withPath("/api/measurements"),
                VerificationTimes.exactly(verificationTimes));
    }
    
    private static HttpResponse getResponseWithStatusCode(int statusCode) {
        return HttpResponse.response().withStatusCode(statusCode);
    }
    
    private static org.apache.http.HttpResponse execute(HttpPost postRequest) throws ClientProtocolException, IOException {
        HttpClient httpclient = HttpClients.createDefault();
        return httpclient.execute(postRequest);
    }
}

```

**Comment by pranavbhandari24** [comment]
+1, facing the same issue.  I am providing the certificate and key files as `certificate.crt` and `privatekey.key`. They are PEM format.

I get the following stacktrace: 
```
2022-04-18 14:57:38 ERROR MockServerEventLog:102 - exception creating SSL context for serverfailed to set certificate and key
javax.net.ssl.SSLException: failed to set certificate and key
	at io.netty.handler.ssl.ReferenceCountedOpenSslServerContext.newSessionContext(ReferenceCountedOpenSslServerContext.java:138)
	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:353)
	at io.netty.handler.ssl.OpenSslServerContext.<init>(OpenSslServerContext.java:334)
	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:471)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:571)
	at org.mockserver.socket.tls.NettySslContextFactory.createServerSslContext(NettySslContextFactory.java:142)
	at org.mockserver.socket.tls.SniHandler.lookup(SniHandler.java:31)
	at io.netty.handler.ssl.AbstractSniHandler.lookup(AbstractSniHandler.java:126)
	at io.netty.handler.ssl.SslClientHelloHandler.select(SslClientHelloHandler.java:188)
	at io.netty.handler.ssl.SslClientHelloHandler.decode(SslClientHelloHandler.java:149)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:404)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:371)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.security.KeyStoreException: Key protection algorithm not found: java.security.KeyStoreException: Certificate chain is not valid
	at java.base/sun.security.pkcs12.PKCS12KeyStore.setKeyEntry(PKCS12KeyStore.java:688)
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineSetKeyEntry(PKCS12KeyStore.java:585)
	at java.base/sun.security.util.KeyStoreDelegator.engineSetKeyEntry(KeyStoreDelegator.java:111)
	at java.base/java.security.KeyStore.setKeyEntry(KeyStore.java:1174)
	at io.netty.handler.ssl.SslContext.buildKeyStore(SslContext.java:1102)
	at io.netty.handler.ssl.ReferenceCountedOpenSslServerContext.newSessionContext(ReferenceCountedOpenSslServerContext.java:123)
	... 28 more
Caused by: java.security.KeyStoreException: Certificate chain is not valid
	at java.base/sun.security.pkcs12.PKCS12KeyStore.setKeyEntry(PKCS12KeyStore.java:635)
	... 33 more
```

It looks like we get the error `Certificate chain is not valid` because the files are expected to be in PKCS12 format? I'm not sure.

The certificate and key files are valid and this worked in JAVA 8.
