### ISSUE TITLE
NullPointerException on 5.12.0

### ISSUE THREAD

**Issue by flozano** [mock-server/mockserver#1196]
```
[2022-02-23T19:05:45.405Z] [ERROR] [MockServer-EventLog134] org.mockserver.log.MockServerEventLog 13848 exception encoding response

  {
    "statusCode" : 200,
    "headers" : {
      "connection" : [ "keep-alive" ],
      "Content-Type" : [ "image/png" ]
    },
    "body" : "\u0000\u0001\u0002\u0003\u0004\u0005\u0006\u0007\b\t"
  }
 java.lang.NullPointerException: null
	at java.base/java.lang.String.getBytes(String.java:963)
	at org.mockserver.codec.BodyDecoderEncoder.bodyToBytes(BodyDecoderEncoder.java:63)
	at org.mockserver.codec.BodyDecoderEncoder.bodyToByteBuf(BodyDecoderEncoder.java:16)
	at org.mockserver.mappers.MockServerHttpResponseToFullHttpResponse.getBody(MockServerHttpResponseToFullHttpResponse.java:91)
	at org.mockserver.mappers.MockServerHttpResponseToFullHttpResponse.mapMockServerResponseToNettyResponse(MockServerHttpResponseToFullHttpResponse.java:59)
	at org.mockserver.codec.MockServerHttpToNettyHttpResponseEncoder.encode(MockServerHttpToNettyHttpResponseEncoder.java:24)
	at org.mockserver.codec.MockServerHttpToNettyHttpResponseEncoder.encode(MockServerHttpToNettyHttpResponseEncoder.java:14)
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:89)
	at io.netty.channel.CombinedChannelDuplexHandler.write(CombinedChannelDuplexHandler.java:346)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:717)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:764)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:790)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:758)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:808)
	at org.mockserver.netty.responsewriter.NettyResponseWriter.writeAndCloseSocket(NettyResponseWriter.java:51)
	at org.mockserver.netty.responsewriter.NettyResponseWriter.sendResponse(NettyResponseWriter.java:38)
	at org.mockserver.responsewriter.ResponseWriter.writeResponse(ResponseWriter.java:62)
	at org.mockserver.mock.action.http.HttpActionHandler.lambda$writeResponseActionResponse$21(HttpActionHandler.java:370)
	at org.mockserver.scheduler.Scheduler.run(Scheduler.java:87)
	at org.mockserver.scheduler.Scheduler.schedule(Scheduler.java:113)
	at org.mockserver.mock.action.http.HttpActionHandler.writeResponseActionResponse(HttpActionHandler.java:357)
	at org.mockserver.mock.action.http.HttpActionHandler.lambda$null$1(HttpActionHandler.java:104)
	at org.mockserver.mock.action.http.HttpActionHandler.handleAnyException(HttpActionHandler.java:339)
	at org.mockserver.mock.action.http.HttpActionHandler.lambda$processAction$2(HttpActionHandler.java:102)
	at org.mockserver.scheduler.Scheduler.run(Scheduler.java:87)
	at org.mockserver.scheduler.Scheduler.schedule(Scheduler.java:113)
	at org.mockserver.mock.action.http.HttpActionHandler.processAction(HttpActionHandler.java:102)
	at org.mockserver.netty.HttpRequestHandler.channelRead0(HttpRequestHandler.java:166)
	at org.mockserver.netty.HttpRequestHandler.channelRead0(HttpRequestHandler.java:50)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.mockserver.dashboard.DashboardWebSocketHandler.channelRead(DashboardWebSocketHandler.java:137)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.mockserver.netty.websocketregistry.CallbackWebSocketServerHandler.channelRead(CallbackWebSocketServerHandler.java:57)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at org.mockserver.netty.unification.PortUnificationHandler.switchToHttp(PortUnificationHandler.java:260)
	at org.mockserver.netty.unification.PortUnificationHandler.decode(PortUnificationHandler.java:138)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:829)
```
The use was not correct at all:
```java
		byte[] response = new byte[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
		String type = "image/png";

		mockServer.when(request().withMethod("POST").withPath("/run").withBody(request.toString())).respond(response()
				.withStatusCode(200).withHeader(new Header("Content-Type", type)).withBody(new String(response)));
```
(note the new `String(response)`)

 but it shouldn't generate such exception and return nothing at all. When changing to `withBody(response)`, the server works as expected and no exception is logged.

**Comment by jamesdbloom** [comment]
I have fixed this NullPointerException and will push it shortly (once the full test set has completed) but it seems to be caused by an invalid combination of a StringBody and a non string Content-Type header.  I suspect such a combination won't result in a correctly formatted response.

**Comment by jamesdbloom** [comment]
If you change you code as follow (i.e. remove the wrapping string) I suspect your'll get better results:

```java
byte[] response = new byte[] { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9 };
String type = "image/png";

mockServer
    .when(
        request()
            .withMethod("POST")
            .withPath("/run")
            .withBody(request.toString())
    )
    .respond(
        response()
            .withStatusCode(200)
            .withHeader(new Header("Content-Type", type))
            .withBody(response)
    );
```
