### ISSUE TITLE
mockserver 5.12.0 has NoSuchFieldError: ACCEPT_CASE_INSENSITIVE_VALUES

### ISSUE THREAD

**Issue by vbhosle** [mock-server/mockserver#1227]
There is some conflict with jackson libraries that is causing NoSuchFieldError: ACCEPT_CASE_INSENSITIVE_VALUES while parsing initializer json.  It forces you to use latest jackson libraries, which we don't want to. And still want to use the multiple json file support. 

**Impact of this warning is that, it fails to match on queryStringParameters.**

Stack trace: 
ACCEPT_CASE_INSENSITIVE_VALUES java.lang.NoSuchFieldError: ACCEPT_CASE_INSENSITIVE_VALUES
	at org.mockserver.serialization.ObjectMapperFactory.lambda$buildObjectMapperWithoutRemovingEmptyValues$7(ObjectMapperFactory.java:105)
	at org.mockserver.exception.ExceptionHandling.swallowThrowable(ExceptionHandling.java:37)
	at org.mockserver.serialization.ObjectMapperFactory.buildObjectMapperWithoutRemovingEmptyValues(ObjectMapperFactory.java:105)
	at org.mockserver.serialization.ObjectMapperFactory.buildObjectMapperWithOnlyConfigurationDefaults(ObjectMapperFactory.java:137)
	at org.mockserver.serialization.ObjectMapperFactory.buildObjectMapperWithDeserializerAndSerializers(ObjectMapperFactory.java:148)
	at org.mockserver.serialization.ObjectMapperFactory.createObjectMapper(ObjectMapperFactory.java:51)
	at org.mockserver.log.model.LogEntry.<clinit>(LogEntry.java:33)
	at org.mockserver.exception.ExceptionHandling.swallowThrowable(ExceptionHandling.java:40)
	at org.mockserver.serialization.ObjectMapperFactory.buildObjectMapperWithoutRemovingEmptyValues(ObjectMapperFactory.java:105)
	at org.mockserver.serialization.ObjectMapperFactory.buildObjectMapperWithOnlyConfigurationDefaults(ObjectMapperFactory.java:137)
	at org.mockserver.serialization.ObjectMapperFactory.buildObjectMapperWithDeserializerAndSerializers(ObjectMapperFactory.java:148)
	at org.mockserver.serialization.ObjectMapperFactory.<clinit>(ObjectMapperFactory.java:45)
	at org.mockserver.serialization.RequestDefinitionSerializer.<init>(RequestDefinitionSerializer.java:37)
	at org.mockserver.client.MockServerClient.<init>(MockServerClient.java:72)
	at org.mockserver.integration.ClientAndServer.<init>(ClientAndServer.java:34)
	at org.mockserver.integration.ClientAndServer.startClientAndServer(ClientAndServer.java:57)

**Comment by jamesdbloom** [comment]
I'm not sure your conclusion is correct.  Please re-run your code with TRACE level logging on.  MockServer swallows these errors so I suspect the reason your matching is failing is unrelated.

**Comment by vbhosle** [comment]
@jamesdbloom It says
exception decoding request

  HttpObjectAggregator$AggregatedFullHttpRequest(decodeResult: success, version: HTTP/1.1, content: CompositeByteBuf(freed, components=0))
  GET /someresource/list?resourceID=abcde-12345&startDate=2020-10-31T00%3A00%3A00%2B00&endDate=2020-12-31T00%3A00%3A00%2B00&limit=20&offset=0 HTTP/1.1
  Authorization: Bearer test-auth-token
  Host: localhost:33000
  Connection: Keep-Alive
  Accept-Encoding: gzip
  User-Agent: okhttp/3.12.1
  content-length: 0
 java.lang.NoSuchMethodError: io.netty.handler.codec.http.QueryStringDecoder.<init>(Ljava/lang/String;Ljava/nio/charset/Charset;ZIZ)V
	at org.mockserver.codec.ExpandedParameterDecoder.retrieveQueryParameters(ExpandedParameterDecoder.java:62)
	at org.mockserver.mappers.FullHttpRequestToMockServerHttpRequest.setQueryString(FullHttpRequestToMockServerHttpRequest.java:92)
	at org.mockserver.mappers.FullHttpRequestToMockServerHttpRequest.mapFullHttpRequestToMockServerRequest(FullHttpRequestToMockServerHttpRequest.java:57)
	at org.mockserver.codec.NettyHttpToMockServerHttpRequestDecoder.decode(NettyHttpToMockServerHttpRequestDecoder.java:24)
	at org.mockserver.codec.NettyHttpToMockServerHttpRequestDecoder.decode(NettyHttpToMockServerHttpRequestDecoder.java:14)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at org.mockserver.dashboard.DashboardWebSocketHandler.channelRead(DashboardWebSocketHandler.java:137)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at org.mockserver.netty.websocketregistry.CallbackWebSocketServerHandler.channelRead(CallbackWebSocketServerHandler.java:57)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at org.mockserver.netty.unification.PortUnificationHandler.switchToHttp(PortUnificationHandler.java:260)
	at org.mockserver.netty.unification.PortUnificationHandler.decode(PortUnificationHandler.java:138)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1421)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:930)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:697)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:632)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:549)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:511)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)

**Comment by vbhosle** [comment]
In received request log, it doesn't print the query params as it fails to decode it
2022-03-16 15:32:17,497 29109 [MockServer-EventLog0] INFO  [o.m.l.MockServerEventLog] {{clusterName,default}{appResourceId,viraj.b@dev}} - received request:

  {
    "method" : "GET",
    "path" : "/someresource/list"
  }
  
  It works fine with 5.11.2 mockserver-netty

**Comment by vbhosle** [comment]
Got it. My pom has netty-codec-http and netty-codec-http2 both dependencies. Excluded netty-codec-http from mockserver-netty. Now it's working. Thanks!
