### ISSUE TITLE
Connection timed out when expectation matches request with json schema

### ISSUE THREAD

**Issue by mmaier2** [mock-server/mockserver#1231]
**Describe the issue**
Connection timed out when expectation matches request with json schema

**What you are trying to do**
Using the expectation from examples:
```
  {
    "httpRequest" : {
      "path" : "/some/path/{cartId}/{maxItemCount}",
      "pathParameters" : {
        "cartId" : [ {
          "schema" : {
            "type" : "string",
            "pattern" : "^[A-Z0-9-]+$"
          }
        } ],
        "maxItemCount" : [ {
          "schema" : {
            "type" : "integer"
          }
        } ]
      }
    },
    "httpResponse" : {
      "body" : "some_response_body"
    }
  }
```

**MockServer version**
5.13.0 (mockserver-netty-5.13.0-shaded.jar)

**To Reproduce**

Put expectation via expectation rest api, or import via init json file.

1. How you are running MockServer: Does not make any difference, currently just the jar
2. Code you used to create expectations: rest api or json init file
3. What error you saw: see the logs below

**Expected behaviour**
Mock-server is handling the expectation. Unfortunately, there's a corporate proxy I've to use. Is there any way to specify a proxy or offline validation for the json validation library?

**MockServer Log**
Log output, as INFO level (or lower)
```
com.networknt.schema.JsonSchemaException: java.net.ConnectException: Connection timed out: connect
        at com.networknt.schema.JsonSchemaFactory.getSchema(JsonSchemaFactory.java:384)
        at com.networknt.schema.RefValidator.getRefSchema(RefValidator.java:82)
        at com.networknt.schema.RefValidator.<init>(RefValidator.java:45)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at com.networknt.schema.ValidatorTypeCode.newValidator(ValidatorTypeCode.java:134)
        at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:411)
        at com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:57)
        at com.networknt.schema.JsonSchema.read(JsonSchema.java:204)
        at com.networknt.schema.JsonSchema.getValidators(JsonSchema.java:442)
        at com.networknt.schema.JsonSchema.validate(JsonSchema.java:259)
        at com.networknt.schema.PropertiesValidator.validate(PropertiesValidator.java:68)
        at com.networknt.schema.JsonSchema.validate(JsonSchema.java:261)
        at com.networknt.schema.OneOfValidator.validate(OneOfValidator.java:160)
        at com.networknt.schema.JsonSchema.validate(JsonSchema.java:261)
        at com.networknt.schema.JsonSchemaRef.validate(JsonSchemaRef.java:38)
        at com.networknt.schema.RefValidator.validate(RefValidator.java:139)
        at com.networknt.schema.JsonSchema.validate(JsonSchema.java:261)
        at com.networknt.schema.ItemsValidator.doValidate(ItemsValidator.java:100)
        at com.networknt.schema.ItemsValidator.validate(ItemsValidator.java:87)
        at com.networknt.schema.JsonSchema.validate(JsonSchema.java:261)
        at com.networknt.schema.OneOfValidator.validate(OneOfValidator.java:160)
        at com.networknt.schema.JsonSchema.validate(JsonSchema.java:261)
        at com.networknt.schema.PatternPropertiesValidator.validate(PatternPropertiesValidator.java:61)
        at com.networknt.schema.JsonSchema.validate(JsonSchema.java:261)
        at com.networknt.schema.OneOfValidator.validate(OneOfValidator.java:160)
        at com.networknt.schema.JsonSchema.validate(JsonSchema.java:261)
        at com.networknt.schema.JsonSchemaRef.validate(JsonSchemaRef.java:38)
        at com.networknt.schema.RefValidator.validate(RefValidator.java:139)
        at com.networknt.schema.JsonSchema.validate(JsonSchema.java:261)
        at com.networknt.schema.PropertiesValidator.validate(PropertiesValidator.java:68)
        at com.networknt.schema.JsonSchema.validate(JsonSchema.java:261)
        at com.networknt.schema.JsonSchemaRef.validate(JsonSchemaRef.java:38)
        at com.networknt.schema.RefValidator.validate(RefValidator.java:139)
        at com.networknt.schema.JsonSchema.validate(JsonSchema.java:261)
        at com.networknt.schema.AnyOfValidator.validate(AnyOfValidator.java:75)
        at com.networknt.schema.JsonSchema.validate(JsonSchema.java:261)
        at com.networknt.schema.JsonSchemaRef.validate(JsonSchemaRef.java:38)
        at com.networknt.schema.RefValidator.validate(RefValidator.java:139)
        at com.networknt.schema.JsonSchema.validate(JsonSchema.java:261)
        at com.networknt.schema.PropertiesValidator.validate(PropertiesValidator.java:68)
        at com.networknt.schema.JsonSchema.validate(JsonSchema.java:261)
        at com.networknt.schema.BaseJsonValidator.validate(BaseJsonValidator.java:114)
        at org.mockserver.validator.jsonschema.JsonSchemaValidator.isValid(JsonSchemaValidator.java:152)
        at org.mockserver.validator.jsonschema.JsonSchemaValidator.isValid(JsonSchemaValidator.java:145)
        at org.mockserver.serialization.ExpectationSerializer.deserialize(ExpectationSerializer.java:119)
        at org.mockserver.serialization.ExpectationSerializer.deserializeArray(ExpectationSerializer.java:183)
        at org.mockserver.mock.HttpState.handle(HttpState.java:589)
        at org.mockserver.netty.HttpRequestHandler.channelRead0(HttpRequestHandler.java:96)
        at org.mockserver.netty.HttpRequestHandler.channelRead0(HttpRequestHandler.java:49)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at org.mockserver.dashboard.DashboardWebSocketHandler.channelRead(DashboardWebSocketHandler.java:137)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at org.mockserver.netty.websocketregistry.CallbackWebSocketServerHandler.channelRead(CallbackWebSocketServerHandler.java:57)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at org.mockserver.netty.unification.PortUnificationHandler.switchToHttp(PortUnificationHandler.java:261)
        at org.mockserver.netty.unification.PortUnificationHandler.decode(PortUnificationHandler.java:139)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1372)
        at io.netty.handler.ssl.SslHandler.decodeNonJdkCompatible(SslHandler.java:1246)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1286)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.ConnectException: Connection timed out: connect
        at java.base/java.net.PlainSocketImpl.connect0(Native Method)
        at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:101)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/java.net.Socket.connect(Socket.java:558)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at com.networknt.schema.uri.URLFetcher.openConnectionCheckRedirects(URLFetcher.java:57)
        at com.networknt.schema.uri.URLFetcher.fetch(URLFetcher.java:43)
        at com.networknt.schema.uri.URISchemeFetcher.fetch(URISchemeFetcher.java:50)
        at com.networknt.schema.JsonSchemaFactory.getSchema(JsonSchemaFactory.java:360)
        ... 113 more
```

Thanx
Markus

**Comment by jamesdbloom** [comment]
Can you please provide the schema so I can see what is causing the remote request to be made

**Comment by mmaier2** [comment]
> Can you please provide the openapi schema so I can see what is causing the remote request to be made and the way the expectation or openapi was added to MockServer.

Hi James,

There is no openapi spec involved. The problem occurs - I guess - when the mockserver wants to validate the expectation itself.

I've just started the mockserver via java -jar... and I wanted to do the rest api example of https://mock-server.com/mock_server/creating_expectations.html#button_match_request_by_path_parameter_json_schema_value

In my case if I run the curl in the example to put the expectation into the mockserver I'm getting the error. So I guess the used json schema validation lib to validate the expectation wants to connect to some resource. If you're not behind any proxies you might not face this issue.

Thanx 
Markus

**Comment by mmaier2** [comment]
Maybe any hints what I could do?
Thanks
Markus
