### ISSUE TITLE
`NoSuchMethodError` when starting mockserver with version >=5.13.1

### ISSUE THREAD

**Issue by martinfrancois** [mock-server/mockserver#1273]
**Describe the issue**
When I'm trying to start the mockserver with version 5.13.1 or 5.13.2, it results in a `NoSuchMethodError`, which does NOT appear with 5.13.0:
```
Exception in thread "main" java.lang.NoSuchMethodError: org.mockserver.mock.action.http.HttpActionHandler.<init>(Lorg/mockserver/configuration/Configuration;Lio/netty/channel/EventLoopGroup;Lorg/mockserver/mock/HttpState;Ljava/util/List;Lorg/mockserver/socket/tls/NettySslContextFactory;)V
	at org.mockserver.netty.MockServer.createServerBootstrap(MockServer.java:189)
	at org.mockserver.netty.MockServer.<init>(MockServer.java:78)
	at org.mockserver.netty.MockServer.<init>(MockServer.java:57)
	at org.mockserver.integration.ClientAndServer.<init>(ClientAndServer.java:58)
	at org.mockserver.integration.ClientAndServer.<init>(ClientAndServer.java:52)
	at MockServer.start(MockServer.java:10)
	at MockServer.main(MockServer.java:6)
```

**What you are trying to do**
When running a main method that does `ClientAndServer client = new ClientAndServer(1080);`, it results in the aforementioned error.

A similar error appears when trying to start junit tests when using the `MockServerExtension`, I assume it's the same kind of issue, but wanted to mention it anyways in case it's a different issue.

**MockServer version**
5.13.1 and 5.13.2

**To Reproduce**
Steps to reproduce the issue:

1. Clone the minimal reproducible example here: https://github.com/martinfrancois/mockserver-5_13_1-repro
2. Run the main method in `src/main/java/MockServer.java`
3. Aforementioned error appears
4. Run the unit tests in `src/test/java/MockServerTest.java`
5. Similar `NoSuchMethodError` appears

**Expected behaviour**
The mockserver to start normally, as when the mockserver version is 5.13.0, with an output like this:
```
2022-04-08 16:04:44 5.13.0 INFO 1080 started on port: 1080 
```

**MockServer Log**
No log output by MockServer, apart from the error.

**Comment by jamesdbloom** [comment]
Once you can confirm this is the issue I can make it clearer in the documentation to only use one or the other type of dependence.  The shading process re-writes packages so if you include both there is a race condition in the class loader as to which class is loaded and you're have a mix of re-written classes and non-re-written classes.

**Comment by jamesdbloom** [comment]
Closing this issue — it's a dependency version mismatch rather than a bug in MockServer. The `NoSuchMethodError` occurs when different MockServer artifacts (e.g. `mockserver-netty` and `mockserver-client-java`) are on the classpath at different versions. The constructor signature for `HttpActionHandler` changed in 5.13.1, so mixing 5.13.0 and 5.13.1 JARs causes this error. The fix is to ensure all MockServer dependencies use the same version.
