### ISSUE TITLE
NoClassDefFoundError when starting mockserver with version >=5.13.1

### ISSUE THREAD

**Issue by anilkumarmyla** [mock-server/mockserver#1274]
**Describe the issue**
This is similar to #1273 when using the shaded jar to start mockserver with an ExpectationInitializer

**What you are trying to do**
Given this ExpectationInitializer (which uses a method from io.swagger.models), starting mockserver with the shaded jar causes the error below 
```java
package com.foo.bar;

import io.swagger.models.HttpMethod;
import org.mockserver.mock.Expectation;
import org.mockserver.model.HttpRequest;
import org.mockserver.model.HttpResponse;
import org.mockserver.server.initialize.ExpectationInitializer;

public class ExpectationInitializerExample implements ExpectationInitializer {
  @Override
  public Expectation[] initializeExpectations() {
    return new Expectation[] {
      new Expectation(
              HttpRequest.request().withMethod(String.valueOf(HttpMethod.GET)).withPath("/foo"))
          .thenRespond(HttpResponse.response().withBody("bar"))
    };
  }
}
```

```
mockserver_1  | 2022-04-08 19:41:48 5.13.1 INFO loading class initialization file:
mockserver_1  | 
mockserver_1  |   com.foo.bar.ExpectationInitializerExample
mockserver_1  |  
mockserver_1  | 2022-04-08 19:41:48 5.13.1 WARNING exception while loading JSON initialization class, ignoring class:
mockserver_1  | 
mockserver_1  |   com.foo.bar.ExpectationInitializerExample
mockserver_1  |  
mockserver_1  | java.lang.NoClassDefFoundError: io/swagger/models/HttpMethod
mockserver_1  | 	at com.foo.bar.ExpectationInitializerExample.initializeExpectations(ExpectationInitializerExample.java:14)
mockserver_1  | 	at org.mockserver.server.initialize.ExpectationInitializerLoader.retrieveExpectationsFromInitializerClass(ExpectationInitializerLoader.java:85)
mockserver_1  | 	at org.mockserver.server.initialize.ExpectationInitializerLoader.addExpectationsFromInitializer(ExpectationInitializerLoader.java:61)
mockserver_1  | 	at org.mockserver.server.initialize.ExpectationInitializerLoader.<init>(ExpectationInitializerLoader.java:43)
mockserver_1  | 	at org.mockserver.mock.HttpState.<init>(HttpState.java:126)
mockserver_1  | 	at org.mockserver.lifecycle.LifeCycle.<init>(LifeCycle.java:55)
mockserver_1  | 	at org.mockserver.netty.MockServer.<init>(MockServer.java:77)
mockserver_1  | 	at org.mockserver.netty.MockServer.<init>(MockServer.java:48)
mockserver_1  | 	at org.mockserver.cli.Main.main(Main.java:149)
mockserver_1  | Caused by: java.lang.ClassNotFoundException: io.swagger.models.HttpMethod
mockserver_1  | 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
mockserver_1  | 	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
mockserver_1  | 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
mockserver_1  | 	... 9 more
```

**MockServer version**
 mockserver >= 5.13.1

**To Reproduce**
See above

**Expected behaviour**
This was working with 5.13.0, broken with 5.13.1 when shaded mockserver-netty started shading stuff into shaded_package

**MockServer Log**
See above

**Workaround**
Making below change makes the class work

```java
-import io.swagger.models.HttpMethod;
+import shaded_package.io.swagger.models.HttpMethod;
```

**Comment by jamesdbloom** [comment]
This code is attempting to use an internal class dependency from MockServer that class isn't part of the MockServer interface.  The packages has been moved by the shading process but it is an internal class so it should never have been referenced.

If callback code needs to use a class then it needs to be on the classpath otherwise the class loader can't load it.  So if you added the swagger dependency to the classpath of MockServer this code would work.
