### ISSUE TITLE
Certificate Chain for server authentication

### ISSUE THREAD

**Issue by RiccardoCaliffo** [mock-server/mockserver#1311]
I would use a Certificate Chain (multiple PEM file merged in one file - end-entity certificate + Intermediate certificate) to do server authentication.
I'm using the following env variable:

`MOCKSERVER_TLS_X509_CERTIFICATE_PATH`

pointing to a file with multiple certificates inside.

The mockserver shows the following error:

`2022-05-06 13:40:57 5.11.2 FINE using command line options:

  serverPort=1080
 
2022-05-06 13:41:00 5.11.2 INFO created expectation file watcher for

 
2022-05-06 13:41:03 5.11.2 FINE logger level is DEBUG, change using:
 - 'ConfigurationProperties.logLevel(String level)' in Java code,
 - '-logLevel' command line argument,
 - 'mockserver.logLevel' JVM system property or,
 - 'mockserver.logLevel' property value in 'mockserver.properties' 
2022-05-06 13:41:03 5.11.2 INFO 1080 started on port: 1080 
2022-05-06 13:41:20 5.11.2 SEVERE TSL handshake failure while a client attempted to connect to [id: 0xad8bc00f, L:0.0.0.0/0.0.0.0:1080] 
io.netty.handler.codec.DecoderException: javax.net.ssl.SSLHandshakeException: Insufficient buffer remaining for AEAD cipher fragment (2). Needs to be more than tag size (16)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:471)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: javax.net.ssl.SSLHandshakeException: Insufficient buffer remaining for AEAD cipher fragment (2). Needs to be more than tag size (16)
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:320)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:263)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:258)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:129)
	at java.base/sun.security.ssl.SSLEngineImpl.decode(SSLEngineImpl.java:668)
	at java.base/sun.security.ssl.SSLEngineImpl.readRecord(SSLEngineImpl.java:623)
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:441)
	at java.base/sun.security.ssl.SSLEngineImpl.unwrap(SSLEngineImpl.java:420)
	at java.base/javax.net.ssl.SSLEngine.unwrap(SSLEngine.java:634)
	at io.netty.handler.ssl.SslHandler$SslEngineType$3.unwrap(SslHandler.java:282)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1387)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1282)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1329)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
	... 16 more
Caused by: javax.crypto.BadPaddingException: Insufficient buffer remaining for AEAD cipher fragment (2). Needs to be more than tag size (16)
	at java.base/sun.security.ssl.SSLCipher$T13GcmReadCipherGenerator$GcmReadCipher.decrypt(SSLCipher.java:1868)
	at java.base/sun.security.ssl.SSLEngineInputRecord.decodeInputRecord(SSLEngineInputRecord.java:240)
	at java.base/sun.security.ssl.SSLEngineInputRecord.decode(SSLEngineInputRecord.java:197)
	at java.base/sun.security.ssl.SSLEngineInputRecord.decode(SSLEngineInputRecord.java:160)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
	... 27 more
`

when I perform the following curl:

`curl -L https://localhost:1080 --cacert rest-ms-certs/myRootCA.pem -v`

the output of curl is:

*   Trying 127.0.0.1:1080...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 1080 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: rest-ms-certs/myRootCA.pem
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (OUT), TLS alert, unsupported certificate (555):
* SSL certificate problem: unsupported certificate purpose
* Closing connection 0
curl: (60) SSL certificate problem: unsupported certificate purpose
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.

**Comment by jamesdbloom** [comment]
I believe is you upgrade your version MockServer to 5.13.2 this issue should be resolved.

Please confirm

**Comment by jamesdbloom** [comment]
It looks like the format of the certificate is not valid, the exception is indicating that.  Have you verified all the certificates in your file can be read by another tool?

**Comment by RiccardoCaliffo** [comment]
Yes, the certificates in the chain are correct. My dubt is about the position in the file. Currently I have the Intermediate certificate in the first position and the end-entity certificate in the second position. 
Should they be inverted?

**Comment by jamesdbloom** [comment]
Can you please show how you are creating your certificates.  Are you specifying EC certificates for example as these are not currently supported but will be very soon.

**Comment by jamesdbloom** [comment]
Please re-test as EC certificates are now supported in MockServer

**Comment by jamesdbloom** [comment]
Closing this issue as the reported error is almost certainly a user certificate configuration issue, not a MockServer bug. The issue is also 3+ years old with no follow-up.

## Analysis

The error `SSL certificate problem: unsupported certificate purpose` from curl indicates the TLS handshake completed (MockServer sent its certificate) but curl rejected the certificate for one of these reasons:

1. **Missing `certificateAuthorityCertificate` configuration** (most likely) — When you set `MOCKSERVER_TLS_X509_CERTIFICATE_PATH` and `MOCKSERVER_TLS_PRIVATE_KEY_PATH`, you must also set `MOCKSERVER_CERTIFICATE_AUTHORITY_X509_CERTIFICATE` to your own CA certificate. Without this, MockServer sends a chain of `[your_leaf_cert, MockServer_default_CA]`, which is invalid because MockServer's built-in CA didn't sign your leaf certificate.

2. **Certificate lacks `serverAuth` Extended Key Usage** — If your leaf certificate was generated without the `serverAuth` EKU, strict TLS clients will reject it with "unsupported certificate purpose".

3. **CA certificate has `basicConstraints: CA=FALSE`** — If the signing CA certificate doesn't have proper CA constraints.

## Regarding certificate chains (multiple PEM certs in one file)

MockServer currently reads only the first certificate from `x509CertificatePath` (uses `generateCertificate` singular, not `generateCertificates`). The `certificateChain()` method in `BCKeyAndCertificateFactory` hardcodes a 2-element chain: `[leaf_cert, CA_cert]`. If you need intermediate CA support, this would be a separate feature request.

## The SSLHandshakeException in the server log

The `Insufficient buffer remaining for AEAD cipher fragment` error is a secondary symptom — it occurs when the client aborts the TLS 1.3 handshake mid-flight (after rejecting the certificate), causing the server to receive a truncated/malformed message.

## Correct configuration for custom certificates

```bash
MOCKSERVER_TLS_X509_CERTIFICATE_PATH=/path/to/leaf-cert.pem
MOCKSERVER_TLS_PRIVATE_KEY_PATH=/path/to/private-key.pem
MOCKSERVER_CERTIFICATE_AUTHORITY_X509_CERTIFICATE=/path/to/ca-cert.pem
MOCKSERVER_CERTIFICATE_AUTHORITY_PRIVATE_KEY=/path/to/ca-private-key.pem
```

Then verify with:
```bash
curl -L https://localhost:1080 --cacert /path/to/ca-cert.pem -v
```

**Comment by jamesdbloom** [comment]
This issue was most likely caused by providing certificates that were misconfigured (e.g., missing intermediate chain, key/cert mismatch, or incorrect CA configuration). Previously, MockServer gave no upfront feedback on certificate misconfiguration — errors only surfaced as cryptic Netty-level messages during TLS handshakes.

MockServer now has significantly improved TLS error reporting (commit afa44a228):

- **Startup validation** — custom certificates are validated eagerly before accepting connections. Misconfigurations (key/cert mismatch, expired certs, missing files, unsigned-by-CA) now produce actionable error messages with file paths and remediation steps, and MockServer fails to start rather than silently serving broken TLS.
- **Intermediate CA chain support** — `x509CertificatePath` can now contain a full PEM chain (leaf + intermediates), and the entire chain is sent during TLS handshake.
- **Improved runtime diagnostics** — TLS handshake failures now include diagnostic hints (`certificate_unknown`, `bad_certificate`, `handshake_failure`, `no_certificate`) and the configured certificate file paths.

If you encounter similar issues in future, the new error messages should make the root cause immediately clear.

**Comment by jamesdbloom** [comment]
Relevant commit: afa44a22855dcf2527bfa91ef9e4ba3480aa3535
