### ISSUE TITLE
`TypeError` when using `mockserver-client` in the browser: `Cannot read properties of undefined (reading 'startsWith')`

### ISSUE THREAD

**Issue by OliverJAsh** [mock-server/mockserver#1375]
Full reduced test case: https://github.com/OliverJAsh/mockserver-test/tree/client-exception

`package.json`:
```json
{
  "dependencies": {
    "http-server": "^14.1.1",
    "mockserver-client": "^5.13.2",
    "mockserver-node": "^5.13.2"
  }
}

```

`main.js`:
```js
const ms = require("mockserver-node");
ms.start_mockserver({
    serverPort: 3030,
});

```

`index.html`:
```html
<script src="https://unpkg.com/mockserver-client@5.13.2/mockServerClient.js"></script>
<script src="./client.js"></script>

```

`client.js`:
```js
const mock = mockServerClient("localhost", 3030);
mock.mockAnyResponse([]);

```

```sh
yarn
node main.js

http-server -c-1
open localhost:8080
```

… then open the console and you will see this error:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'startsWith')
    at makeRequest (mockServerClient.js:33:91)
    at Object.mockAnyResponse (mockServerClient.js:366:20)
    at client.js:2:6
```

<img width="1840" alt="image" src="https://user-images.githubusercontent.com/921609/175784366-daba0cc8-f5f3-4ba2-b68e-bb69cbf84459.png">

I've created this patch to workaround the issue:

`patches/mockserver-client+5.13.2.patch`:
```patch
diff --git a/node_modules/mockserver-client/mockServerClient.js b/node_modules/mockserver-client/mockServerClient.js
index 3338f5d..df72eab 100644
--- a/node_modules/mockserver-client/mockServerClient.js
+++ b/node_modules/mockserver-client/mockServerClient.js
@@ -30,7 +30,7 @@ var mockServerClient;
 
         var makeRequest = (runningInNode() ? require('./sendRequest').sendRequest(tls, caCertPemFilePath) : function (host, port, path, jsonBody) {
             var body = (typeof jsonBody === "string" ? jsonBody : JSON.stringify(jsonBody || ""));
-            var url = (tls ? 'https' : 'http') + '://' + host + ':' + port + (contextPath.startsWith("/") ? contextPath : "/" + contextPath) + path;
+            var url = (tls ? 'https' : 'http') + '://' + host + ':' + port + (contextPath !== undefined ? contextPath.startsWith("/") ? contextPath : "/" + contextPath : '') + path;
 
             return {
                 then: function (sucess, error) {

```

**Comment by jamesdbloom** [comment]
Closing as out of scope for this repository. The `mockserver-client-node` npm package lives in a separate repository at https://github.com/mock-server/mockserver-client-node. Please file this issue there.
