### ISSUE TITLE
Improve error for binary requests when proxying is not configured

### ISSUE THREAD

**Issue by KirillKurdyukov** [mock-server/mockserver#1450]
Hello! 
I make request to mock server and have next exception.

```
2022-08-24 11:36:47.549  INFO [,,] 50450 --- [           main] r.y.fintech.oneshot.curl.OneshotCurl     : Create request...
url: http://localhost:12333/test/endpoint
requestMethod: POST
2022-08-24 11:36:47.703  INFO [,,] 50450 --- [erver-EventLog0] org.mockserver.log.MockServerEventLog    : received binary request:

  706f7374202f746573742f656e64706f696e7420485454502f312e310d0a436f6e74656e742d4c656e6774683a20300d0a486f73743a206c6f63616c686f73743a31323333330d0a4163636570743a202a2f2a0d0a4163636570742d436861727365743a205554462d380d0a557365722d4167656e743a204b746f7220636c69656e740d0a0d0a

2022-08-24 11:36:47.704  INFO [,,] 50450 --- [erver-EventLog0] org.mockserver.log.MockServerEventLog    : unknown message format

  706f7374202f746573742f656e64706f696e7420485454502f312e310d0a436f6e74656e742d4c656e6774683a20300d0a486f73743a206c6f63616c686f73743a31323333330d0a4163636570743a202a2f2a0d0a4163636570742d436861727365743a205554462d380d0a557365722d4167656e743a204b746f7220636c69656e740d0a0d0a


java.io.IOException: parsing HTTP/1.1 status line, receiving [unknown message format], parser state [STATUS_LINE]

	at java.net.http/jdk.internal.net.http.common.Utils.wrapWithExtraDetail(Utils.java:351)
	at java.net.http/jdk.internal.net.http.Http1Response$HeadersReader.onReadError(Http1Response.java:675)
	at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.checkForErrors(Http1AsyncReceiver.java:302)
	at java.net.http/jdk.internal.net.http.Http1AsyncReceiver.flush(Http1AsyncReceiver.java:268)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$LockingRestartableTask.run(SequentialScheduler.java:205)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$CompleteRestartableTask.run(SequentialScheduler.java:149)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.io.EOFException: EOF reached while reading
	at java.net.http/jdk.internal.net.http.Http1AsyncReceiver$Http1TubeSubscriber.onComplete(Http1AsyncReceiver.java:596)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadSubscription.signalCompletion(SocketTube.java:640)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.read(SocketTube.java:845)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowTask.run(SocketTube.java:181)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler$SchedulableTask.run(SequentialScheduler.java:230)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:303)
	at java.net.http/jdk.internal.net.http.common.SequentialScheduler.runOrSchedule(SequentialScheduler.java:256)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$InternalReadSubscription.signalReadable(SocketTube.java:774)
	at java.net.http/jdk.internal.net.http.SocketTube$InternalReadPublisher$ReadEvent.signalEvent(SocketTube.java:957)
	at java.net.http/jdk.internal.net.http.SocketTube$SocketFlowEvent.handle(SocketTube.java:253)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.handleEvent(HttpClientImpl.java:979)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.lambda$run$3(HttpClientImpl.java:934)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.net.http/jdk.internal.net.http.HttpClientImpl$SelectorManager.run(HttpClientImpl.java:934)
```

I create request with ktor framework for Kotlin. 

```
val client = HttpClient(Java)

        val response: HttpResponse = runBlocking {
            client.request {
                url {
                    takeFrom(input.url)
                }

                method = input.requestMethod.toHttpMethod()
            }
      }
```

**Comment by KirillKurdyukov** [comment]
Hex to String
post /test/endpoint HTTP/1.1
Content-Length: 0
Host: localhost:12333
Accept: */*
Accept-Charset: UTF-8
User-Agent: Ktor client

**Comment by jamesdbloom** [comment]
You method doesn't look correct as it is in lowercase which doesn't conform to the HTTP specification: https://www.rfc-editor.org/rfc/rfc9110.html#name-methods

**Please try again with a valid method name and this should work correctly.**

The error is happening because MockServer is treating the data as binary which is only supports for proxying, and no proxying has been configured.

I'll update this issue to have a clearer title and fix the error that appears in the log to make that clearer.

**Comment by KirillKurdyukov** [comment]
Thanks! The error was in lowercase http method!
