### ISSUE TITLE
PEM Expired? Not Returning expectations

### ISSUE THREAD

**Issue by lexanta** [mock-server/mockserver#1451]
**Describe the issue**
Encountering following since Early Monday Morning (08/22/2022) suddenly with no changes at our end:

2022-08-24 19:25:57 5.14.0 INFO loaded CA private key from path
  file:/mockserver-netty-jar-with-dependencies.jar!/org/mockserver/socket/PKCS8CertificateAuthorityPrivateKey.pem
 
2022-08-24 19:26:02 5.14.0 INFO exception decoding client certificate 

Full Log below

**What you are trying to do**
Running Mock Server on ECS Fargate Via Terraform
This should always pull the latest image as far as we are let to believe

**To Reproduce**
Steps to reproduce the issue:

1. deploy docker via fargate on aws (note this started without a redeploy)
3. clear and reset expectations successfully via direct integration
4. Attempt to contact proxy to retrieve expected response
5. Mock Proxy sends traffic to actual backend

**Expected behaviour**
Expecting Mock server to return expectations as set

**MockServer Log**
```
2022-08-24 19:40:05 5.14.0 INFO using environment variables:
--
[
MOCKSERVER_SOCKET_CONNECTION_TIMEOUT=200000,
SERVER_PORT=1080,
MOCKSERVER_MAX_FUTURE_TIMEOUT=6000000,
MOCKSERVER_MAX_EXPECTATIONS=2000,
MOCKSERVER_FORWARD_HTTP_PROXY=proxy.qa.squid.ecs:3128,
MOCKSERVER_FORWARD_HTTPS_PROXY=proxy.qa.squid.ecs:3128,
MOCKSERVER_LIVENESS_HTTP_GET_PATH=/liveness/probe,
MOCKSERVER_MAX_SOCKET_TIMEOUT=200000,
MOCKSERVER_ALWAYS_CLOSE_SOCKET_CONNECTIONS=true
]
and system properties:
[
mockserver.propertyFile=/config/mockserver.properties
]
and command line options:
[
 
]
 
2022-08-24 19:40:06 5.14.0 INFO logger level is INFO, change using:
- 'ConfigurationProperties.logLevel(String level)' in Java code,
- '-logLevel' command line argument,
- 'mockserver.logLevel' JVM system property or,
- 'mockserver.logLevel' property value in 'mockserver.properties'
2022-08-24 19:40:06 5.14.0 INFO 1080 started on port: 1080
2022-08-24 19:40:13 5.14.0 INFO loaded CA X509 from path
file:/mockserver-netty-jar-with-dependencies.jar!/org/mockserver/socket/CertificateAuthorityCertificate.pem
containing PEM
-----BEGIN CERTIFICATE-----
MIIDqDCCApCgAwIBAgIEPhwe6TANBgkqhkiG9w0BAQsFADBiMRswGQYDVQQDDBJ3
d3cubW9ja3NlcnZlci5jb20xEzARBgNVBAoMCk1vY2tTZXJ2ZXIxDzANBgNVBAcM
BkxvbmRvbjEQMA4GA1UECAwHRW5nbGFuZDELMAkGA1UEBhMCVUswIBcNMTYwNjIw
MTYzNDE0WhgPMjExNzA1MjcxNjM0MTRaMGIxGzAZBgNVBAMMEnd3dy5tb2Nrc2Vy
dmVyLmNvbTETMBEGA1UECgwKTW9ja1NlcnZlcjEPMA0GA1UEBwwGTG9uZG9uMRAw
DgYDVQQIDAdFbmdsYW5kMQswCQYDVQQGEwJVSzCCASIwDQYJKoZIhvcNAQEBBQAD
ggEPADCCAQoCggEBAPGORrdkwTY1H1dvQPYaA+RpD+pSbsvHTtUSU6H7NQS2qu1p
sE6TEG2fE+Vb0QIXkeH+jjKzcfzHGCpIU/0qQCu4RVycrIW4CCdXjl+T3L4C0I3R
mIMciTig5qcAvY9P5bQAdWDkU36YGrCjGaX3QlndGxD9M974JdpVK4cqFyc6N4gA
Onys3uS8MMmSHTjTFAgR/WFeJiciQnal+Zy4ZF2x66CdjN+hP8ch2yH/CBwrSBc0
ZeH2flbYGgkh3PwKEqATqhVa+mft4dCrvqBwGhBTnzEGWK/qrl9xB4mTs4GQ/Z5E
8rXzlvpKzVJbfDHfqVzgFw4fQFGV0XMLTKyvOX0CAwEAAaNkMGIwHQYDVR0OBBYE
FH3W3sL4XRDM/VnRayaSamVLISndMA8GA1UdEwEB/wQFMAMBAf8wCwYDVR0PBAQD
AgG2MCMGA1UdJQQcMBoGCCsGAQUFBwMBBggrBgEFBQcDAgYEVR0lADANBgkqhkiG
9w0BAQsFAAOCAQEAecfgKuMxCBe/NxVqoc4kzacf9rjgz2houvXdZU2UDBY3hCs4
MBbM7U9Oi/3nAoU1zsA8Rg2nBwc76T8kSsfG1TK3iJkfGIOVjcwOoIjy3Z8zLM2V
YjYbOUyAQdO/s2uShAmzzjh9SV2NKtcNNdoE9e6udvwDV8s3NGMTUpY5d7BHYQqV
sqaPGlsKi8dN+gdLcRbtQo29bY8EYR5QJm7QJFDI1njODEnrUjjMvWw2yjFlje59
j/7LBRe2wfNmjXFYm5GqWft10UJ7Ypb3XYoGwcDac+IUvrgmgTHD+E3klV3SUi8i
Gm5MBedhPkXrLWmwuoMJd7tzARRHHT6PBH/ZGw==
-----END CERTIFICATE-----
 
2022-08-24 19:40:13 5.14.0 INFO loaded CA private key from path
file:/mockserver-netty-jar-with-dependencies.jar!/org/mockserver/socket/PKCS8CertificateAuthorityPrivateKey.pem
 
2022-08-24 19:40:17 5.14.0 INFO exception decoding client certificate
java.lang.IllegalStateException: javax.security.cert.CertificateException: Could not find class: java.lang.ClassNotFoundException: com/sun/security/cert/internal/x509/X509V1CertImpl
at io.netty.handler.ssl.util.LazyJavaxX509Certificate.unwrap(LazyJavaxX509Certificate.java:142)
at io.netty.handler.ssl.util.LazyJavaxX509Certificate.getSerialNumber(LazyJavaxX509Certificate.java:61)
at org.mockserver.mappers.JDKCertificateToMockServerX509Certificate.lambda$setClientCertificates$0(JDKCertificateToMockServerX509Certificate.java:34)
at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
at org.mockserver.mappers.JDKCertificateToMockServerX509Certificate.setClientCertificates(JDKCertificateToMockServerX509Certificate.java:54)
at org.mockserver.mappers.FullHttpRequestToMockServerHttpRequest.mapFullHttpRequestToMockServerRequest(FullHttpRequestToMockServerHttpRequest.java:73)
at org.mockserver.codec.NettyHttpToMockServerHttpRequestDecoder.decode(NettyHttpToMockServerHttpRequestDecoder.java:36)
at org.mockserver.codec.NettyHttpToMockServerHttpRequestDecoder.decode(NettyHttpToMockServerHttpRequestDecoder.java:18)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at org.mockserver.dashboard.DashboardWebSocketHandler.channelRead(DashboardWebSocketHandler.java:137)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at org.mockserver.netty.websocketregistry.CallbackWebSocketServerHandler.channelRead(CallbackWebSocketServerHandler.java:57)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
```

**Comment by jamesdbloom** [comment]
Why do you think the PEM is expired, the error shows a ClassNotFoundException, or am I missing something?

Also I assume you are using the latest tag to run your container, so you are now using the recently release 5.14.0 version as I can see from your logs.

What confuses me is that I'm running the exact same image on my machine without any issue so I don't understand how a class could be missing from your image.  Have you modified the image at all?

**Comment by lexanta** [comment]
Its was a guess being as It could not apparently decode and as it started manifesting overnight suddenly a week ago. 

As far as any mods go, no. we are drawing in the image via terraform script on AWS ECS/Fargate. As far as I know that will not cache nor alter. Though now that you mention latest I do notice that this version was apparently released a week ago. So maybe its something about this image and how it plays with fargate.

Let me try to force downgrade to last

**Comment by lexanta** [comment]
A forced downgrade to the previous version worked. As it turns out the entire error chain that we see in the logs is a red herring and was happening before and is happening after.

I do not know why, but it seems that something about 3.14.0 is not working properly on our setup. 3.13.2 works fine for our needs and this satisfies us and our needs. Thanks.

**Comment by sebagomez** [comment]
This is so weird, a bit over one year after this issue was opened I'm running the MockServer through its Helm chart (5.14.0) and I see the same issue.

I'm running the cluster on WSL tunneling to Windows and running a Windows app with the MockServer as proxy.

Any ideas?
