### ISSUE TITLE
ClassNotFoundException for a registered callback class

### ISSUE THREAD

**Issue by zhelepas** [mock-server/mockserver#1571]
**Describe the issue**
We are using mockserver-netty in Java and recently we updated the version to 5.13.2 (from 5.11.2). We have a json file with some mock requests and for some of the we use httpResponseClassCallback to reference to a class with the handling logic. But after migrating to ver. 5.13.2 we started getting ClassNotFoundException for the callback class.

**What you are trying to do**
Register httpResponseClassCallback (in json) and define a class with the handling logic.

**MockServer version**
5.13.2 and 5.14.0

**To Reproduce**
Steps to reproduce the issue:

1.Define a server_requests.json file with the following content:
```json
{
    "httpRequest": {
      "path": "/test/endpoint",
      "method" : "POST"
    },
    "httpResponseClassCallback": {
      "callbackClass": "com.vw.odp.cte.mockrestservice.test.callback.TestCallback"
    }
}
```

2. Create the TestCallback class:
```java
public class TestCallback implements ExpectationResponseCallback {

  public TestCallback () {
    MockServerServiceApplication.autowire(this);
  }

  @Override
  public HttpResponse handle(final HttpRequest httpRequest) {
   // do stuff
    return HttpResponse.response();
  }
}
```
```java
@SpringBootApplication
public class MockServerServiceApplication implements CommandLineRunner {
  private static MockServerServiceApplication INSTANCE;

  public static void autowire(final Object bean) {
    INSTANCE.applicationContext.getAutowireCapableBeanFactory().autowireBean(bean);
  }

  @Autowired private ApplicationContext applicationContext;

  public MockServerServiceApplication() {
    MockServerServiceApplication.INSTANCE = this;
  }

  public static void main(final String[] args) {
    SpringApplication.run(MockServerServiceApplication.class, args);
  }

  @Override
  public void run(final String... args) throws Exception {
    System.setProperty(
        "mockserver.initializationClass", ExpectationInitializerFromJsonFiles.class.getName());
    org.mockserver.cli.Main.main(args);
  }
}
```

3. Run the mockserver by using the following command:
`java -Dmockserver.initializationJsonPath=server_requests.json -jar ./target/mock-rest-service-1.0.0-SNAPSHOT.jar -serverPort 3000`

4. With version 5.11.2 this was working fine and /test/endpoint request was triggering the handle() method of the callback class. After migrating to 5.13.2 (same for 5.14.0) this doesn't work anymore and when we trigger the endpoint we get:
```
 matched expectation:

  {
    "httpRequest" : {
      "method" : "POST",
      "path" : "/test/endpoint"
    },
    "httpResponseClassCallback" : {
      "callbackClass" : "com.vw.odp.cte.mockrestservice.test.callback.TestCallback"
    },
    "id" : "8068d0f6-3101-3469-be54-30345d4c0ca2",
    "priority" : 0,
    "timeToLive" : {
      "unlimited" : true
    },
    "times" : {
      "unlimited" : true
    }
  }

2022-12-09 16:14:43.727 ERROR 5412 --- [erver-EventLog0] org.mockserver.log.MockServerEventLog    : 3000 ClassNotFoundException - while trying to instantiate ExpectationResponseCallback class "com.vw.odp.cte.mockrestservice.test.callback.TestCallback"

java.lang.ClassNotFoundException: com.vw.odp.cte.mockrestservice.test.callback.TestCallback
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583) ~[na:na]
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[na:na]
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[na:na]
        at org.mockserver.mock.action.http.HttpResponseClassCallbackActionHandler.instantiateCallback(HttpResponseClassCallbackActionHandler.java:40) ~[mockserver-core-5.13.2.jar!/:5.13.2]
        at org.mockserver.mock.action.http.HttpResponseClassCallbackActionHandler.invokeCallbackMethod(HttpResponseClassCallbackActionHandler.java:79) ~[mockserver-core-5.13.2.jar!/:5.13.2]
        at org.mockserver.mock.action.http.HttpResponseClassCallbackActionHandler.handle(HttpResponseClassCallbackActionHandler.java:34) ~[mockserver-core-5.13.2.jar!/:5.13.2]
```

**Comment by g-schaeffer** [comment]
I face the same issue, and I found the culprit for my case, so I'm sharing with you incase it helps:
I bumped from chart 5.13 to chart 5.14 and it stopped working. The difference is that the /libs mount is no longer commented out.
You can notice that in the dockerfile that the /libs mount is used to provide additional content to the classpath, so that would be a nice place to provide content for callbacks: "-cp", "/mockserver-netty-jar-with-dependencies.jar:/libs/*"
https://github.com/mock-server/mockserver/blob/master/docker/Dockerfile#L54 

In our case, we build a custom mock-server image, importing the base docker one, and adding directly in /libs our callbakcs

However in the chart, there is now a mount in /libs as well https://github.com/mock-server/mockserver/blob/master/helm/mockserver/templates/deployment.yaml#L84 and the default mounted content is mockserver-config configmap https://github.com/mock-server/mockserver/blob/master/helm/mockserver/values.yaml#L9 

If your configmap has no jar, it overrides the /lib with no jar content and this likely is the root cause of the ClassNotFound.

Either override the helm chart, or a fix needs to be done to condition the /libs volume dependending on the presence of mountedLibsConfigMapName in values

**Comment by g-schaeffer** [comment]
Thanks James ;)

**Comment by jamesdbloom** [comment]
Fixed in commit 36e81912c.

**Root cause:** `HttpResponseClassCallbackActionHandler` used `ClassLoader.getSystemClassLoader()` (line 21) and `HttpForwardClassCallbackActionHandler` used `Class.forName()` (line 32) to load user callback classes. In a Spring Boot uber JAR, user classes are loaded by `LaunchedURLClassLoader`, which is not the system classloader. This caused `ClassNotFoundException` for any callback class.

**Fix:** Both handlers now prefer `Thread.currentThread().getContextClassLoader()` (which Spring Boot sets to its custom classloader), falling back to the system classloader if the context classloader is null.
