### ISSUE TITLE
Warnings on deploying mockserver as a WAR on JBoss

### ISSUE THREAD

**Issue by ThiAmm** [mock-server/mockserver#1656]
**Describe the issue**
There are several warnings in the server-log file while deploying mockserver as a WAR-File on JBoss 7.3. One of them is:
`WARN  [org.jboss.as.server.deployment] (MSC service thread 1-8) WFLYSRV0003: Could not index class com/google
/common/collect/MultimapBuilder$MultimapBuilderWithKeys$2.class in /C:/UData/jboss/jboss-eap-7.3-NVG-2.5/bin/content/mockserv
er-war-5.15.0.war/WEB-INF/lib/guava-31.1-jre.jar: java.lang.ArrayIndexOutOfBoundsException: Index 1 out of b
ounds for length 0
        at org.jboss.jandex@2.1.2.Final-redhat-00001//org.jboss.jandex.Indexer.updateTypeTarget(Indexer.java:840)
        at org.jboss.jandex@2.1.2.Final-redhat-00001//org.jboss.jandex.Indexer.updateTypeTargets(Indexer.java:624)
        at org.jboss.jandex@2.1.2.Final-redhat-00001//org.jboss.jandex.Indexer.index(Indexer.java:1603)
        at org.jboss.as.server@10.1.23.Final-redhat-00001//org.jboss.as.server.deployment.annotation.ResourceRootIndexer.inde
xResourceRoot(ResourceRootIndexer.java:99)
        at org.jboss.as.server@10.1.23.Final-redhat-00001//org.jboss.as.server.deployment.annotation.AnnotationIndexProcessor
.deploy(AnnotationIndexProcessor.java:51)
        at org.jboss.as.server@10.1.23.Final-redhat-00001//org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(De
ploymentUnitPhaseService.java:176)
        at org.jboss.msc@1.4.11.Final-redhat-00001//org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(Servic
eControllerImpl.java:1739)
        at org.jboss.msc@1.4.11.Final-redhat-00001//org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceCont
rollerImpl.java:1701)
        at org.jboss.msc@1.4.11.Final-redhat-00001//org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceCon
trollerImpl.java:1559)
        at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoa
derSavingRunnable.java:35)
        at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.
java:1982)
        at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQ
ueueExecutor.java:1486)
        at org.jboss.threads@2.3.3.Final-redhat-00001//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueEx
ecutor.java:1363)
        at java.base/java.lang.Thread.run(Thread.java:829)`
**What you are trying to do**
I deploy mockServer using the WAR file.
**MockServer version**
5.15.0

**To Reproduce**
1. download [mockserver-war-5.14.0.war](https://search.maven.org/remotecontent?filepath=org/mock-server/mockserver-war/5.14.0/mockserver-war-5.14.0.war) from Maven Central
2. Deploy on JBoss 7.3
3. Inspect server logs

1. How you are running MockServer (i.e maven plugin, docker, etc)
5. What error you saw

**Expected behaviour**
What you expected to happen

**MockServer Log**
Log output, as INFO level (or lower)

**Comment by malfj** [comment]
I've encountered the same issue and I can share the findings:

It's a jandex issue: https://github.com/smallrye/jandex/issues/147
Fixed by https://github.com/smallrye/jandex/pull/154 merged on Oct 7, 2021 and part of milestone 2.4.1.Final.
According to https://issues.redhat.com/browse/JBEAP-23528 JBoss 7.4.6.GA should contain the fix.

**Comment by jamesdbloom** [comment]
**Resolution: JBoss/Jandex bug**

As identified by @malfj, this is a bug in the Jandex annotation indexer used by JBoss/WildFly, not in MockServer. The issue was fixed in Jandex 2.4.1.Final.

To resolve: upgrade Jandex in your JBoss/WildFly installation, or exclude MockServer JARs from annotation scanning.
