### ISSUE TITLE
mock-server-no-dependencies includes JDK14LoggerAdapter

### ISSUE THREAD

**Issue by BartVansegbroeck** [mock-server/mockserver#1660]
**Describe the issue**
The latest version of mock-server-no-dependencies includes the SLF4J JDK14LoggerAdapter. By adding this to the classpath, a circular logging path is created in case someone redirects logging from JUL to SLF4J. 

**What you are trying to do**
No explicit feature of mock-server is involved.

**MockServer version**
5.15.0
5.14.0 did not cause any issues.

**To Reproduce**
Start a Spring application with mock-server-no-dependencies dependency and setup SLF4J to log to something else, say LOG4J2.

1. How you are running MockServer (i.e maven plugin, docker, etc)
MockServer started from integration tests, error occurs in gradle CLI build as well as IntelliJ run.
2. Code you used to create expectations

3. What error you saw
`	
        Caused by: java.lang.StackOverflowError
	at java.base/java.util.HashMap.hash(HashMap.java:338)
	at java.base/java.util.HashMap.getNode(HashMap.java:568)
	at java.base/java.util.HashMap.containsKey(HashMap.java:594)
	at java.base/java.util.HashSet.contains(HashSet.java:205)
	at java.base/java.lang.StackTraceElement$HashedModules.contains(StackTraceElement.java:525)
	at java.base/java.lang.StackTraceElement.isHashedInJavaBase(StackTraceElement.java:496)
	at java.base/java.lang.StackTraceElement.computeFormat(StackTraceElement.java:462)
	at java.base/java.lang.StackTraceElement.of(StackTraceElement.java:545)
	at java.base/java.lang.Throwable.getOurStackTrace(Throwable.java:839)
	at java.base/java.lang.Throwable.getStackTrace(Throwable.java:831)
	at org.slf4j.jul.JDK14LoggerAdapter.fillCallerData(JDK14LoggerAdapter.java:182)
	at org.slf4j.jul.JDK14LoggerAdapter.innerNormalizedLoggingCallHandler(JDK14LoggerAdapter.java:155)
	at org.slf4j.jul.JDK14LoggerAdapter.log(JDK14LoggerAdapter.java:172)
	at org.slf4j.bridge.SLF4JBridgeHandler.callLocationAwareLogger(SLF4JBridgeHandler.java:221)
	at org.slf4j.bridge.SLF4JBridgeHandler.publish(SLF4JBridgeHandler.java:303)
	at java.logging/java.util.logging.Logger.log(Logger.java:980)
	at org.slf4j.jul.JDK14LoggerAdapter.innerNormalizedLoggingCallHandler(JDK14LoggerAdapter.java:156)
	at org.slf4j.jul.JDK14LoggerAdapter.log(JDK14LoggerAdapter.java:172)
`

**Expected behaviour**

**MockServer Log**
n/a

**Workaround**
Switch to org.mock-server:mockserver-netty and exclude dependencies, but this also didn't work for us, as mock-server requires older versions of a few libraries (mainly fasterxml) than we are currtly using.

**Comment by MoritzHorch** [comment]
Hello @jamesdbloom, could you please look into this issue?

I think this issue affects a lot of people running mock-server with spring boot. My team tries to avoid introducing workarounds by manually adjusting the `pom.xml` as those fixes tend be forgotten after a while. Additionally, the name `mockserver-netty-no-dependencies` is currently misleading for anyone who really does care about not adding too many dependencies.

We are really happy with this piece of software currently, but this issue, as it currently affects the latest version, could discourage some people.

Thanks in advance :)

**Comment by markvr** [comment]
This is also affecting us.  Can the pull request above be merged please?
