### ISSUE TITLE
under jdk17, meet javax.security.cert.CertificateException: Could not find class: java.lang.ClassNotFoundException: com/sun/security/cert/internal/x509/X509V1CertImpl

### ISSUE THREAD

**Issue by yqzhan** [mock-server/mockserver#1739]
**Describe the issue**
under jdk17, meet javax.security.cert.CertificateException: Could not find class: java.lang.ClassNotFoundException: com/sun/security/cert/internal/x509/X509V1CertImpl

**What you are trying to do**
try upgrade jdk8 to jdk17

**MockServer version**
<dependency>
    <groupId>org.mock-server</groupId>
    <artifactId>mockserver-netty-no-dependencies</artifactId>
    <version>5.15.0</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.mock-server</groupId>
    <artifactId>mockserver-client-java-no-dependencies</artifactId>
    <version>5.15.0</version>
    <scope>test</scope>
</dependency>

**To Reproduce**
Steps to reproduce the issue:

1. How you are running MockServer (i.e maven plugin, docker, etc)
   junit
2. Code you used to create expectations
   send https request to mock server
3. What error you saw
   javax.security.cert.CertificateException: Could not find class: java.lang.ClassNotFoundException: com/sun/security/cert/internal/x509/X509V1CertImpl
**Expected behaviour**
no error

**MockServer Log**

2023-05-12 10:33:53,243+08:00:INFO[MockServer-EventLog90]o.m.l.MockServerEventLog:119-->1080 exception decoding client certificate
java.lang.IllegalStateException: javax.security.cert.CertificateException: Could not find class: java.lang.ClassNotFoundException: com/sun/security/cert/internal/x509/X509V1CertImpl
        at shaded_package.io.netty.handler.ssl.util.LazyJavaxX509Certificate.unwrap(LazyJavaxX509Certificate.java:142) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.handler.ssl.util.LazyJavaxX509Certificate.getSerialNumber(LazyJavaxX509Certificate.java:61) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at org.mockserver.mappers.JDKCertificateToMockServerX509Certificate.lambda$setClientCertificates$0(JDKCertificateToMockServerX509Certificate.java:34) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[?:?]
        at org.mockserver.mappers.JDKCertificateToMockServerX509Certificate.setClientCertificates(JDKCertificateToMockServerX509Certificate.java:54) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at org.mockserver.mappers.FullHttpRequestToMockServerHttpRequest.mapFullHttpRequestToMockServerRequest(FullHttpRequestToMockServerHttpRequest.java:74) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at org.mockserver.codec.NettyHttpToMockServerHttpRequestDecoder.decode(NettyHttpToMockServerHttpRequestDecoder.java:40) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at org.mockserver.codec.NettyHttpToMockServerHttpRequestDecoder.decode(NettyHttpToMockServerHttpRequestDecoder.java:20) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at org.mockserver.dashboard.DashboardWebSocketHandler.channelRead(DashboardWebSocketHandler.java:137) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at org.mockserver.netty.websocketregistry.CallbackWebSocketServerHandler.channelRead(CallbackWebSocketServerHandler.java:57) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.handler.codec.http2.InboundHttp2ToHttpAdapter.fireChannelRead(InboundHttp2ToHttpAdapter.java:133) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.handler.codec.http2.InboundHttp2ToHttpAdapter.onDataRead(InboundHttp2ToHttpAdapter.java:245) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.handler.codec.http2.DelegatingDecompressorFrameListener.onDataRead(DelegatingDecompressorFrameListener.java:82) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.handler.codec.http2.Http2FrameListenerDecorator.onDataRead(Http2FrameListenerDecorator.java:36) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.handler.codec.http2.Http2EmptyDataFrameListener.onDataRead(Http2EmptyDataFrameListener.java:49) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder$FrameReadListener.onDataRead(DefaultHttp2ConnectionDecoder.java:307) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.handler.codec.http2.DefaultHttp2FrameReader.readDataFrame(DefaultHttp2FrameReader.java:415) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.handler.codec.http2.DefaultHttp2FrameReader.processPayloadState(DefaultHttp2FrameReader.java:250) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.handler.codec.http2.DefaultHttp2FrameReader.readFrame(DefaultHttp2FrameReader.java:159) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.handler.codec.http2.DefaultHttp2ConnectionDecoder.decodeFrame(DefaultHttp2ConnectionDecoder.java:173) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.handler.codec.http2.DecoratingHttp2ConnectionDecoder.decodeFrame(DecoratingHttp2ConnectionDecoder.java:63) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.handler.codec.http2.Http2ConnectionHandler$FrameDecoder.decode(Http2ConnectionHandler.java:393) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.handler.codec.http2.Http2ConnectionHandler.decode(Http2ConnectionHandler.java:453) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1373) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1236) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1285) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at shaded_package.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: javax.security.cert.CertificateException: Could not find class: java.lang.ClassNotFoundException: com/sun/security/cert/internal/x509/X509V1CertImpl
        at javax.security.cert.X509Certificate.getInst(X509Certificate.java:242) ~[?:?]
        at javax.security.cert.X509Certificate.getInstance(X509Certificate.java:208) ~[?:?]
        at shaded_package.io.netty.handler.ssl.util.LazyJavaxX509Certificate.unwrap(LazyJavaxX509Certificate.java:140) ~[mockserver-netty-no-dependencies-5.15.0.jar:5.15.0]
        ... 66 more

**Comment by ryanzhutao** [comment]
@yqzhan did you find any workaround?

**Comment by baseballyama** [comment]
I think this is fixed by this commit. But it's not included to released version.

https://github.com/mock-server/mockserver/pull/1657/commits/08f51f365162a11204347495302ab522f5f3cf96

**Comment by pavilalopes** [comment]
I'm getting the same error when I try to use client certificates (mTLS)

@baseballyama That commit is not tied to any PR or branch in this repo. How did you find it?

**Comment by baseballyama** [comment]
@pavilalopes 

Ohh I don't remember how to find this commit.
(I think I'd looked for PRs.)

But again I checked commits on master branch and I think this commit could be fix this issue.
https://github.com/mock-server/mockserver/commit/618d937434010c26d0d56169d296c183c0574282

**Comment by pavilalopes** [comment]
I compiled the latest version from git and this bug is indeed fixed.

**Comment by sebagomez** [comment]
Can we get this fix planed for a minor bug fix upgrade please?

**Comment by stukalin** [comment]
Huge +1 here

**Comment by prary** [comment]
> Can we get this fix planed for a minor bug fix upgrade please?

This change is already part of latest master

**Comment by baseballyama** [comment]
> This change is already part of latest master

But not released yet.

**Comment by durcon** [comment]
Is there any relase date for this fix?

**Comment by michael1011101** [comment]
There has been no new update for a long time, is there any alternative method?

**Comment by sebagomez** [comment]
I'm using WireMock right now and it's been great so far

**Comment by michael1011101** [comment]
May I know how to build docker image with latest code?
I tried with following command, but it failed.
```
> cd docker 
> docker build . -t mockserver:local
...
Step 11/24 : COPY mockserver-netty-jar-with-dependencies.jar .
COPY failed: file not found in build context or excluded by .dockerignore: stat mockserver-netty-jar-with-dependencies.jar: file does not exist
```

**Comment by pedrolamarao** [comment]
We have just been hit by this issue. It is very disheartening to find this is a known issue since 2023.

**Comment by palatam** [comment]
+1

**Comment by palatam** [comment]
after hours of research I've found a workaround.

1. create a Delegate for `javax.security.cert.X509Certificate`:

```java
package do_not_use;

import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.math.BigInteger;
import java.security.*;
import java.security.cert.CertificateEncodingException;
import java.security.cert.CertificateException;
import java.security.cert.CertificateFactory;
import java.util.Date;

public class DeprecatedX509Certificate extends javax.security.cert.X509Certificate {

    private final java.security.cert.X509Certificate delegate;

    public DeprecatedX509Certificate(final byte[] data) {
        this(new ByteArrayInputStream(data));
    }

    public DeprecatedX509Certificate(final InputStream inputStream) {
        super();
        this.delegate = load(inputStream);
    }

    private static java.security.cert.X509Certificate load(final InputStream inputStream) {
        try {
            final CertificateFactory certificateFactory = CertificateFactory.getInstance("X.509");
            return (java.security.cert.X509Certificate) certificateFactory.generateCertificate(inputStream);
        } catch (final CertificateException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public void checkValidity() {
    }

    @Override
    public void checkValidity(Date date) {
    }

    @Override
    public int getVersion() {
        return this.delegate.getVersion();
    }

    @Override
    public BigInteger getSerialNumber() {
        return this.delegate.getSerialNumber();
    }

    @Override
    public Principal getIssuerDN() {
        return this.delegate.getIssuerX500Principal();
    }

    @Override
    public Principal getSubjectDN() {
        return this.delegate.getSubjectX500Principal();
    }

    @Override
    public Date getNotBefore() {
        return this.delegate.getNotBefore();
    }

    @Override
    public Date getNotAfter() {
        return this.delegate.getNotAfter();
    }

    @Override
    public String getSigAlgName() {
        return this.delegate.getSigAlgName();
    }

    @Override
    public String getSigAlgOID() {
        return this.delegate.getSigAlgOID();
    }

    @Override
    public byte[] getSigAlgParams() {
        return this.delegate.getSigAlgParams();
    }

    @Override
    public byte[] getEncoded() {
        try {
            return this.delegate.getEncoded();
        } catch (final CertificateEncodingException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public void verify(PublicKey key) throws NoSuchAlgorithmException, InvalidKeyException, NoSuchProviderException, SignatureException {
    }

    @Override
    public void verify(PublicKey key, String sigProvider) throws NoSuchAlgorithmException, InvalidKeyException, NoSuchProviderException, SignatureException {
    }

    @Override
    public String toString() {
        return this.delegate.toString();
    }

    @Override
    public PublicKey getPublicKey() {
        return this.delegate.getPublicKey();
    }
}
```

2. build a JAR with the Delegate so we can add it to the Bootstrap ClassLoader later:

```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <executions>
                    <execution>
                        <id>mockserver</id>
                        <phase>process-test-classes</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                        <configuration>
                            <classesDirectory>${project.build.testOutputDirectory}</classesDirectory>
                            <includes>
                                <include>do_not_use/DeprecatedX509Certificate.class</include>
                            </includes>
                            <outputDirectory>${project.build.directory}/bootclasspath</outputDirectory>
                            <finalName>cert-provider</finalName>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

3. create `src/test/resources/security.properties` to configure our Delegate as default X509 Implementation:

```properties
cert.provider.x509v1=do_not_use.DeprecatedX509Certificate
```

4. configure the JVM to use our Delegate:

```xml
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <configuration>
                    <includes>**/*Test</includes>
                    <argLine>-Xbootclasspath/a:target/bootclasspath -Djava.security.properties=src/test/resources/security.properties</argLine>
                </configuration>
            </plugin>
```

The underlying Netty webserver of MockServer now instantiates our Delegate instead of the dead `com.sun.security.cert.internal.x509.X509V1CertImpl` (tested with JDK21)

**Comment by jamesdbloom** [comment]
Closing — the current code in `JDKCertificateToMockServerX509Certificate` already handles this gracefully. It re-parses certificates using the standard `java.security.cert.CertificateFactory` (avoiding the deprecated `javax.security.cert` path), and wraps the conversion in a `catch (Throwable)` block so any JDK-version-specific failures are logged at INFO level without affecting request processing. The `LazyJavaxX509Certificate` error from the Netty shaded jar would only affect client certificate chain extraction — mocking and proxying still work normally on JDK 17+.
