### ISSUE TITLE
Support BouncyCastle FIPS library 

### ISSUE THREAD

**Issue by artik00** [mock-server/mockserver#1769]
**Describe the feature request**
Currently mockserver uses `bcprov-jdk18on` library, when using a client to communicate with mockserver, which uses`bc-fips` [library](https://www.bouncycastle.org/fips-java/) , it crashes with :
```
2023-07-06 22:43:16 java.lang.NoSuchFieldError: blake3_256
2023-07-06 22:43:16 	at org.bouncycastle.jcajce.provider.digest.Blake3$Mappings.configure(Unknown Source)
2023-07-06 22:43:16 	at org.bouncycastle.jce.provider.BouncyCastleProvider.loadServiceClass(BouncyCastleProvider.java:289)
2023-07-06 22:43:16 	at org.bouncycastle.jce.provider.BouncyCastleProvider.loadAlgorithms(BouncyCastleProvider.java:256)
2023-07-06 22:43:16 	at org.bouncycastle.jce.provider.BouncyCastleProvider.setup(BouncyCastleProvider.java:178)
2023-07-06 22:43:16 	at org.bouncycastle.jce.provider.BouncyCastleProvider.access$000(BouncyCastleProvider.java:68)
2023-07-06 22:43:16 	at org.bouncycastle.jce.provider.BouncyCastleProvider$1.run(BouncyCastleProvider.java:170)
2023-07-06 22:43:16 	at java.base/java.security.AccessController.doPrivileged(Native Method)
2023-07-06 22:43:16 	at org.bouncycastle.jce.provider.BouncyCastleProvider.<init>(BouncyCastleProvider.java:166)
2023-07-06 22:43:16 	at org.mockserver.socket.tls.bouncycastle.BCKeyAndCertificateFactory.<clinit>(BCKeyAndCertificateFactory.java:55)
2023-07-06 22:43:16 	at org.mockserver.socket.tls.KeyAndCertificateFactoryFactory.createKeyAndCertificateFactory(KeyAndCertificateFactoryFactory.java:27)
2023-07-06 22:43:16 	at org.mockserver.socket.tls.NettySslContextFactory.<init>(NettySslContextFactory.java:79)
2023-07-06 22:43:16 	at org.mockserver.client.MockServerClient.getNettyHttpClient(MockServerClient.java:341)
2023-07-06 22:43:16 	at org.mockserver.client.MockServerClient.sendRequest(MockServerClient.java:392)
2023-07-06 22:43:16 	at org.mockserver.client.MockServerClient.sendRequest(MockServerClient.java:428)
2023-07-06 22:43:16 	at org.mockserver.client.MockServerClient.hasStarted(MockServerClient.java:583)
2023-07-06 22:43:16 	at org.mockserver.client.MockServerClient.hasStarted(MockServerClient.java:575)
```

**What you are trying to do**
Currently only using `bcprov-jdk*` libraries work

**The solution you'd like**
An option which library to use wether bc fips certified or regular.

**Describe alternatives you've considered**
No alternative as of now.

Similar [issue](https://github.com/bcgit/bc-java/issues/1287) that was reported.

Thank you!

**Comment by krm1312** [comment]
If you don't need to support TLS/SSL in your tests you can get away with:

```
static {
        KeyAndCertificateFactoryFactory.setCustomKeyAndCertificateFactorySupplier((logger, isServerInstance, configuration) -> null);
}
```

**Comment by mgrundie-r7** [comment]
I'm also running into this issue. ( mockserver-client-java-5.13.2 + bcfips 2.0.0)

```
java.lang.NoSuchFieldError: ecdsa_plain_SHA3_224

	at org.bouncycastle.jcajce.provider.asymmetric.EC$Mappings.configure(Unknown Source)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.loadAlgorithms(BouncyCastleProvider.java:245)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.setup(BouncyCastleProvider.java:171)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.access$000(BouncyCastleProvider.java:58)
	at org.bouncycastle.jce.provider.BouncyCastleProvider$1.run(BouncyCastleProvider.java:153)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at org.bouncycastle.jce.provider.BouncyCastleProvider.<init>(BouncyCastleProvider.java:149)
	at org.mockserver.socket.tls.bouncycastle.BCKeyAndCertificateFactory.<clinit>(BCKeyAndCertificateFactory.java:54)
	at org.mockserver.socket.tls.KeyAndCertificateFactoryFactory.createKeyAndCertificateFactory(KeyAndCertificateFactoryFactory.java:23)
	at org.mockserver.socket.tls.NettySslContextFactory.<init>(NettySslContextFactory.java:72)
	at org.mockserver.client.MockServerClient.getNettyHttpClient(MockServerClient.java:342)
	at org.mockserver.client.MockServerClient.sendRequest(MockServerClient.java:393)
	at org.mockserver.client.MockServerClient.sendRequest(MockServerClient.java:429)
	at org.mockserver.client.MockServerClient.upsert(MockServerClient.java:1494)
	at org.mockserver.client.ForwardChainExpectation.respond(ForwardChainExpectation.java:84)
```

**Comment by jamesdbloom** [comment]
Implemented in commit 8db9093b9. `BCKeyAndCertificateFactory` now uses lazy initialization — the BouncyCastle provider is loaded at first use rather than at class-load time. `KeyAndCertificateFactoryFactory` performs a runtime check for BouncyCastle FIPS (`BCFIPS` provider) and selects it automatically when available. This allows MockServer to work with both standard BouncyCastle and BouncyCastle FIPS libraries.
