### ISSUE TITLE
java.io.FileNotFoundException: /config/Initialiser.json (No such file or directory)

### ISSUE THREAD

**Issue by carellevbt** [mock-server/mockserver#1821]
**Describe the issue**
I am setting up Mockserver using a docker-compose file. I am mounting it to a volume. However, when the container spins up, I get the error " exception while loading JSON initialization file, ignoring file: "/config/InitialiserJson.json" caused by: jaja.io.FileNotFoundException: /config/initialiserJson.json (No such file or directory).

**What you are trying to do**
Bring up mockerserv using docker-compose. File content below

mockServer:
    container_name: mockserver
    image: artifactory/mockserver:5.14.0
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initialiserJson.json
      MOCKSERVER_PERSIST_EXPECTATIONS: "TRUE"
      MOCKSERVER_PERSISTED_EXPECTATIONS_PATH: /config/initialiserJson.json
    volumes:
      - /mockserver/opt/app/mockserver/config:/config
      
**MockServer version**
5.14.0

**To Reproduce**
Steps to reproduce the issue:

1. How you are running MockServer
Using docker

3. Code you used to create expectations - docker-compose
mockServer:
    container_name: mockserver
    image: artifactory/mockserver:5.14.0
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initialiserJson.json
      MOCKSERVER_PERSIST_EXPECTATIONS: "TRUE"
      MOCKSERVER_PERSISTED_EXPECTATIONS_PATH: /config/initialiserJson.json
    volumes:
      - /mockserver/opt/app/mockserver/config:/config

4. What error you saw
java.lang.RuntimeException: Exception while loading "/config/initialiserJson.json"
	at org.mockserver.file.FileReader.readFileFromClassPathOrPath(FileReader.java:37)
	at org.mockserver.server.initialize.ExpectationInitializerLoader.lambda$retrieveExpectationsFromFile$1(ExpectationInitializerLoader.java:137)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:273)
	at java.base/java.util.Collections$2.tryAdvance(Collections.java:4853)
	at java.base/java.util.Collections$2.forEachRemaining(Collections.java:4861)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.mockserver.server.initialize.ExpectationInitializerLoader.retrieveExpectationsFromFile(ExpectationInitializerLoader.java:176)
	at org.mockserver.server.initialize.ExpectationInitializerLoader.retrieveExpectationsFromJson(ExpectationInitializerLoader.java:116)
	at org.mockserver.server.initialize.ExpectationInitializerLoader.addExpectationsFromInitializer(ExpectationInitializerLoader.java:60)
	at org.mockserver.server.initialize.ExpectationInitializerLoader.<init>(ExpectationInitializerLoader.java:43)
	at org.mockserver.mock.HttpState.<init>(HttpState.java:126)
	at org.mockserver.lifecycle.LifeCycle.<init>(LifeCycle.java:55)
	at org.mockserver.netty.MockServer.<init>(MockServer.java:77)
	at org.mockserver.netty.MockServer.<init>(MockServer.java:48)
	at org.mockserver.cli.Main.main(Main.java:149)
Caused by: java.io.FileNotFoundException: /config/initialiserJson.json (No such file or directory)

**Expected behaviour**
No get this error

**MockServer Log**
Log output, as INFO level (or lower)
11-29 22:23:21.314 SERVER_CONFIGURATION   	started on port: 1080
11-29 22:23:21.041 SERVER_CONFIGURATION   	exception while loading JSON initialization file, ignoring file:	"/config/initialiserJson.json"	exception:	
...
11-29 22:23:21.040 SERVER_CONFIGURATION   	loading JSON initialization file:	"/config/initialiserJson.json"
11-29 22:23:21.018 INFO                   	created expectation file system persistence for	"/config/initialiserJson.json"
11-29 22:23:21.017 ERROR                  	exception creating persisted expectations file /config/initialiserJson.json	exception:	
...

**Comment by carellevbt** [comment]
I was able to resolve it
