### ISSUE TITLE
mockserver failed to initialize the server-side SSL context

### ISSUE THREAD

**Issue by viraj-nutanix** [mock-server/mockserver#1833]
**Describe the issue**
Mockserver throwing exceptions in loop when starting it on a linux machine

**What you are trying to do**
I am trying to set expectation for an API

**MockServer version**
mockserver-netty-5.14.0-shaded.jar

**To Reproduce**
Steps to reproduce the issue:

1. Copy mockserver jar file to the machine
2. java -jar mockserver-netty-5.14.0-shaded.jar -serverPort 9440
4. ```
01-23 10:18:16.838 ERROR                  	exception creating SSL context for serverfailed to initialize the server-side SSL context	exception:	
...
01-23 10:18:16.488 INFO                   	loaded CA private key from path	"file:/home/nutanix/viraj-trial/mockserver/mockserver-netty-5.14.0-shaded.jar!/org/mockserver/socket/PKCS8CertificateAuthorityPrivateKey.pem"
01-23 10:18:16.356 INFO                   	loaded CA X509 from path	"file:/home/nutanix/viraj-trial/mockserver/mockserver-netty-5.14.0-shaded.jar!/org/mockserver/socket/CertificateAuthorityCertificate.pem"	containing PEM	
...
01-23 10:17:20.753 SERVER_CONFIGURATION   	started on port: 9440
```

**Expected behaviour**
Mockserver is ready for setting expectation 

**MockServer Log**
```
exception creating SSL context for serverfailed to initialize the server-side SSL context	exception:	
javax.net.ssl.SSLException: failed to initialize the server-side SSL context
	at shaded_package.io.netty.handler.ssl.JdkSslServerContext.newSSLContext(JdkSslServerContext.java:289)
	at shaded_package.io.netty.handler.ssl.JdkSslServerContext.<init>(JdkSslServerContext.java:247)
	at shaded_package.io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:467)
	at shaded_package.io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:606)
	at org.mockserver.socket.tls.NettySslContextFactory.createServerSslContext(NettySslContextFactory.java:218)
	at org.mockserver.socket.tls.SniHandler.lookup(SniHandler.java:46)
	at shaded_package.io.netty.handler.ssl.AbstractSniHandler.lookup(AbstractSniHandler.java:126)
	at shaded_package.io.netty.handler.ssl.SslClientHelloHandler.select(SslClientHelloHandler.java:188)
	at shaded_package.io.netty.handler.ssl.SslClientHelloHandler.decode(SslClientHelloHandler.java:169)
	at shaded_package.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at shaded_package.io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:449)
	at shaded_package.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at shaded_package.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at shaded_package.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at shaded_package.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at shaded_package.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at shaded_package.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at shaded_package.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at shaded_package.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at org.mockserver.netty.unification.PortUnificationHandler.enableTls(PortUnificationHandler.java:216)
	at org.mockserver.netty.unification.PortUnificationHandler.decode(PortUnificationHandler.java:150)
	at shaded_package.io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:510)
	at shaded_package.io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at shaded_package.io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:279)
	at shaded_package.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at shaded_package.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at shaded_package.io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at shaded_package.io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at shaded_package.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at shaded_package.io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at shaded_package.io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at shaded_package.io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at shaded_package.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at shaded_package.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at shaded_package.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at shaded_package.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at shaded_package.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at shaded_package.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.security.KeyStoreException: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_SESSION_READ_ONLY
	at sun.security.pkcs11.P11KeyStore.engineSetEntry(P11KeyStore.java:1110)
	at sun.security.pkcs11.P11KeyStore.engineSetKeyEntry(P11KeyStore.java:455)
	at java.security.KeyStore.setKeyEntry(KeyStore.java:1140)
	at shaded_package.io.netty.handler.ssl.SslContext.buildKeyStore(SslContext.java:1112)
	at shaded_package.io.netty.handler.ssl.SslContext.buildKeyManagerFactory(SslContext.java:1280)
	at shaded_package.io.netty.handler.ssl.JdkSslServerContext.newSSLContext(JdkSslServerContext.java:266)
	... 38 more
Caused by: sun.security.pkcs11.wrapper.PKCS11Exception: CKR_SESSION_READ_ONLY
	at sun.security.pkcs11.wrapper.PKCS11.C_CopyObject(Native Method)
	at sun.security.pkcs11.P11KeyStore.updateP11Pkey(P11KeyStore.java:1523)
	at sun.security.pkcs11.P11KeyStore.storePkey(P11KeyStore.java:1789)
	at sun.security.pkcs11.P11KeyStore.engineSetEntry(P11KeyStore.java:1106)
	... 43 more

```

**Comment by jamesdbloom** [comment]
Closing — this issue was reported against MockServer 5.14.0 on a Debian Linux system with an SSL context initialization failure (`javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty`).

This is a well-known JVM/OS-level issue where the Java trust store is empty or misconfigured — typically caused by:
- Missing or broken `/etc/ssl/certs/java/cacerts` on Debian/Ubuntu
- Docker images based on slim/distroless that don't include the CA certificates package

**This is not a MockServer bug.** The fix is to ensure the JVM's trust store is populated:
```bash
# Debian/Ubuntu
apt-get install -y ca-certificates-java
update-ca-certificates -f
```

MockServer 5.15+ also uses a newer Netty/BoringSSL stack which may handle some edge cases better, but the root cause is OS-level certificate configuration.
