### ISSUE TITLE
Docker Build fail on s390x platform

### ISSUE THREAD

**Issue by chegde20121** [mock-server/mockserver#1887]
I am trying to build docker image from source on s390x platform as there is no official support. I got below errors.

**MockServer Log**
742.5 constituent[44]: file:/root/.m2/wrapper/dists/apache-maven-3.9.0-bin/7u41pcsb933vr4m6u83d7ofakm/apache-maven-3.9.0/lib/maven-resolver-transport-http-1.9.4.jar
742.5 constituent[45]: file:/root/.m2/wrapper/dists/apache-maven-3.9.0-bin/7u41pcsb933vr4m6u83d7ofakm/apache-maven-3.9.0/lib/httpcore-4.4.15.jar
742.5 constituent[46]: file:/root/.m2/wrapper/dists/apache-maven-3.9.0-bin/7u41pcsb933vr4m6u83d7ofakm/apache-maven-3.9.0/lib/maven-resolver-transport-wagon-1.9.4.jar
742.5 constituent[47]: file:/root/.m2/wrapper/dists/apache-maven-3.9.0-bin/7u41pcsb933vr4m6u83d7ofakm/apache-maven-3.9.0/lib/maven-slf4j-provider-3.9.0.jar
742.5 constituent[48]: file:/root/.m2/wrapper/dists/apache-maven-3.9.0-bin/7u41pcsb933vr4m6u83d7ofakm/apache-maven-3.9.0/lib/jansi-2.4.0.jar
742.5 ---------------------------------------------------
742.5 Exception in thread "main" java.lang.reflect.InvocationTargetException
742.5 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
742.5 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
742.5 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
742.5 	at java.lang.reflect.Method.invoke(Method.java:498)
742.5 	at org.apache.maven.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:39)
742.5 	at org.apache.maven.wrapper.WrapperExecutor.execute(WrapperExecutor.java:122)
742.5 	at org.apache.maven.wrapper.MavenWrapperMain.main(MavenWrapperMain.java:61)
742.5 Caused by: java.lang.Error: Error was thrown while processing /mockserver/mockserver-core/src/main/java/org/mockserver/openapi/OpenAPIConverter.java
742.5 	at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:313)
742.5 	at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:224)
742.5 	at org.apache.maven.plugins.checkstyle.exec.DefaultCheckstyleExecutor.executeCheckstyle(DefaultCheckstyleExecutor.java:195)
742.5 	at org.apache.maven.plugins.checkstyle.CheckstyleViolationCheckMojo.execute(CheckstyleViolationCheckMojo.java:545)
742.5 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
742.5 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:342)
742.5 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:330)
742.5 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
742.5 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:175)
742.5 	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:76)
742.5 	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:163)
742.5 	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
742.5 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
742.5 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
742.5 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
742.5 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
742.5 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
742.5 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:260)
742.5 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:172)
742.5 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:100)
742.5 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:821)
742.5 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:270)
742.5 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
742.5 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
742.5 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
742.5 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
742.5 	at java.lang.reflect.Method.invoke(Method.java:498)
742.5 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
742.5 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
742.5 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
742.5 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
742.5 	... 7 more
742.5 Caused by: java.lang.OutOfMemoryError: Java heap space
742.5 	at java.util.HashMap.resize(HashMap.java:705)
742.5 	at java.util.HashMap.putVal(HashMap.java:630)
742.5 	at java.util.HashMap.put(HashMap.java:613)
742.5 	at org.antlr.v4.runtime.misc.DoubleKeyMap.put(DoubleKeyMap.java:31)
742.5 	at org.antlr.v4.runtime.atn.PredictionContext.mergeSingletons(PredictionContext.java:234)
742.5 	at org.antlr.v4.runtime.atn.PredictionContext.merge(PredictionContext.java:155)
742.5 	at org.antlr.v4.runtime.atn.ATNConfigSet.add(ATNConfigSet.java:155)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1529)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closureCheckingStopState(ParserATNSimulator.java:1513)
742.5 	at org.antlr.v4.runtime.atn.ParserATNSimulator.closure_(ParserATNSimulator.java:1586)
------
Dockerfile_s390x:33
--------------------
  32 |     RUN git clone https://github.com/mock-server/mockserver.git
  33 | >>> RUN cd mockserver && \
  34 | >>>     export JAVA_OPTS="-Xmx2g -Xms512m" && \
  35 | >>>     ./mvnw -s /etc/maven/settings.xml dependency:go-offline && \
  36 | >>>     ./mvnw -s /etc/maven/settings.xml package -DskipTests && \
  37 | >>>     cd .. && \
  38 | >>>     rm -rf mockserver
  39 |
--------------------
ERROR: failed to solve: process "/bin/sh -c cd mockserver &&     export JAVA_OPTS=\"-Xmx2g -Xms512m\" &&     ./mvnw -s /etc/maven/settings.xml dependency:go-offline &&     ./mvnw -s /etc/maven/settings.xml package -DskipTests &&     cd .. &&     rm -rf mockserver" did not complete successfully: exit code: 1

can any body help me to understand this and fix this?

**Comment by chegde20121** [comment]
@JakubJablonski2-TomTom @jamesbloomnektan @jamesdbloom @MitchelNijdam-Rockstars

**Comment by chegde20121** [comment]
I appreciate any suggestions that help me to get on to the right track

**Comment by AB-xdev** [comment]
Likely related: https://github.com/mock-server/mockserver/issues/1568

**Comment by jamesdbloom** [comment]
Closing — s390x is not an officially supported platform for MockServer.

MockServer's Docker images are built for `linux/amd64` and `linux/arm64`. The s390x platform is not supported due to:
1. Lack of native Netty/BoringSSL support for s390x
2. Build tooling (checkstyle, etc.) compatibility issues as shown in the error
3. No CI infrastructure for s390x testing

Building from source on s390x would require significant modifications to the build system and native library dependencies. This is tracked separately as a feature request in #1886.
