### ISSUE TITLE
using creating an expectation using an OpenAPI/Swagger spec uses the wrong JSON schema dialect

### ISSUE THREAD

**Issue by fvanderwielen** [mock-server/mockserver#1896]
**Describe the issue**
When creating an expectation using an OpenAPI/Swagger spec, MockServer uses the wrong JSON schema dialect to create the actual expectation out of it.

**What you are trying to do**
create an expectation using an openAPI swagger spec. MockServer (MS) running as a docker container, calling the create expectation endpoint, with inline swagger spec in the request body.

**MockServer version**
The version you are using: 5.15.0

**To Reproduce**
Steps to reproduce the issue:

1. running MockServer as docker container
2. create the expectation from swagger API via curl, for a specific operationID. The operation has a schema for the body, that uses `excludeminimum: true`. This is correct per OpenAPI schema dialect: https://swagger.io/docs/specification/data-models/keywords/
3. perform the request to mockserver
4. Code you used to create expectations: curl. I cannot share the openAPI spec itself, sadly, but as mentioned it has in the schema `excludeminimum: true`.
5. What error you saw: In the log in the control plane UI/dashboard, an error is reported:
`ERROR                     

exception validating JSON

exception:
com.networknt.schema.JsonSchemaException: exclusiveMinimum value is not a number	at com.networknt.schema.ExclusiveMinimumValidator.<init>(ExclusiveMinimumValidator.java:41)	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)	at com.networknt.schema.ValidatorTypeCode.newValidator(ValidatorTypeCode.java:158)	at com.networknt.schema.JsonMetaSchema.newValidator(JsonMetaSchema.java:286)	at com.networknt.schema.ValidationContext.newValidator(ValidationContext.java:57)	at com.networknt.schema.JsonSchema.read(JsonSchema.java:236)	at com.networknt.schema.JsonSchema.getValidators(JsonSchema.java:524)	at com.networknt.schema.JsonSchema.validate(JsonSchema.java:315)	at com.networknt.schema.PropertiesValidator.validate(PropertiesValidator.java:69)	at com.networknt.schema.JsonSchema.validate(JsonSchema.java:316)	at com.networknt.schema.JsonSchema.validate(JsonSchema.java:299)	at org.mockserver.validator.jsonschema.JsonSchemaValidator.isValid(JsonSchemaValidator.java:167)	at org.mockserver.matchers.JsonSchemaMatcher.matches(JsonSchemaMatcher.java:46)	at org.mockserver.matchers.JsonSchemaMatcher.matches(JsonSchemaMatcher.java:16)	at org.mockserver.matchers.HttpRequestPropertiesMatcher.matches(HttpRequestPropertiesMatcher.java:498)	at org.mockserver.matchers.HttpRequestPropertiesMatcher.bodyMatches(HttpRequestPropertiesMatcher.java:476)	at org.mockserver.matchers.HttpRequestPropertiesMatcher.bodyMatches(HttpRequestPropertiesMatcher.java:444)	at org.mockserver.matchers.HttpRequestPropertiesMatcher.matches(HttpRequestPropertiesMatcher.java:290)	at org.mockserver.matchers.HttpRequestPropertiesMatcher.matches(HttpRequestPropertiesMatcher.java:208)	at org.mockserver.matchers.HttpRequestsPropertiesMatcher.matches(HttpRequestsPropertiesMatcher.java:512)	at org.mockserver.mock.RequestMatchers.lambda$firstMatchingExpectation$9(RequestMatchers.java:227)	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
...`

**Expected behaviour**
the request does not generate an error and is matched.

**MockServer Log**
please see above for the logged error.

**Further info**
in search of a proper fix I dived into the code of mockserver. In the end the problem is that the default JSON schema dialect used is incompatible with the JSON schema dialect of OpenAPI:
- in mockserver it is set to V7: https://github.com/mock-server/mockserver/blob/b607ad690543b17a6f6d6ecd92292ca3f28afe0d/mockserver-core/src/main/java/org/mockserver/validator/jsonschema/JsonSchemaValidator.java#L39
- in OpenAPI, a dialect similar to V4/V5 is used: https://swagger.io/docs/specification/data-models/keywords/ it is not exactly the same, as the docs mention, but for the matter of exclusiveMinimum it is more akin to V4: https://swagger.io/docs/specification/data-models/data-types/#range 

building an expectation without OpenAPI spec but with JSONschema directly does allow for setting the schema dialect explicitly, as mentioned in the MS docs on this. But using an OpenAPI spec uses its parser, and $schema is unsupported or otherwise stripped out of when parsing/serializing it, it seems. Because I did try to add $schema to V4 when PUTing the expectation, but see it gone in the expectation shown on the dashboard.

**Comment by rnagulapalle** [comment]
The reporter's diagnosis is correct and I can confirm it from the source. JsonSchemaValidator.getJsonSchemaFactory() does check for a $schema property on the schema node and will select V4 if it finds draft-04 in the value. The problem is that OpenAPI 3.0's Schema Object doesn't include $schema as a valid keyword, so swagger-parser strips it before MockServer ever sees it. That's why manually adding $schema to the PUT body doesn't help — it gets dropped during OpenAPI parsing, and getJsonSchemaFactory falls back to DEFAULT_JSON_SCHEMA_VERSION (V7).

This means the fix probably needs to happen upstream of the validator — wherever MockServer extracts body schemas from parsed OpenAPI specs, it should either inject "$schema": "http://json-schema.org/draft-04/schema#" into the extracted schema node, or pass the dialect as a parameter to JsonSchemaValidator so it can skip the $schema detection fallback. The OpenAPI path always implies draft-04-compatible semantics.

Worth noting this isn't limited to exclusiveMinimum — exclusiveMaximum has the same boolean-to-number change between draft-04 and draft-07, so any spec using exclusiveMaximum: true would hit the same crash.

**Comment by jamesdbloom** [comment]
Fixed in commit 9bc841597. OpenAPI 3.0 uses JSON Schema Draft 4 where `exclusiveMinimum` is a boolean (`true`/`false`), but MockServer's json-schema-validator defaults to Draft-07 where `exclusiveMinimum` must be a number. `AbstractSchemaSerializer` now translates the OAS 3.0 boolean form during schema serialization:

- `"exclusiveMinimum": true` + `"minimum": N` → `"exclusiveMinimum": N` (Draft-07 numeric form)
- `"exclusiveMinimum": false` → removed (no-op)
- Same treatment for `exclusiveMaximum`/`maximum`
