### ISSUE TITLE
Unable to execute MockServerClient

### ISSUE THREAD

**Issue by vali92** [mock-server/mockserver#695]
Hi, I'm trying to run mockserver on a localhosted environemnt this is my code.
 ```java
new MockServerClient("localhost", 4200)
  // this request matcher matches every request
  .when(
    request()
  )
  .respond(
    response()
      .withBody("some_response_body")
  );//some api calls
```

But at execution I have the following errors:

> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.

org.mockserver.client.ClientException: error:

	<!DOCTYPE html>
	<html lang="en">
	<head>
	<meta charset="utf-8">
	<title>Error</title>
	</head>
	<body>
	<pre>Cannot PUT /mockserver/expectation</pre>
	</body>
	</html>

 while submitted expectation:

	{
	  "httpRequest" : { },
	  "times" : {
	    "unlimited" : true
	  },
	  "timeToLive" : {
	    "unlimited" : true
	  },
	  "httpResponse" : {
	    "body" : "some_response_body"
	  }
	}

	at org.mockserver.client.MockServerClient.sendExpectation(MockServerClient.java:656)
	at org.mockserver.client.ForwardChainExpectation.respond(ForwardChainExpectation.java:43)
	at backend.helpers.TestMockServer.Test(TestMockServer.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:73)
	at org.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:123)

I'm using the latest version of mock-server 5.7.2.

Thanks,

**Comment by jamesdbloom** [comment]
The logger configuration output is expected if you don't have a logger binding for the Java logging on the classpath.  This is because I have included the logging binding in Mockserver as follows:
```xml
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-jdk14</artifactId>
    <version>1.7.29</version>
    <optional>true</optional> <!-- do not impose on project importing mock-server -->
</dependency>
```
This means that projects that import MockServer don't get forced to use my logging binding.  However, the flip side to this is that no logs appear unless you already have a logging binding.

To solve this problem please add the following dependency to your pom file (or equivalent to you gradle.build file):

```
<dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-jdk14</artifactId>
    <version>1.7.29</version>
</dependency>
```

I will improve the documentation on the website to make this clearer, see: https://trello.com/c/uQa3BPmM/42-improve-log-configuration-documentation

**Comment by vali92** [comment]
Thanks, that removed the log errors but unfortunately I cannot execute a test the error is the same as above - Cannot PUT /mockserver/expectation. Thanks

**Comment by jamesdbloom** [comment]
MockServer does return XML so I don’t understand how you an XML error response can you provide more details about how you are running MockServer and which version you are using.

**Comment by vali92** [comment]
My bad I figured it out, I was trying to mock localhosted endpoints unfortunately mockserver cannot start on the same port since is already in use. Thanks
