### ISSUE TITLE
Tests compilation is failing with Maven (3.6.3) + Java 11 + MockServer 5.9.0

### ISSUE THREAD

**Issue by aheritier** [mock-server/mockserver#722]
**Describe the issue**
Tests compilation is failing with Maven (3.6.3) + Java 11 + MockServer 5.9.0

```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/share/maven
Java version: 11.0.6, vendor: Oracle Corporation, runtime: /usr/local/openjdk-11
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.9.0-9-amd64", arch: "amd64", family: "unix"
....
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ support-analytics ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 25 source files to /root/workspace/cations_support-analytics_PR-166/target/test-classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  53.831 s
[INFO] Finished at: 2020-02-03T08:21:41Z
[INFO] ------------------------------------------------------------------------
---------------------------------------------------
constituent[0]: file:/usr/share/maven/conf/logging/
constituent[1]: file:/usr/share/maven/lib/maven-settings-3.6.3.jar
constituent[2]: file:/usr/share/maven/lib/maven-resolver-provider-3.6.3.jar
constituent[3]: file:/usr/share/maven/lib/maven-builder-support-3.6.3.jar
constituent[4]: file:/usr/share/maven/lib/plexus-utils-3.2.1.jar
constituent[5]: file:/usr/share/maven/lib/wagon-provider-api-3.3.4.jar
constituent[6]: file:/usr/share/maven/lib/commons-io-2.5.jar
constituent[7]: file:/usr/share/maven/lib/jsr250-api-1.0.jar
constituent[8]: file:/usr/share/maven/lib/org.eclipse.sisu.inject-0.3.4.jar
constituent[9]: file:/usr/share/maven/lib/maven-repository-metadata-3.6.3.jar
constituent[10]: file:/usr/share/maven/lib/maven-core-3.6.3.jar
constituent[11]: file:/usr/share/maven/lib/javax.inject-1.jar
constituent[12]: file:/usr/share/maven/lib/org.eclipse.sisu.plexus-0.3.4.jar
constituent[13]: file:/usr/share/maven/lib/plexus-component-annotations-2.1.0.jar
constituent[14]: file:/usr/share/maven/lib/maven-resolver-connector-basic-1.4.1.jar
constituent[15]: file:/usr/share/maven/lib/maven-resolver-api-1.4.1.jar
constituent[16]: file:/usr/share/maven/lib/maven-resolver-util-1.4.1.jar
constituent[17]: file:/usr/share/maven/lib/maven-plugin-api-3.6.3.jar
constituent[18]: file:/usr/share/maven/lib/cdi-api-1.0.jar
constituent[19]: file:/usr/share/maven/lib/commons-lang3-3.8.1.jar
constituent[20]: file:/usr/share/maven/lib/maven-resolver-impl-1.4.1.jar
constituent[21]: file:/usr/share/maven/lib/plexus-cipher-1.7.jar
constituent[22]: file:/usr/share/maven/lib/maven-artifact-3.6.3.jar
constituent[23]: file:/usr/share/maven/lib/maven-model-builder-3.6.3.jar
constituent[24]: file:/usr/share/maven/lib/plexus-interpolation-1.25.jar
constituent[25]: file:/usr/share/maven/lib/maven-model-3.6.3.jar
constituent[26]: file:/usr/share/maven/lib/commons-cli-1.4.jar
constituent[27]: file:/usr/share/maven/lib/maven-resolver-spi-1.4.1.jar
constituent[28]: file:/usr/share/maven/lib/maven-slf4j-provider-3.6.3.jar
constituent[29]: file:/usr/share/maven/lib/jcl-over-slf4j-1.7.29.jar
constituent[30]: file:/usr/share/maven/lib/jansi-1.17.1.jar
constituent[31]: file:/usr/share/maven/lib/maven-settings-builder-3.6.3.jar
constituent[32]: file:/usr/share/maven/lib/maven-embedder-3.6.3.jar
constituent[33]: file:/usr/share/maven/lib/guice-4.2.1-no_aop.jar
constituent[34]: file:/usr/share/maven/lib/jsoup-1.12.1.jar
constituent[35]: file:/usr/share/maven/lib/maven-resolver-transport-wagon-1.4.1.jar
constituent[36]: file:/usr/share/maven/lib/wagon-file-3.3.4.jar
constituent[37]: file:/usr/share/maven/lib/guava-25.1-android.jar
constituent[38]: file:/usr/share/maven/lib/plexus-sec-dispatcher-1.4.jar
constituent[39]: file:/usr/share/maven/lib/maven-shared-utils-3.2.1.jar
constituent[40]: file:/usr/share/maven/lib/wagon-http-3.3.4-shaded.jar
constituent[41]: file:/usr/share/maven/lib/slf4j-api-1.7.29.jar
constituent[42]: file:/usr/share/maven/lib/maven-compat-3.6.3.jar
---------------------------------------------------
Exception in thread "main" java.lang.AssertionError
	at jdk.compiler/com.sun.tools.javac.util.Assert.error(Assert.java:155)
	at jdk.compiler/com.sun.tools.javac.util.Assert.check(Assert.java:46)
	at jdk.compiler/com.sun.tools.javac.comp.Modules.enter(Modules.java:247)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.readSourceFile(JavaCompiler.java:837)
	at jdk.compiler/com.sun.tools.javac.processing.JavacProcessingEnvironment$ImplicitCompleter.complete(JavacProcessingEnvironment.java:1529)
	at jdk.compiler/com.sun.tools.javac.code.Symbol.complete(Symbol.java:642)
	at jdk.compiler/com.sun.tools.javac.code.Symbol$ClassSymbol.complete(Symbol.java:1326)
	at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.complete(Type.java:1140)
	at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.getTypeArguments(Type.java:1066)
	at jdk.compiler/com.sun.tools.javac.code.Printer.visitClassType(Printer.java:237)
	at jdk.compiler/com.sun.tools.javac.code.Printer.visitClassType(Printer.java:52)
	at jdk.compiler/com.sun.tools.javac.code.Type$ClassType.accept(Type.java:993)
	at jdk.compiler/com.sun.tools.javac.code.Printer.visit(Printer.java:136)
	at jdk.compiler/com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArgument(AbstractDiagnosticFormatter.java:199)
	at jdk.compiler/com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArguments(AbstractDiagnosticFormatter.java:167)
	at jdk.compiler/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:111)
	at jdk.compiler/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:67)
	at jdk.compiler/com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArgument(AbstractDiagnosticFormatter.java:185)
	at jdk.compiler/com.sun.tools.javac.util.AbstractDiagnosticFormatter.formatArguments(AbstractDiagnosticFormatter.java:167)
	at jdk.compiler/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:111)
	at jdk.compiler/com.sun.tools.javac.util.BasicDiagnosticFormatter.formatMessage(BasicDiagnosticFormatter.java:67)
	at jdk.compiler/com.sun.tools.javac.util.JCDiagnostic.getMessage(JCDiagnostic.java:788)
	at jdk.compiler/com.sun.tools.javac.api.ClientCodeWrapper$DiagnosticSourceUnwrapper.getMessage(ClientCodeWrapper.java:799)
	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:131)
	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1134)
	at org.apache.maven.plugin.compiler.TestCompilerMojo.execute(TestCompilerMojo.java:180)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
```

**What you are trying to do**
I have several projects based on spring-boot where I use mock-server in my tests (JUnit 4 or 5) to mock some remote services (classical)
Trying to upgrade MockServer dependency from 3.8.1 to 3.9.0 and the the compilation of tests is failing ...
I can reproduce it on several projects, on my CI environment and on my computer (thus it's not a CI issue - I was afraid of it).

**MockServer version**
The version you are using (i.e. 5.7.2)

**To Reproduce**
Steps to reproduce the issue:

(Not yet sure but ...)

Have a project built with Maven and using `MockServerRule`. Compilation is ok with 5.8.1 but is failing with 5.9.0

**Expected behaviour**

It should compile or the error should be more understandable....

**Comment by aheritier** [comment]
Building in IntelliJ gives an interesting feedback: 

```
Error:(11, 28) java: package org.mockserver.junit does not exist
```

Thus the problem is probably because of this change:

* moved Junit4 to separate module to reduce size of jar-with-dependencies, simplify code and increase build speed

**Comment by aheritier** [comment]
In my code I just have something classical like:

```
  @Rule
  public MockServerRule mockServerRule = new MockServerRule(this, false, MOCK_SERVER_PORT);
```

I am not sure why Maven is failing like this instead of reporting an import not found .... (@hboutemy @rfscholte @Tibor17 did you already see such issue on your side ? Should I report / track it in the maven side ?)

The solution is to replace the dependency `mockserver-netty` by `mockserver-junit-rule`

**Comment by jamesdbloom** [comment]
I hope you found that the MockServerRule was moved to 
```xml
<dependency>
  <groupId>org.mock-server</groupId>
  <artifactId>mockserver-junit-rule</artifactId>
  <version>5.9.0</version>
</dependency>
```

**Comment by aheritier** [comment]
Hi @jamesdbloom 

Yes I found it was the root cause. But I don't understand the crappy compilation failure. I prefered to share my error here if others people are facing it ..

cheers

**Comment by awharkrider** [comment]
I came across this with a google search for "Exception in thread "main" java.lang.AssertionError at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)"

This post led me to figure out that I needed to look at anything todo with junit4 and found that the below dependency was the one that needed to be updated. I hope this helps when anyone else gets this odd output. I updated from 1.3.0 to 1.5.0 https://mvnrepository.com/artifact/com.palantir.docker.compose/docker-compose-rule-junit4/1.5.0

```
<dependency>
    <groupId>com.palantir.docker.compose</groupId>
    <artifactId>docker-compose-rule-junit4</artifactId>
    <version>1.5.0</version>
</dependency>
```

**Comment by pilhuhn** [comment]
I had (just for reference to others and as mockserver is often used with testcontainers) a similar issue today, where it turned out that the `org.jetbrains:annotations:jar:19.0.0:test` package was missing which was coming from testcontainers 1.14 and which is no longer in testcontainers 1.15

**Comment by mjeffrey** [comment]
> I had (just for reference to others and as mockserver is often used with testcontainers) a similar issue today, where it turned out that the `org.jetbrains:annotations:jar:19.0.0:test` package was missing which was coming from testcontainers 1.14 and which is no longer in testcontainers 1.15

Thanks! Just had that and your post saved me a lot of time.
