### ISSUE TITLE
No enum constant org.mockserver.log.model.LogEntry.LogMessageType.ERROR

### ISSUE THREAD

**Issue by dbubenheim** [mock-server/mockserver#736]
**Describe the issue**
We've experienced some outages while using a docker based installation of the _mockserver_. 

Our setup is the following:

- container based architecture using OpenShift
- _mockserver_ is used as a service in this OpenShift project
- _mockserver_ mimics other bounded contexts which we are communicating with in production in our test environment
-  our containers are communicating via http directly with the _mockserver_
- it happens that we receive _502 Bad Gateway_ response from time to time from the _mockserver_ service

**What you are trying to do**
- We are creating some http expectations
- mostly GET responses for our external requests. 
- The _mockserver_ is used to serve with static responses.
- After each end-to-end test we reset the mockserver expectations and create new ones

**MockServer version**
- 5.9.0
- https://hub.docker.com/layers/jamesdbloom/mockserver/mockserver-5.9.0/images/sha256-851023456142c92b342c3d347a495919f6b0e03deed7082ac7f52f3b74cb5469?context=explore

**To Reproduce**
Steps to reproduce the issue:

1. As already mentioned we run mockserver as a docker container inside an OpenShift Cluster
2. Code you used to create expectations: TBD (will be following)
3. Error you saw: _org.mockserver.netty.MockServer handler -> closing pipeline_

**MockServer Log**

```
2020-02-27 16:39:02  org.mockserver.log.MockServerEventLog  SEVERE  exception caught by class org.mockserver.netty.MockServer handler -> closing pipeline [id: 0x16175e7c, L:/*********:1080 - R:/********:50356] 
java.lang.IllegalArgumentException: No enum constant org.mockserver.log.model.LogEntry.LogMessageType.ERROR
	at java.lang.Enum.valueOf(Enum.java:238)
	at org.mockserver.log.model.LogEntry$LogMessageType.valueOf(LogEntry.java:383)
	at org.mockserver.log.model.LogEntry.setLogLevel(LogEntry.java:89)
	at org.mockserver.netty.MockServerHandler.channelRead0(MockServerHandler.java:176)
	at org.mockserver.netty.MockServerHandler.channelRead0(MockServerHandler.java:46)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at org.mockserver.dashboard.DashboardWebSocketServerHandler.channelRead(DashboardWebSocketServerHandler.java:130)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at org.mockserver.callback.CallbackWebSocketServerHandler.channelRead(CallbackWebSocketServerHandler.java:57)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:316)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)
```

It would be really nice to know what happens here and if there is anything we can do to prevent it. 

Thanks in advance!
Daniel

**Comment by jamesdbloom** [comment]
I'm just running the build and will push the fix for this in the next 20 mins

**Comment by jamesdbloom** [comment]
This is now fixed

**Comment by dbubenheim** [comment]
Thanks a lot for fixing it!
