### ISSUE TITLE
MockServer 5.10.0 has read timeout for every request after the first request

### ISSUE THREAD

**Issue by quincy** [mock-server/mockserver#798]
**Describe the issue**
If I try to run multiple requests against the same instance of MockServer, the first request is successful but all subsequent requests time out on read.

**MockServer version**
5.10.0

**To Reproduce**
Here is a minimal test class which reproduces the issue.  This same class passes both tests on earlier versions of MockServer.  I tested it on 5.9.0 and 5.5.1.

```
class MockServerTest {
    companion object {
        private lateinit var mockServer: ClientAndServer

        @BeforeAll
        @JvmStatic
        fun setup() {
            mockServer = startClientAndServer()
        }

        @AfterAll
        @JvmStatic
        fun teardown() {
            mockServer.stop()
        }
    }

    @Test
    fun `make a request`() {
        mockServer
            .`when`(request("/one"))
            .respond(response().withBody("got it").withContentType(MediaType.TEXT_PLAIN))

        val response = URL("http://localhost:${mockServer.localPort}/one")
            .openConnection().apply {
                connectTimeout = 2000
                readTimeout = 2000
                connect()
            }.content as? InputStream
        val actual = response?.bufferedReader()?.readText()

        assertThat(actual, equalTo("got it"))
        mockServer.verify(request("/one"))
    }

    @Test
    fun `make another request`() {
        mockServer
            .`when`(request("/two"))
            .respond(response().withBody("got it again").withContentType(MediaType.TEXT_PLAIN))

        val response: InputStream? = URL("http://localhost:${mockServer.localPort}/two").openConnection().apply {
            connectTimeout = 2000
            readTimeout = 2000
            connect()
        }.content as? InputStream
        val actual = response?.bufferedReader()?.readText()

        assertThat(actual, equalTo("got it again"))
        mockServer.verify(request("/two"))
    }
}
```

1. How you are running MockServer (i.e maven plugin, docker, etc)
I am running with the `mockserver-netty` dependency on Kotlin 1.3.70 using Junit 5.1.0.

2. Code you used to create expectations
See above.

3. What error you saw
```
java.net.SocketTimeoutException: Read timed out

	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.URLConnection.getContent(URLConnection.java:739)
	at com.mycompany.MockServerTest.make a request(MockServerTest.kt:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:532)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:170)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:166)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:113)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:58)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:108)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$4(NodeTestTask.java:112)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:72)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:98)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:74)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
```

**Expected behaviour**
Both tests should pass.

**Comment by jamesdbloom** [comment]
I think your code is not correct and the `teardown` function must be being called prior to the second test running.  

In addition, it is not reasonable to expect that such a massive bug would exist in a library with over 10,000 unit and integration tests that is used across 1,000 of projects, otherwise it wouldn't work for anyone else.

Despite that I have tested an exactly equivalent test written in Java as follows:
```java
package org.mockserver.examples;

import org.junit.AfterClass;
import org.junit.BeforeClass;
import org.junit.Test;
import org.mockserver.integration.ClientAndServer;
import org.mockserver.model.MediaType;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.URL;

import static org.hamcrest.core.Is.is;
import static org.junit.Assert.assertThat;
import static org.junit.Assert.fail;
import static org.mockserver.integration.ClientAndServer.startClientAndServer;
import static org.mockserver.model.HttpRequest.request;
import static org.mockserver.model.HttpResponse.response;

public class MockServerTest {
    private static ClientAndServer mockServer;

    @BeforeClass
    public static void setup() {
        mockServer = startClientAndServer();
    }

    @AfterClass
    public static void teardown() {
        mockServer.stop();
    }

    @Test
    public void makeARequest() throws IOException {
        mockServer
            .when(request("/one"))
            .respond(response().withBody("got it").withContentType(MediaType.TEXT_PLAIN));

        HttpURLConnection urlConnection = (HttpURLConnection) new URL("http://localhost:" + mockServer.getLocalPort() + "/one").openConnection();
        urlConnection.setConnectTimeout(2000);
        urlConnection.setReadTimeout(2000);
        urlConnection.connect();

        if (200 <= urlConnection.getResponseCode() && urlConnection.getResponseCode() <= 399) {
            assertThat(new BufferedReader(new InputStreamReader(urlConnection.getInputStream())).readLine(), is("got it"));
        } else {
            fail("expected 200 response but got " + urlConnection.getResponseCode());
        }

        mockServer.verify(request("/one"));
    }

    @Test
    public void makeAnotherRequest() throws IOException {
        mockServer
            .when(request("/two"))
            .respond(response().withBody("got it again").withContentType(MediaType.TEXT_PLAIN));

        HttpURLConnection urlConnection = (HttpURLConnection) new URL("http://localhost:" + mockServer.getLocalPort() + "/two").openConnection();
        urlConnection.setConnectTimeout(2000);
        urlConnection.setReadTimeout(2000);
        urlConnection.connect();

        if (200 <= urlConnection.getResponseCode() && urlConnection.getResponseCode() <= 399) {
            assertThat(new BufferedReader(new InputStreamReader(urlConnection.getInputStream())).readLine(), is("got it again"));
        } else {
            fail("expected 200 response but got " + urlConnection.getResponseCode());
        }

        mockServer.verify(request("/two"));
    }
}
``

This has no issue and output the following logs:

```bash
2020-07-04 07:23:21 5.10.1-SNAPSHOT org.mockserver.log.MockServerEventLog  INFO  started on port: 61245 
2020-07-04 07:23:22 5.10.1-SNAPSHOT org.mockserver.log.MockServerEventLog  INFO  creating expectation:

  {
    "id" : "083bcfdd-2ee1-4af9-a877-df5ba2183b33",
    "priority" : 0,
    "httpRequest" : {
      "path" : "/two"
    },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpResponse" : {
      "headers" : {
        "content-type" : [ "text/plain" ]
      },
      "body" : "got it again"
    }
  }
 
2020-07-04 07:23:22 5.10.1-SNAPSHOT org.mockserver.log.MockServerEventLog  INFO  received request:

  {
    "method" : "GET",
    "path" : "/two",
    "headers" : {
      "User-Agent" : [ "Java/1.8.0_201" ],
      "Host" : [ "localhost:61245" ],
      "Accept" : [ "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2" ],
      "Connection" : [ "keep-alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  }
 
2020-07-04 07:23:22 5.10.1-SNAPSHOT org.mockserver.log.MockServerEventLog  INFO  request:

  {
    "method" : "GET",
    "path" : "/two",
    "headers" : {
      "User-Agent" : [ "Java/1.8.0_201" ],
      "Host" : [ "localhost:61245" ],
      "Accept" : [ "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2" ],
      "Connection" : [ "keep-alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  }

 matched expectation:

  {
    "id" : "083bcfdd-2ee1-4af9-a877-df5ba2183b33",
    "priority" : 0,
    "httpRequest" : {
      "path" : "/two"
    },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpResponse" : {
      "headers" : {
        "content-type" : [ "text/plain" ]
      },
      "body" : "got it again"
    }
  }
 
2020-07-04 07:23:22 5.10.1-SNAPSHOT org.mockserver.log.MockServerEventLog  INFO  returning response:

  {
    "headers" : {
      "content-type" : [ "text/plain" ]
    },
    "body" : "got it again"
  }

 for request:

  {
    "method" : "GET",
    "path" : "/two",
    "headers" : {
      "User-Agent" : [ "Java/1.8.0_201" ],
      "Host" : [ "localhost:61245" ],
      "Accept" : [ "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2" ],
      "Connection" : [ "keep-alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  }

 for action:

  {
    "headers" : {
      "content-type" : [ "text/plain" ]
    },
    "body" : "got it again"
  }
 
2020-07-04 07:23:22 5.10.1-SNAPSHOT org.mockserver.log.MockServerEventLog  INFO  verifying sequence that match:

  {
    "httpRequests" : [ {
      "path" : "/two"
    } ]
  }
 
2020-07-04 07:23:22 5.10.1-SNAPSHOT org.mockserver.log.MockServerEventLog  INFO  creating expectation:

  {
    "id" : "69ca0ae4-b752-457f-b8b3-9836b831a83c",
    "priority" : 0,
    "httpRequest" : {
      "path" : "/one"
    },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpResponse" : {
      "headers" : {
        "content-type" : [ "text/plain" ]
      },
      "body" : "got it"
    }
  }
 
2020-07-04 07:23:22 5.10.1-SNAPSHOT org.mockserver.log.MockServerEventLog  INFO  received request:

  {
    "method" : "GET",
    "path" : "/one",
    "headers" : {
      "User-Agent" : [ "Java/1.8.0_201" ],
      "Host" : [ "localhost:61245" ],
      "Accept" : [ "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2" ],
      "Connection" : [ "keep-alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  }
 
2020-07-04 07:23:22 5.10.1-SNAPSHOT org.mockserver.log.MockServerEventLog  INFO  request:

  {
    "method" : "GET",
    "path" : "/one",
    "headers" : {
      "User-Agent" : [ "Java/1.8.0_201" ],
      "Host" : [ "localhost:61245" ],
      "Accept" : [ "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2" ],
      "Connection" : [ "keep-alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  }

 didn't match expectation:

  {
    "id" : "083bcfdd-2ee1-4af9-a877-df5ba2183b33",
    "priority" : 0,
    "httpRequest" : {
      "path" : "/two"
    },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpResponse" : {
      "headers" : {
        "content-type" : [ "text/plain" ]
      },
      "body" : "got it again"
    }
  }

 because:

  method matched
  path didn't match
 
2020-07-04 07:23:22 5.10.1-SNAPSHOT org.mockserver.log.MockServerEventLog  INFO  request:

  {
    "method" : "GET",
    "path" : "/one",
    "headers" : {
      "User-Agent" : [ "Java/1.8.0_201" ],
      "Host" : [ "localhost:61245" ],
      "Accept" : [ "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2" ],
      "Connection" : [ "keep-alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  }

 matched expectation:

  {
    "id" : "69ca0ae4-b752-457f-b8b3-9836b831a83c",
    "priority" : 0,
    "httpRequest" : {
      "path" : "/one"
    },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpResponse" : {
      "headers" : {
        "content-type" : [ "text/plain" ]
      },
      "body" : "got it"
    }
  }
 
2020-07-04 07:23:22 5.10.1-SNAPSHOT org.mockserver.log.MockServerEventLog  INFO  returning response:

  {
    "headers" : {
      "content-type" : [ "text/plain" ]
    },
    "body" : "got it"
  }

 for request:

  {
    "method" : "GET",
    "path" : "/one",
    "headers" : {
      "User-Agent" : [ "Java/1.8.0_201" ],
      "Host" : [ "localhost:61245" ],
      "Accept" : [ "text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2" ],
      "Connection" : [ "keep-alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  }

 for action:

  {
    "headers" : {
      "content-type" : [ "text/plain" ]
    },
    "body" : "got it"
  }
 
2020-07-04 07:23:22 5.10.1-SNAPSHOT org.mockserver.log.MockServerEventLog  INFO  verifying sequence that match:

  {
    "httpRequests" : [ {
      "path" : "/one"
    } ]
  }
```

**Comment by quincy** [comment]
Thank you @jamesdbloom for looking at this.  I copied your test class into my project with a couple of changes.  As written it was using Junit 4, which I don't have on my classpath.  I changed it to use Junit 5.  The test fails when run with MockServer `5.10.0` but not with earlier versions.

I copied both my test and yours (with Junit 4 and Junit 5 versions) into a brand new project, and all three pass without issue.  So it seems there is something more interacting with this then I originally thought.  I agree with you that the MockServer must be getting shutdown sometime between the first interaction and the second.

I will continue to look into what else might be interacting with the test.

I appreciate you taking the time to investigate the issue for me.  I have used and promoted MockServer for at least the past three years.  I would like to leave you with a thought regarding your comment:

> In addition, it is not reasonable to expect that such a massive bug would exist in a library with over 10,000 unit and integration tests that is used across 1,000 of projects, otherwise it wouldn't work for anyone else.

I find this dismissive and somewhat defensive.  By submitting my issue I was reaching out for help.  For the first time in three years I was having a problem trying to use the project, and the behavior I was seeing was both reproducible and unexpected.  I did my best to produce a well-written issue describing the trouble I was having.  In response, I was told that I was being unreasonable.  That doesn't feel like the way to [build a strong community](https://docs.github.com/en/github/site-policy/github-community-guidelines#building-a-strong-community).

**Comment by jamesdbloom** [comment]
I agree that my comment was too strong and I'm sorry if you felt patronised.  I do, however, get a lot of people asking basic questions that less than 2 minutes of reading the documentation or investigation would resolve.  Prior to responding to your issues I had already had two people aggressively complaining about things as if I'm getting paid to work on this open source project.  Normally I'm very calm in my responses.  However, the title of this issue is worded in an overly strong way and therefore lead me to assume the person who submitted the issue was angry at the time that they wrote the issue and likely hadn't done their homework.

**Comment by quincy** [comment]
Thank you @jamesdbloom.  I intended my title to just be a description of what I was experiencing.  I'll keep that in mind the next time I open an issue somewhere.  Communication is hard.  You've really built a fantastic project, and I do recommend it to others whenever I can.

**Comment by jamesdbloom** [comment]
Thank you and I'm sorry if I was rude as I do want to build a strong community.
