### ISSUE TITLE
ERROR [MockServer-EventLog0] MockServerEventLog:104 - web socket server caught exception

### ISSUE THREAD

**Issue by sai28593** [mock-server/mockserver#817]
Getting web socket error while running tests.

Error:
java.lang.NoSuchMethodError: org.apache.commons.lang3.builder.EqualsBuilder.setExcludeFields([Ljava/lang/String;)Lorg/apache/commons/lang3/builder/EqualsBuilder;
	at org.mockserver.model.ObjectWithReflectiveEqualsHashCodeToString.equals(ObjectWithReflectiveEqualsHashCodeToString.java:34)
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:940)
	at org.mockserver.netty.unification.PortUnificationHandler.getLocalAddresses(PortUnificationHandler.java:304)
	at org.mockserver.netty.unification.PortUnificationHandler.switchToHttp(PortUnificationHandler.java:255)
	at org.mockserver.netty.unification.PortUnificationHandler.decode(PortUnificationHandler.java:138)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
	at io.netty.handler.codec.ReplayingDecoder.callDecode(ReplayingDecoder.java:366)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.lang.Thread.run(Thread.java:748)
2020-07-20 14:38:49 DEBUG [main] wire:87 - http-outgoing-0 << "[read] I/O error: Connection reset"
2020-07-20 14:38:49 DEBUG [main] DefaultManagedHttpClientConnection:79 - http-outgoing-0: Close connection
2020-07-20 14:38:49 DEBUG [main] DefaultManagedHttpClientConnection:96 - http-outgoing-0: Shutdown connection
2020-07-20 14:38:49 DEBUG [main] MainClientExec:129 - Connection discarded
2020-07-20 14:38:49 DEBUG [main] PoolingHttpClientConnectionManager:326 - Connection released: [id: 0][route: {}->http://localhost:53499][total kept alive: 0; route allocated: 0 of 2; total allocated: 0 of 20]
2020-07-20 14:38:49 ERROR [main] castar-batch-query:127 - Exception while calling Castar-Spark : SERVER_ERROR, EXCEPTION =  java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.conn.LoggingInputStream.read(LoggingInputStream.java:84)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)

code: 
`  fun `test generate sql audit report success`(){
        setup(
                "POST",
                "/jobs",
                200,
                "{\n" +
                        "  \"status\":\"SUBMITTED\"\n"+
                        "}",
                1
        )
       ....
    }`
`private fun setup(requestMethod:String,
                       requestPath:String,
                       responseStatus: Int,
                       responseBody:String,
                      time: Int) {

        mockServer.`when`(
                request()
                        .withMethod(requestMethod)
                        .withPath(requestPath)
                        .withQueryStringParameters(
                                param("appName","......"),
                                param("classPath","......")
                        )
        , Times.exactly(time)

        )
                .respond(
                        response()
                                .withStatusCode(responseStatus)
                                .withBody(responseBody)
                )
    }`

**Comment by jamesdbloom** [comment]
This is because your project has a dependancy (potentially transitive) on a with an old version of `org.apache.commons.lang3.builder.EqualsBuilder` in in.  This method in the error above was available since version 3.6 (release 09-Jun-2017), please update this dependency to make this error go away. Or run MockServer in a [different way](https://mock-server.com/mock_server/running_mock_server.html) such as Docker container, maven plugin, etc

To understand where your dependency problem is use one of the follow commands:

### maven wrapper

```bash
./mvnw dependency:tree
```

### maven

```bash
mvn dependency:tree
```

### gradle wrapper

```bash
./gradlew -q dependencies
```

### gradle

```bash
gradle -q dependencies
```
