### ISSUE TITLE
Headers matching not working correctly

### ISSUE THREAD

**Issue by tvcsantos** [mock-server/mockserver#821]
**Describe the issue**
Headers matching behaviour changed from 5.10 to 5.11.0+ and is not working as it should.

**What you are trying to do**
A simple scenario with an expectation that matches if a header is missing.

**MockServer version**
`>= 5.11.0`

**To Reproduce**

src/main/kotlin/org/example/Hello.kt

```kotlin
package org.example

import com.fasterxml.jackson.module.kotlin.jacksonObjectMapper
import org.mockserver.integration.ClientAndServer
import org.mockserver.model.*
import java.util.*

object Example {

    private val base64Encoder = Base64.getEncoder()

    private val objectMapper = jacksonObjectMapper()

    private const val AUTHORIZATION = "Authorization"
    const val HELLO_PATH = "/hello"

    fun init() {
        val mockServer = ClientAndServer.startClientAndServer(5000)

        configureMissingHelloAuthorization(mockServer)

        configureAuthorized(
            "admin_id",
            "admin_secret",
            mockServer
        )
    }

    private fun configureMissingHelloAuthorization(mockServer: ClientAndServer) {
        mockServer.`when`(
            HttpRequest.request()
                .withMethod("GET")
                .withPath(HELLO_PATH)
                .withHeaders(
                    Header.header(NottableString.not(AUTHORIZATION))
                )
        ).respond(
            HttpResponse.response()
                .withStatusCode(HttpStatusCode.BAD_REQUEST_400.code())
                .withContentType(MediaType.APPLICATION_JSON_UTF_8)
                .withBody(
                    objectMapper.writeValueAsString(object {
                        val error = "invalid_request"
                        val error_description = "missing authorization header"
                    })
                )
        )
    }

    private fun configureAuthorized(
        clientId: String,
        clientSecret: String,
        mockServer: ClientAndServer
    ) {
        val credentials = "${clientId}:${clientSecret}"
        val auth = base64Encoder.encodeToString(credentials.toByteArray())

        mockServer.`when`(
            HttpRequest.request()
                .withMethod("GET")
                .withPath(HELLO_PATH)
                .withHeaders(
                    Header.header(AUTHORIZATION, "^Basic $auth")
                )
        ).respond(
            HttpResponse.response()
                .withStatusCode(HttpStatusCode.OK_200.code())
                .withContentType(MediaType.APPLICATION_JSON_UTF_8)
                .withBody(
                    objectMapper.writeValueAsString(
                        object {
                            val message = "Hello World!"
                        }
                    )
                )
        )
    }
}

fun main(args: Array<String>) {
    println("Hello, World")

    Example.init()
}
```

src/test/kotlin/org/example/HelloTest.kt

```kotlin
package org.example

import io.restassured.module.kotlin.extensions.Given
import io.restassured.module.kotlin.extensions.Then
import io.restassured.module.kotlin.extensions.When
import org.example.Example.HELLO_PATH
import org.junit.BeforeClass
import org.junit.Test

class HelloTest {

    companion object {
        @JvmStatic
        @BeforeClass
        fun setupClass() {
            Example.init()
        }
    }

    @Test
    fun testHeaderMatch() {
        Given {
            auth().preemptive().basic("admin_id", "admin_secret")
            baseUri("http://localhost:5000")
        } When {
            log().all()
            get(HELLO_PATH)
        } Then {
            statusCode(200)
        }
    }
}
```

<details>
<summary>pom.xml</summary>

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>mock-server-test</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>org.example mock-server-test</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <kotlin.version>1.3.72</kotlin.version>
        <kotlin.code.style>official</kotlin.code.style>
        <junit.version>4.12</junit.version>

        <mockserver.version>5.11.1</mockserver.version>
        <jackson-module-kotlin.version>2.11.1</jackson-module-kotlin.version>
        <rest-assured.version>4.3.1</rest-assured.version>
        <groovy.version>3.0.2</groovy.version>
        <slf4j.version>1.7.30</slf4j.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
            <version>${kotlin.version}</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-test-junit</artifactId>
            <version>${kotlin.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.mock-server</groupId>
            <artifactId>mockserver-netty</artifactId>
            <version>${mockserver.version}</version>
        </dependency>

        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-kotlin</artifactId>
            <version>${jackson-module-kotlin.version}</version>
        </dependency>

        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>kotlin-extensions</artifactId>
            <version>${rest-assured.version}</version>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>${slf4j.version}</version>
        </dependency>
    </dependencies>

    <build>
        <sourceDirectory>src/main/kotlin</sourceDirectory>
        <testSourceDirectory>src/test/kotlin</testSourceDirectory>

        <plugins>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>${kotlin.version}</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <phase>test-compile</phase>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
```
</details>

If you run the tests above with

```
mvn clean test
```

they are failing on versions `>= 5.11.0`

**Expected behaviour**

The test is failing because it is matching the expectaction that should only match if we don't have an "Authorization" header in our request.

The expected behaviour would be the mock-server to match the correct expectation that requires the "Authorization" header, and hence the tests will succeed as expected. This was working on version `5.10`.

**MockServer Log**

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.example.HelloTest
[MockServer-EventLog0] INFO org.mockserver.log.MockServerEventLog - 5000 started on port: 5000
Loading JavaScript to validate ECMA262 regular expression in JsonSchema because java.util.regex package in Java does not match ECMA262
Warning: Nashorn engine is planned to be removed from a future JDK release
[MockServer-EventLog0] INFO org.mockserver.log.MockServerEventLog - 5000 creating expectation:

  {
    "id" : "21dc5f7e-d737-4fb4-a94b-b587cf7f9a0e",
    "priority" : 0,
    "httpRequest" : {
      "method" : "GET",
      "path" : "/hello",
      "headers" : {
        "!Authorization" : [ ".*" ]
      }
    },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpResponse" : {
      "statusCode" : 400,
      "headers" : {
        "content-type" : [ "application/json; charset=utf-8" ]
      },
      "body" : "{\"error\":\"invalid_request\",\"error_description\":\"missing authorization header\"}"
    }
  }

 with id:

  21dc5f7e-d737-4fb4-a94b-b587cf7f9a0e

[MockServer-EventLog0] INFO org.mockserver.log.MockServerEventLog - 5000 creating expectation:

  {
    "id" : "0bf2b947-cfc7-4ac8-9005-0d808de24ebf",
    "priority" : 0,
    "httpRequest" : {
      "method" : "GET",
      "path" : "/hello",
      "headers" : {
        "Authorization" : [ "^Basic YWRtaW5faWQ6YWRtaW5fc2VjcmV0" ]
      }
    },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpResponse" : {
      "statusCode" : 200,
      "headers" : {
        "content-type" : [ "application/json; charset=utf-8" ]
      },
      "body" : "{\"message\":\"Hello World!\"}"
    }
  }

 with id:

  0bf2b947-cfc7-4ac8-9005-0d808de24ebf

Request method: GET
Request URI:    http://localhost:5000/hello
Proxy:                  <none>
Request params: <none>
Query params:   <none>
Form params:    <none>
Path params:    <none>
Headers:                Authorization=Basic YWRtaW5faWQ6YWRtaW5fc2VjcmV0
                                Accept=*/*
Cookies:                <none>
Multiparts:             <none>
Body:                   <none>
[MockServer-EventLog0] INFO org.mockserver.log.MockServerEventLog - 5000 received request:

  {
    "method" : "GET",
    "path" : "/hello",
    "headers" : {
      "Authorization" : [ "Basic YWRtaW5faWQ6YWRtaW5fc2VjcmV0" ],
      "Accept" : [ "*/*" ],
      "Host" : [ "localhost:5000" ],
      "Connection" : [ "Keep-Alive" ],
      "User-Agent" : [ "Apache-HttpClient/4.5.3 (Java/11.0.8)" ],
      "Accept-Encoding" : [ "gzip,deflate" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  }

[MockServer-EventLog0] INFO org.mockserver.log.MockServerEventLog - 5000 request:

  {
    "method" : "GET",
    "path" : "/hello",
    "headers" : {
      "Authorization" : [ "Basic YWRtaW5faWQ6YWRtaW5fc2VjcmV0" ],
      "Accept" : [ "*/*" ],
      "Host" : [ "localhost:5000" ],
      "Connection" : [ "Keep-Alive" ],
      "User-Agent" : [ "Apache-HttpClient/4.5.3 (Java/11.0.8)" ],
      "Accept-Encoding" : [ "gzip,deflate" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  }

 matched expectation:

  {
    "id" : "21dc5f7e-d737-4fb4-a94b-b587cf7f9a0e",
    "priority" : 0,
    "httpRequest" : {
      "method" : "GET",
      "path" : "/hello",
      "headers" : {
        "!Authorization" : [ ".*" ]
      }
    },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpResponse" : {
      "statusCode" : 400,
      "headers" : {
        "content-type" : [ "application/json; charset=utf-8" ]
      },
      "body" : "{\"error\":\"invalid_request\",\"error_description\":\"missing authorization header\"}"
    }
  }

[MockServer-EventLog0] INFO org.mockserver.log.MockServerEventLog - 5000 returning response:

  {
    "statusCode" : 400,
    "headers" : {
      "content-type" : [ "application/json; charset=utf-8" ]
    },
    "body" : "{\"error\":\"invalid_request\",\"error_description\":\"missing authorization header\"}"
  }

 for request:

  {
    "method" : "GET",
    "path" : "/hello",
    "headers" : {
      "Authorization" : [ "Basic YWRtaW5faWQ6YWRtaW5fc2VjcmV0" ],
      "Accept" : [ "*/*" ],
      "Host" : [ "localhost:5000" ],
      "Connection" : [ "Keep-Alive" ],
      "User-Agent" : [ "Apache-HttpClient/4.5.3 (Java/11.0.8)" ],
      "Accept-Encoding" : [ "gzip,deflate" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : false
  }

 for action:

  {
    "statusCode" : 400,
    "headers" : {
      "content-type" : [ "application/json; charset=utf-8" ]
    },
    "body" : "{\"error\":\"invalid_request\",\"error_description\":\"missing authorization header\"}"
  }

 from expectation:

  21dc5f7e-d737-4fb4-a94b-b587cf7f9a0e

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.ReflectionUtils (file:/Users/santotia/.m2/repository/org/codehaus/groovy/groovy/3.0.3/groovy-3.0.3.jar) to constructor java.lang.AssertionError(java.lang.String)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.745 sec <<< FAILURE!
testHeaderMatch(org.example.HelloTest)  Time elapsed: 1.531 sec  <<< FAILURE!
java.lang.AssertionError: 1 expectation failed.
Expected status code <200> but was <400>.

        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:72)
        at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:59)
        at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:263)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:277)
        at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:493)
        at io.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$1.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at io.restassured.internal.ResponseSpecificationImpl.forceValidateResponse(ResponseSpecificationImpl.groovy:660)
        at io.restassured.module.kotlin.extensions.RestAssuredKotlinExtensionsKt$Then$2.invoke(RestAssuredKotlinExtensions.kt:61)
        at io.restassured.module.kotlin.extensions.RestAssuredKotlinExtensionsKt$Then$2.invoke(RestAssuredKotlinExtensions.kt)
        at io.restassured.module.kotlin.extensions.RestAssuredKotlinExtensionsKt$doIfValidatableResponseImpl$1.invoke(RestAssuredKotlinExtensions.kt:80)
        at io.restassured.module.kotlin.extensions.RestAssuredKotlinExtensionsKt$doIfValidatableResponseImpl$1.invoke(RestAssuredKotlinExtensions.kt)
        at io.restassured.module.kotlin.extensions.RestAssuredKotlinExtensionsKt.Then(RestAssuredKotlinExtensions.kt:60)
        at org.example.HelloTest.testHeaderMatch(HelloTest.kt:28)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)


Results :

Failed tests:   testHeaderMatch(org.example.HelloTest): 1 expectation failed.(..)

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```

**Comments**
If you have any further questions or if you need something please ask :).

Thanks for this awesome project 👍

**Comment by jamesdbloom** [comment]
This was working before due to the excessively complex way that matching was implemented which is no longer possible to maintain because support for things like schemas and optional values was added to enable OpenAPI support.  The matching now matches if there is a header with not the header name you specified.  Therefore if you have other headers the matcher will match.  I understand this is not ideal and is a breaking changing in the way the matching works.

I could look at implementing support for notted header values to mean no header exist with that name.  That would solve this issue.

**Comment by jamesdbloom** [comment]
This is now fixed and the fix is in the last SNAPSHOT.  It'll be released in the next release likely in 1-2 months.

**Comment by tvcsantos** [comment]
Hey @jamesdbloom thanks for the update and quick fix 👍
