### ISSUE TITLE
HTTPS traffic does not pass through the server

### ISSUE THREAD

**Issue by StanislavSelen** [mock-server/mockserver#822]
**Describe the issue**
HTTPS traffic does not pass through the server

**What you are trying to do**
I want to go to https://www.google.com/ in the browser using the mock server.

**MockServer version**
5.11.1

1. Using selenide (https://github.com/selenide/selenide), create a browser instance:
`WebDriver driver;`

2. Create a proxy server:
```
System.setProperty("javax.net.ssl.trustStore", "src/test/resources/certs/cacerts");
System.setProperty("javax.net.ssl.keyStore", "src/test/resources/certs/keystore.jks");
System.setProperty("javax.net.ssl.keyStorePassword", "changeit");
System.setProperty("javax.net.ssl.trustStorePassword", "changeit");

HttpsURLConnection.setDefaultSSLSocketFactory(new KeyStoreFactory(new MockServerLogger()).SslContext(). GetSocketFactory());

ConfigurationProperties.maxSocketTimeout(120000);
ConfigurationProperties.dynamicallyCreateCertificateAuthorityCertificate(true);
ConfigurationProperties.directoryToSaveDynamicSSLCertificate("src/test/resources/certs/");
ConfigurationProperties.sslCertificateDomainName("localhost.local");
ConfigurationProperties.addSslSubjectAlternativeNameDomains("www.example.com");
ConfigurationProperties.addSslSubjectAlternativeNameIps("127.0.0.1");
ConfigurationProperties.enableCORSForAPI(true);
ConfigurationProperties.enableCORSForAllResponses(true);
ConfigurationProperties.nioEventLoopThreadCount(500);
ConfigurationProperties.forwardProxyTLSX509CertificatesTrustManagerType("ANY");
ConfigurationProperties.forwardHttpsProxy();
ConfigurationProperties.forwardHttpProxy();

ClientAndServer mockServer = startClientAndServer();
mockServer.withSecure(true);
```
 
3. Install mockserver as a proxy:
```
String PROXY = "localhost:" + mockServer.getLocalPort();
Proxy seleniumProxy = new Proxy();
seleniumProxy.setHttpProxy(PROXY).setSslProxy(PROXY);
ChromeOptions options = new ChromeOptions();
options.setCapability(CapabilityType.PROXY, seleniumProxy);
driver = new ChromeDriver(options);
```

4. Go to google site:
`driver.open("https://google.com");`

**Expected behaviour**
The google site loaded without issue.

**MockServer Log**
The google site is not loading.
Log:
```
javax.net.ssl|DEBUG|01|main|2020-07-31 11:50:51.430 MSK|SSLCipher.java:465|jdk.tls.keyLimits:  entry = AES/GCM/NoPadding KeyUpdate 2^37. AES/GCM/NOPADDING:KEYUPDATE = 137438953472
javax.net.ssl|ALL|1B|MockServer-MockServer-workerEventLoop5|2020-07-31 11:50:53.111 MSK|X509Authentication.java:295|No X.509 cert selected for EC
javax.net.ssl|ALL|1B|MockServer-MockServer-workerEventLoop5|2020-07-31 11:50:53.112 MSK|X509Authentication.java:295|No X.509 cert selected for EC
Loading JavaScript to validate ECMA262 regular expression in JsonSchema because java.util.regex package in Java does not match ECMA262
javax.net.ssl|ALL|1A|MockServer-ClientAndServer-eventLoop4|2020-07-31 11:50:53.575 MSK|SSLEngineImpl.java:818|Closing outbound of SSLEngine
javax.net.ssl|WARNING|1A|MockServer-ClientAndServer-eventLoop4|2020-07-31 11:50:53.577 MSK|SSLEngineOutputRecord.java:173|outbound has closed, ignore outbound application data
javax.net.ssl|DEBUG|1B|MockServer-MockServer-workerEventLoop5|2020-07-31 11:50:53.578 MSK|Alert.java:238|Received alert message(
"Alert": {
  "level"      : "warning",
  "description": "close_notify"
}
)
javax.net.ssl|WARNING|1B|MockServer-MockServer-workerEventLoop5|2020-07-31 11:50:53.579 MSK|SSLEngineOutputRecord.java:173|outbound has closed, ignore outbound application data
javax.net.ssl|DEBUG|03|Finalizer|2020-07-31 11:50:53.679 MSK|SSLSocketImpl.java:550|duplex close of SSLSocket
javax.net.ssl|WARNING|03|Finalizer|2020-07-31 11:50:53.680 MSK|SSLSocketImpl.java:571|SSLSocket duplex close failed(
"throwable" : {
  java.net.SocketException: Socket is not connected
    at java.base/java.net.Socket.shutdownOutput(Socket.java:1607)
    at java.base/sun.security.ssl.BaseSSLSocketImpl.shutdownOutput(BaseSSLSocketImpl.java:232)
    at java.base/sun.security.ssl.SSLSocketImpl.handleClosedNotifyAlert(SSLSocketImpl.java:716)
    at java.base/sun.security.ssl.SSLSocketImpl.duplexCloseOutput(SSLSocketImpl.java:688)
    at java.base/sun.security.ssl.SSLSocketImpl.close(SSLSocketImpl.java:556)
    at java.base/sun.security.ssl.BaseSSLSocketImpl.finalize(BaseSSLSocketImpl.java:275)
    at java.base/java.lang.System$2.invokeFinalize(System.java:2190)
    at java.base/java.lang.ref.Finalizer.runFinalizer(Finalizer.java:87)
    at java.base/java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:171)}

)
javax.net.ssl|ALL|27|MockServer-ClientAndServer-eventLoop8|2020-07-31 11:50:53.703 MSK|SSLEngineImpl.java:818|Closing outbound of SSLEngine
javax.net.ssl|WARNING|27|MockServer-ClientAndServer-eventLoop8|2020-07-31 11:50:53.704 MSK|SSLEngineOutputRecord.java:173|outbound has closed, ignore outbound application data
javax.net.ssl|DEBUG|28|MockServer-MockServer-workerEventLoop9|2020-07-31 11:50:53.706 MSK|Alert.java:238|Received alert message(
"Alert": {
  "level"      : "warning",
  "description": "close_notify"
}
)
javax.net.ssl|WARNING|28|MockServer-MockServer-workerEventLoop9|2020-07-31 11:50:53.707 MSK|SSLEngineOutputRecord.java:173|outbound has closed, ignore outbound application data
javax.net.ssl|ALL|2B|MockServer-ClientAndServer-eventLoop12|2020-07-31 11:50:53.781 MSK|SSLEngineImpl.java:818|Closing outbound of SSLEngine
javax.net.ssl|WARNING|2B|MockServer-ClientAndServer-eventLoop12|2020-07-31 11:50:53.781 MSK|SSLEngineOutputRecord.java:173|outbound has closed, ignore outbound application data
javax.net.ssl|DEBUG|2C|MockServer-MockServer-workerEventLoop13|2020-07-31 11:50:53.782 MSK|Alert.java:238|Received alert message(
"Alert": {
  "level"      : "warning",
  "description": "close_notify"
}
)
javax.net.ssl|WARNING|2C|MockServer-MockServer-workerEventLoop13|2020-07-31 11:50:53.783 MSK|SSLEngineOutputRecord.java:173|outbound has closed, ignore outbound application data
javax.net.ssl|ALL|2F|MockServer-ClientAndServer-eventLoop16|2020-07-31 11:50:53.846 MSK|SSLEngineImpl.java:818|Closing outbound of SSLEngine
javax.net.ssl|WARNING|2F|MockServer-ClientAndServer-eventLoop16|2020-07-31 11:50:53.847 MSK|SSLEngineOutputRecord.java:173|outbound has closed, ignore outbound application data
javax.net.ssl|DEBUG|30|MockServer-MockServer-workerEventLoop17|2020-07-31 11:50:53.848 MSK|Alert.java:238|Received alert message(
"Alert": {
  "level"      : "warning",
  "description": "close_notify"
}
)
javax.net.ssl|WARNING|30|MockServer-MockServer-workerEventLoop17|2020-07-31 11:50:53.848 MSK|SSLEngineOutputRecord.java:173|outbound has closed, ignore outbound application data
javax.net.ssl|ALL|33|MockServer-ClientAndServer-eventLoop20|2020-07-31 11:50:53.911 MSK|SSLEngineImpl.java:818|Closing outbound of SSLEngine
javax.net.ssl|WARNING|33|MockServer-ClientAndServer-eventLoop20|2020-07-31 11:50:53.912 MSK|SSLEngineOutputRecord.java:173|outbound has closed, ignore outbound application data
javax.net.ssl|DEBUG|34|MockServer-MockServer-workerEventLoop21|2020-07-31 11:50:53.913 MSK|Alert.java:238|Received alert message(
"Alert": {
  "level"      : "warning",
  "description": "close_notify"
}
)
javax.net.ssl|WARNING|34|MockServer-MockServer-workerEventLoop21|2020-07-31 11:50:53.913 MSK|SSLEngineOutputRecord.java:173|outbound has closed, ignore outbound application data
javax.net.ssl|ALL|1A|MockServer-ClientAndServer-eventLoop4|2020-07-31 11:50:53.954 MSK|SSLEngineImpl.java:818|Closing outbound of SSLEngine
javax.net.ssl|WARNING|1A|MockServer-ClientAndServer-eventLoop4|2020-07-31 11:50:53.955 MSK|SSLEngineOutputRecord.java:173|outbound has closed, ignore outbound application data
javax.net.ssl|DEBUG|37|MockServer-MockServer-workerEventLoop24|2020-07-31 11:50:53.956 MSK|Alert.java:238|Received alert message(
"Alert": {
  "level"      : "warning",
  "description": "close_notify"
}
)
javax.net.ssl|WARNING|37|MockServer-MockServer-workerEventLoop24|2020-07-31 11:50:53.956 MSK|SSLEngineOutputRecord.java:173|outbound has closed, ignore outbound application data
javax.net.ssl|ALL|27|MockServer-ClientAndServer-eventLoop8|2020-07-31 11:50:53.999 MSK|SSLEngineImpl.java:818|Closing outbound of SSLEngine
javax.net.ssl|WARNING|27|MockServer-ClientAndServer-eventLoop8|2020-07-31 11:50:53.999 MSK|SSLEngineOutputRecord.java:173|outbound has closed, ignore outbound application data
javax.net.ssl|DEBUG|39|MockServer-MockServer-workerEventLoop26|2020-07-31 11:50:54.001 MSK|Alert.java:238|Received alert message(
"Alert": {
  "level"      : "warning",
  "description": "close_notify"
}
)
javax.net.ssl|WARNING|39|MockServer-MockServer-workerEventLoop26|2020-07-31 11:50:54.001 MSK|SSLEngineOutputRecord.java:173|outbound has closed, ignore outbound application data
javax.net.ssl|ALL|2B|MockServer-ClientAndServer-eventLoop12|2020-07-31 11:50:54.048 MSK|SSLEngineImpl.java:818|Closing outbound of SSLEngine
javax.net.ssl|WARNING|2B|MockServer-ClientAndServer-eventLoop12|2020-07-31 11:50:54.048 MSK|SSLEngineOutputRecord.java:173|outbound has closed, ignore outbound application data
javax.net.ssl|DEBUG|3A|MockServer-MockServer-workerEventLoop27|2020-07-31 11:50:54.050 MSK|Alert.java:238|Received alert message(
"Alert": {
  "level"      : "warning",
  "description": "close_notify"
}
)
javax.net.ssl|WARNING|3A|MockServer-MockServer-workerEventLoop27|2020-07-31 11:50:54.050 MSK|SSLEngineOutputRecord.java:173|outbound has closed, ignore outbound application data
2020-07-31 11:20:46 ERROR MockServerEventLog:102 - 50920 Connection failed to 0.0.0.0/0.0.0.0:50920
io.netty.channel.ConnectTimeoutException: connection timed out: 0.0.0.0/0.0.0.0:50920
  at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
  at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
  at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:170)
  at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
  at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
  at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
  at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
  at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  at java.base/java.lang.Thread.run(Thread.java:830)
```

**Comment by jamesdbloom** [comment]
As mentioned here it is not possible to do man-in-the-middle to URLs like https://www.google.com/ 

See: https://mock-server.com/mock_server/HTTPS_TLS.html#verify_trust_chain
> Some sites will work but others (such as google sites) won't work due to certificate pinning.
