### ISSUE TITLE
full exemple with self-generated CA and certs for mTLS

### ISSUE THREAD

**Issue by viollinn** [mock-server/mockserver#889]
Hello,

I've been trying for several days to make mTLS work following instructions in the docs in vain.
I ended up trying with the certs presents in `mockserver/mockserver-netty/src/test/resources/org/mockserver/netty/integration/tls` of the sources also in vain.

Here is my conf:

```
    image: mockserver/mockserver

    ports:
      - "1070:1080"

    environment:
      - MOCKSERVER_TLS_MUTUAL_AUTHENTICATION_REQUIRED=true
      - MOCKSERVER_TLS_MUTUAL_AUTHENTICATION_CERTIFICATE_CHAIN=/certificats/ca.pem
      - MOCKSERVER_TLS_PRIVATE_KEY_PATH=/certificats/leaf-key-pkcs8.pem
      - MOCKSERVER_TLS_X509_CERTIFICATE_PATH=/certificats/leaf-cert.pem
      - MOCKSERVER_LOG_LEVEL=debug
      - MOCKSERVER_WATCH_INITIALIZATION_JSON=true
      - MOCKSERVER_INITIALIZATION_JSON_PATH=mockserverInitialization.json
    volumes:
      - /home/me/mockserver/expectations.json:/mockserverInitialization.json
      - /home/me/mockserver/certificats:/certificats
```

I call mockserver using this curl command:
`curl -v --cacert ca.pem -E leaf-cert.pem --key leaf-key-pkcs8.pem https://localhost:1070/helloworld`

Here is what i got:
```
2020-10-13 14:08:53 5.11.1 SEVERE exception creating SSL context for serverfailed to initialize the server-side SSL context 
javax.net.ssl.SSLException: failed to initialize the server-side SSL context
        at io.netty.handler.ssl.JdkSslServerContext.newSSLContext(JdkSslServerContext.java:288)
        at io.netty.handler.ssl.JdkSslServerContext.<init>(JdkSslServerContext.java:247)
        at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:465)
        at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:571)
        at org.mockserver.socket.tls.NettySslContextFactory.createServerSslContext(NettySslContextFactory.java:142)
        at org.mockserver.socket.tls.SniHandler.lookup(SniHandler.java:31)
        at io.netty.handler.ssl.AbstractSniHandler.lookup(AbstractSniHandler.java:126)
        at io.netty.handler.ssl.SslClientHelloHandler.select(SslClientHelloHandler.java:188)
        at io.netty.handler.ssl.SslClientHelloHandler.decode(SslClientHelloHandler.java:169)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:501)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:440)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:404)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:371)
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
        at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
        at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:818)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.security.KeyStoreException: Key protection  algorithm not found: java.security.KeyStoreException: Certificate chain is not valid
        at java.base/sun.security.pkcs12.PKCS12KeyStore.setKeyEntry(PKCS12KeyStore.java:704)
        at java.base/sun.security.pkcs12.PKCS12KeyStore.engineSetKeyEntry(PKCS12KeyStore.java:601)
        at java.base/sun.security.util.KeyStoreDelegator.engineSetKeyEntry(KeyStoreDelegator.java:111)
        at java.base/java.security.KeyStore.setKeyEntry(KeyStore.java:1174)
        at io.netty.handler.ssl.SslContext.buildKeyStore(SslContext.java:1102)
        at io.netty.handler.ssl.SslContext.buildKeyManagerFactory(SslContext.java:1274)
        at io.netty.handler.ssl.SslContext.buildKeyManagerFactory(SslContext.java:1263)
        at io.netty.handler.ssl.JdkSslServerContext.newSSLContext(JdkSslServerContext.java:266)
        ... 27 more
Caused by: java.security.KeyStoreException: Certificate chain is not valid
        at java.base/sun.security.pkcs12.PKCS12KeyStore.setKeyEntry(PKCS12KeyStore.java:651)
```

Would you be kind enough to give a complete guide to generate certs (CA, private key, MockServer cert, MockServer private key, curl client cert and curl client private key) ?

For a newbie on certificates as i am it's a nightmare !!

Version is docker latest so probably 5.11.1.

Many thnx !

**Comment by jamesdbloom** [comment]
See also: https://github.com/mock-server/mockserver/issues/1107

**Comment by jamesdbloom** [comment]
This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/NGt4dtp2/188-full-example-with-self-generated-ca-and-certs-for-mtls

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.

**Comment by MPE04** [comment]
Hello, I'm currently facing the same kind of issue. 

@viollinn did you finally succed to find a procedure for your self-generated CA and certs ?

**Comment by matclab** [comment]
It looks like the problem comes from [BCKeyAndCertificateFactory.java#L387](https://github.com/mock-server/mockserver/blob/b607ad690543b17a6f6d6ecd92292ca3f28afe0d/mockserver-core/src/main/java/org/mockserver/socket/tls/bouncycastle/BCKeyAndCertificateFactory.java#L387) where the default `certificateAuthorityX509Certificate` is added to the certificate chain even for a self-signed certificate.
Commenting this line out in case of using a self-signed certificate seems to work as expected.


Also, as a side note, it looks to me that `customPrivateKeyAndCertificateProvided` should be names `customPrivateKeyAndCertificateNotProvided`

**Comment by banzade** [comment]
Are the instructions available now, for setting up https mock-server with custom certs?
@jamesdbloom
