### ISSUE TITLE
Unable to use HttpForward action with EC keys

### ISSUE THREAD

**Issue by kaaarel** [mock-server/mockserver#924]
**Describe the issue**
I'm trying to forward HTTPS request to a server with EC keys, but the connection disconnects.

**What you are trying to do**
Service x1 is not implemented fully and one of the endpoints needs to be mocked so service x2 could use it. So, mock-server should mock one endpoint for service x1 and redirect all other requests to the real x1 service. This service uses EC keys for SSL, but mock-server doesn't seem to support it, so I made a few changes to PEMToFile.java file. When I make a request, that should be forwarded, I get an error `io.netty.handler.proxy.ProxyConnectException: http, none, service_x2/127.0.0.1:8448 => service_x1/127.0.0.1:8447, disconnected`

**MockServer version**
5.11.3

**To Reproduce**
Steps to reproduce the issue:

1. This occurs both in docker and when running the jar
2. Run mockserver with the config that is shown below and with EC keys
3. Get error: `io.netty.handler.proxy.ProxyConnectException: http, none, service_x2/127.0.0.1:8448 => service_x1/127.0.0.1:8447, disconnected` and the service (written in golang) shows error `{"error":"http: TLS handshake error from 172.18.0.1:48684: tls: first record does not look like a TLS handshake\n"}`

mockserver.properties
```
mockserver.logLevel=TRACE

mockserver.maxSocketTimeout=120000

mockserver.dynamicallyCreateCertificateAuthorityCertificate=false

mockserver.enableCORSForAPI=true
mockserver.enableCORSForAllResponses=true

mockserver.initializationJsonPath=/path/to/initializerJson.json

mockserver.attemptToProxyIfNoMatchingExpectation=true
mockserver.forwardHttpsProxy=service_x2:8448

mockserver.privateKeyPath=/path/to/service_x1.key
mockserver.x509CertificatePath=/path/to/service_x1.crt
mockserver.forwardProxyPrivateKey=/path/to/service_x2.key
mockserver.forwardProxyCertificateChain=/path/to/service_x2.crt
mockserver.forwardProxyTLSCustomTrustX509Certificates=/path/to/CA.crt

mockserver.certificateAuthorityPrivateKey=/path/to/CA.key
mockserver.certificateAuthorityCertificate=/path/to/CA.crt

mockserver.serverPort=1080
mockserver.proxyRemotePort=8448
mockserver.proxyRemoteHost=service_x2

mockserver.forwardProxyTLSX509CertificatesTrustManagerType=CUSTOM
mockserver.useBouncyCastleForKeyAndCertificateGeneration=true

```
initializerJson.json
```json
[
  {
    "httpRequest": {
      "path": "/api/v1/report"
    },
    "httpResponse": {
      "body": "{'test':1}",
    }
  },
  {
    "httpRequest": {
      "path": ".*",
      "secure": true,
    },
    "httpForward": {
      "host": "service_x1",
      "port": 8447,
      "scheme": "HTTPS"
    }
  }
]

```
Changes to PEMToFile.java privateKeyFromPEM method
privateKeyFromPEM
```java
    public static PrivateKey privateKeyFromPEM(String pem) {
        try {
            Security.addProvider(new BouncyCastleProvider());
            PKCS8EncodedKeySpec spec = new PKCS8EncodedKeySpec(privateKeyBytesFromPEM(pem));
            ASN1InputStream bIn = new ASN1InputStream(new ByteArrayInputStream(spec.getEncoded()));
            PrivateKeyInfo pki = PrivateKeyInfo.getInstance(bIn.readObject());
            return new JcaPEMKeyConverter().setProvider("BC").getPrivateKey(pki);
        } catch (Exception e) {
            throw new RuntimeException("Exception reading private key from PEM file", e);
        }
    }

```
All of the code changes can be seen here: https://github.com/kaaarel/mockserver/commit/7fdb02c286599562acd2add08c799096422e8d64

**Expected behaviour**
I would like to get the request forwarded to service_x1 and get a response from there.

**MockServer Log**
```
2020-11-18 00:42:21 5.11.3-SNAPSHOT FINE using command line options:

  serverPort=1080

2020-11-18 00:42:21 5.11.3-SNAPSHOT INFO loading JSON initialization file:

  /path/to/initializerJson.json

2020-11-18 00:42:21 5.11.3-SNAPSHOT FINE loaded JSON initialization file:

  /path/to/initializerJson.json

 content:


  [
    {
      "httpRequest": {
        "path": "/api/v1/report"
      },
      "httpResponse": {
        "body": "{'test':1}",
      }
    },
    {
      "httpRequest": {
        "path": ".*",
        "secure": true,
      },
      "httpForward": {
        "host": "service_x1",
        "port": 8447,
        "scheme": "HTTPS"
      }
    }
  ]


2020-11-18 00:42:22 5.11.3-SNAPSHOT INFO creating expectation:

  {
    "id" : "011490c2-0db7-4ef8-bb4a-94223543d6fd",
    "priority" : 0,
    "httpRequest" : {
      "path" : "/api/v1/report"
    },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpResponse" : {
      "body" : "{'test':1}"
    }
  }

 with id:

  011490c2-0db7-4ef8-bb4a-94223543d6fd

2020-11-18 00:42:22 5.11.3-SNAPSHOT INFO creating expectation:

  {
    "id" : "a1b08bdf-2d88-44c4-8aea-462de71d14de",
    "priority" : 0,
    "httpRequest" : {
      "path" : ".*",
      "secure" : true
    },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpForward" : {
      "host" : "service_x1",
      "port" : 8447,
      "scheme" : "HTTPS"
    }
  }

 with id:

  a1b08bdf-2d88-44c4-8aea-462de71d14de

2020-11-18 00:42:22 5.11.3-SNAPSHOT INFO using Bouncy Castle for X.509 Certificate and Private Key generation
2020-11-18 00:42:22 5.11.3-SNAPSHOT FINEST logger level is TRACE, change using:
 - 'ConfigurationProperties.logLevel(String level)' in Java code,
 - '-logLevel' command line argument,
 - 'mockserver.logLevel' JVM system property or,
 - 'mockserver.logLevel' property value in 'mockserver.properties'
2020-11-18 00:42:22 5.11.3-SNAPSHOT INFO 1080 started on port: 1080
2020-11-18 00:42:30 5.11.3-SNAPSHOT FINEST adding TLS decoders for channel:

  [id: 0x4c624305, L:/127.0.0.1:1080 - R:/127.0.0.1:57411]

 pipeline:

  [PortUnificationHandler#0, DefaultChannelPipeline$TailContext#0]

2020-11-18 00:42:30 5.11.3-SNAPSHOT FINEST loaded dynamic CA X509 from path

  /path/to/CA.crt

 from PEM

  -----BEGIN CERTIFICATE-----
  ...
  -----END CERTIFICATE-----


 as

  [
  [
    Version: V3
    Subject: CN=..., OU=Local, O=LocalO
    Signature Algorithm: SHA256withECDSA, OID = 1.2.840.10045.4.3.2

    Key:  Sun EC public key, 256 bits
    public x coord: ...
    public y coord: ...
    parameters: secp256r1 [NIST P-256,X9.62 prime256v1] (1.2.840.10045.3.1.7)
    Validity: [From: Wed Mar 22 09:11:57 CET 2020,
                 To: Fri Mar 22 09:11:57 CET 2022]
    Issuer: CN=..., OU=Local, O=LocalO
    SerialNumber: [    ...]

  Certificate Extensions: 3
  [1]: ObjectId: 2.5.29.19 Criticality=true
  BasicConstraints:[
    CA:true
    PathLen:...
  ]

  [2]: ObjectId: 2.5.29.37 Criticality=false
  ExtendedKeyUsages [
    clientAuth
    serverAuth
  ]

  [3]: ObjectId: 2.5.29.15 Criticality=true
  KeyUsage [
    DigitalSignature
    Key_Encipherment
    Key_CertSign
  ]

  ]
    Algorithm: [SHA256withECDSA]
    Signature:
		...
  ]

2020-11-18 00:42:31 5.11.3-SNAPSHOT FINEST adding HTTP decoders for channel:

  [id: 0x4c624305, L:/127.0.0.1:1080 - R:/127.0.0.1:57411]

 pipeline:

  [io.netty.handler.ssl.SslHandler, LoggingHandler#0, PortUnificationHandler#0, LoggingHandler#1, DefaultChannelPipeline$TailContext#0]

2020-11-18 00:42:31 5.11.3-SNAPSHOT FINEST 1080 received request:

  {
    "method" : "GET",
    "path" : "/api/v1/heartbeat",
    "headers" : {
      "User-Agent" : [ "PostmanRuntime/7.26.5" ],
      "Accept" : [ "*/*" ],
      "Postman-Token" : [ "d25fa2ed-35e9-469d-abb4-18b799731914" ],
      "Host" : [ "service_x1:1080" ],
      "Accept-Encoding" : [ "gzip, deflate, br" ],
      "Connection" : [ "keep-alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : true
  }

2020-11-18 00:42:31 5.11.3-SNAPSHOT INFO 1080 received request:

  {
    "method" : "GET",
    "path" : "/api/v1/heartbeat",
    "headers" : {
      "User-Agent" : [ "PostmanRuntime/7.26.5" ],
      "Accept" : [ "*/*" ],
      "Postman-Token" : [ "d25fa2ed-35e9-469d-abb4-18b799731914" ],
      "Host" : [ "service_x1:1080" ],
      "Accept-Encoding" : [ "gzip, deflate, br" ],
      "Connection" : [ "keep-alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : true
  }

2020-11-18 00:42:31 5.11.3-SNAPSHOT FINEST 1080 string or regex match failed expected:

  /api/v1/report

 found:

  /api/v1/heartbeat

2020-11-18 00:42:31 5.11.3-SNAPSHOT INFO 1080 request:

  {
    "method" : "GET",
    "path" : "/api/v1/heartbeat",
    "headers" : {
      "User-Agent" : [ "PostmanRuntime/7.26.5" ],
      "Accept" : [ "*/*" ],
      "Postman-Token" : [ "d25fa2ed-35e9-469d-abb4-18b799731914" ],
      "Host" : [ "service_x1:1080" ],
      "Accept-Encoding" : [ "gzip, deflate, br" ],
      "Connection" : [ "keep-alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : true
  }

 didn't match expectation:

  {
    "id" : "011490c2-0db7-4ef8-bb4a-94223543d6fd",
    "priority" : 0,
    "httpRequest" : {
      "path" : "/api/v1/report"
    },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpResponse" : {
      "body" : "{'test':1}"
    }
  }

 because:

  method matched
  path didn't match:

    string or regex match failed expected:

      /api/v1/report

     found:

      /api/v1/heartbeat


2020-11-18 00:42:31 5.11.3-SNAPSHOT INFO 1080 request:

  {
    "method" : "GET",
    "path" : "/api/v1/heartbeat",
    "headers" : {
      "User-Agent" : [ "PostmanRuntime/7.26.5" ],
      "Accept" : [ "*/*" ],
      "Postman-Token" : [ "d25fa2ed-35e9-469d-abb4-18b799731914" ],
      "Host" : [ "service_x1:1080" ],
      "Accept-Encoding" : [ "gzip, deflate, br" ],
      "Connection" : [ "keep-alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : true
  }

 matched expectation:

  {
    "id" : "a1b08bdf-2d88-44c4-8aea-462de71d14de",
    "priority" : 0,
    "httpRequest" : {
      "path" : ".*",
      "secure" : true
    },
    "times" : {
      "unlimited" : true
    },
    "timeToLive" : {
      "unlimited" : true
    },
    "httpForward" : {
      "host" : "service_x1",
      "port" : 8447,
      "scheme" : "HTTPS"
    }
  }

2020-11-18 00:42:31 5.11.3-SNAPSHOT INFO http, none, service_x2/127.0.0.1:8448 => service_x1/127.0.0.1:8447, disconnected
io.netty.handler.proxy.ProxyConnectException: http, none, service_x2/127.0.0.1:8448 => service_x1/127.0.0.1:8447, disconnected
	at io.netty.handler.proxy.ProxyHandler.channelInactive(ProxyHandler.java:234)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
	at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:311)
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221)
	at io.netty.handler.proxy.HttpProxyHandler$HttpClientCodecWrapper.channelInactive(HttpProxyHandler.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:819)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:832)

2020-11-18 00:42:31 5.11.3-SNAPSHOT SEVERE 1080 io.netty.handler.proxy.ProxyConnectException: http, none, service_x2/127.0.0.1:8448 => service_x1/127.0.0.1:8447, disconnected
java.util.concurrent.ExecutionException: io.netty.handler.proxy.ProxyConnectException: http, none, service_x2/127.0.0.1:8448 => service_x1/127.0.0.1:8447, disconnected
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2086)
	at org.mockserver.mock.action.http.HttpActionHandler.lambda$writeForwardActionResponse$21(HttpActionHandler.java:346)
	at org.mockserver.scheduler.Scheduler.run(Scheduler.java:86)
	at org.mockserver.scheduler.Scheduler.lambda$submit$2(Scheduler.java:171)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: io.netty.handler.proxy.ProxyConnectException: http, none, service_x2/127.0.0.1:8448 => service_x1/127.0.0.1:8447, disconnected
	at io.netty.handler.proxy.ProxyHandler.channelInactive(ProxyHandler.java:234)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelInactive(CombinedChannelDuplexHandler.java:418)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:389)
	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:354)
	at io.netty.handler.codec.http.HttpClientCodec$Decoder.channelInactive(HttpClientCodec.java:311)
	at io.netty.channel.CombinedChannelDuplexHandler.channelInactive(CombinedChannelDuplexHandler.java:221)
	at io.netty.handler.proxy.HttpProxyHandler$HttpClientCodecWrapper.channelInactive(HttpProxyHandler.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:241)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1405)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:262)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:248)
	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:901)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:819)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	... 1 more

2020-11-18 00:42:31 5.11.3-SNAPSHOT INFO 1080 no expectation for:

  {
    "method" : "GET",
    "path" : "/api/v1/heartbeat",
    "headers" : {
      "User-Agent" : [ "PostmanRuntime/7.26.5" ],
      "Accept" : [ "*/*" ],
      "Postman-Token" : [ "d25fa2ed-35e9-469d-abb4-18b799731914" ],
      "Host" : [ "service_x1:1080" ],
      "Accept-Encoding" : [ "gzip, deflate, br" ],
      "Connection" : [ "keep-alive" ],
      "content-length" : [ "0" ]
    },
    "keepAlive" : true,
    "secure" : true
  }

 returning response:

  {
    "statusCode" : 404,
    "reasonPhrase" : "Not Found"
  }
```

**Comment by jamesdbloom** [comment]
I agree that makes sense.

This feature request has been accepted, new feature requests are prioritised on Trello, so closing issue in GitHub, only bugs or unaccepted feature requests will stay in GitHub, so that new feature backlog can be more effectively managed, see: https://trello.com/c/zIl5yDEz/178-support-ec-certificates

However when this feature is implemented this issue will be checked so please continue any conversation related to this issue here.

**Comment by pascal-hofmann** [comment]
FYI: I just started working on a PR for this.
