### ISSUE TITLE
Setting MOCKSERVER_INITIALIZATION_JSON_PATH on docker leads to "Permission denied" file exception

### ISSUE THREAD

**Issue by paulohenriquesg** [mock-server/mockserver#943]
**Describe the issue**
Using the mock-server docker image, setting the `MOCKSERVER_INITIALIZATION_JSON_PATH` environment variable leads to an exception. 

**What you are trying to do**
Using the mock-server docker image, I want to set the `MOCKSERVER_INITIALIZATION_JSON_PATH` environment variable to be able to persist the expectations.

The initialization process runs without issues, but I can see on the dashboard the following messages:

```
loading JSON initialization file:	"/config/initializerJson.json"
exception while loading JSON initialization file, ignoring file	
```

And the trace of the exception is as follows:

```
java.lang.RuntimeException: Exception while loading "/config/initializerJson.json"
	at org.mockserver.file.FileReader.readFileFromClassPathOrPath(FileReader.java:24)
	at org.mockserver.server.initialize.ExpectationInitializerLoader.retrieveExpectationsFromJson(ExpectationInitializerLoader.java:83)
	at org.mockserver.server.initialize.ExpectationInitializerLoader.loadExpectations(ExpectationInitializerLoader.java:115)
	at org.mockserver.server.initialize.ExpectationInitializerLoader.addExpectationsFromInitializer(ExpectationInitializerLoader.java:37)
	at org.mockserver.server.initialize.ExpectationInitializerLoader.<init>(ExpectationInitializerLoader.java:33)
	at org.mockserver.mock.HttpState.<init>(HttpState.java:120)
	at org.mockserver.lifecycle.LifeCycle.<init>(LifeCycle.java:51)
	at org.mockserver.netty.MockServer.<init>(MockServer.java:50)
	at org.mockserver.netty.MockServer.<init>(MockServer.java:41)
	at org.mockserver.cli.Main.main(Main.java:100)
Caused by: java.io.FileNotFoundException: /config/initializerJson.json (Permission denied)
	at java.base/java.io.FileInputStream.open0(Native Method)
	at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:112)
	at org.mockserver.file.FileReader.openStreamToFileFromClassPathOrPath(FileReader.java:32)
	at org.mockserver.file.FileReader.readFileFromClassPathOrPath(FileReader.java:21)
	... 9 more
```

**MockServer version**
Tried the configuration with the 5.11.1 and 5.11.2 docker images

**To Reproduce**
Steps to reproduce the issue:

1. Create a directory on this structure: /data/mock-server
2. Change the mockserver docker-compose, as follows:

```
mockServer:
      image: mockserver/mockserver:latest
      ports:
          - 1080:1080
      environment:
          MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
          MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
      volumes:
          -   type: bind
              source: ./data/mock-server
              target: /config
```

3. Start the docker image and access the dashboard. the 2 messages should be displayed there.

**Expected behaviour**
I'd expect that, if some extra steps are needed (permission wise, to make the file readable/writeable), this would be available on the documentation.

**MockServer Log**
Log output, as INFO level (or lower)

**Comment by saharemanish** [comment]
Did you find the answer for this issue?

**Comment by fullkomnun** [comment]
@saharemanish  take a look at [this PR](https://github.com/mock-server/mockserver/pull/936/files), it worked for me

**Comment by saharemanish** [comment]
Hi,
I am able to make it work for me by changing the volumes configuration 
from
 volumes:
          -   type: bind
              source: ./data/mock-server
              target: /config
to 
    volumes:
      - ./config/:/config

**Comment by 70m4** [comment]
Hello,
I had the same issue, and you need to configure docker to the new file sharing restrictions, follow [this post:](https://stackoverflow.com/a/60814428/4223102)
or  [this doc](https://docs.docker.com/desktop/windows/)

**Comment by jamesdbloom** [comment]
Please see a working example here: https://github.com/mock-server/mockserver/tree/master/container_integration_tests/docker_compose_with_expectation_initialiser
